
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */

package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>ScreeningEntity Projector</h2>
 * <p>
 * The Screening Entity Projector is responsible for maintaining the read model for
 * Screening entities. It subscribes to domain events published by the Screening
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>ScreeningRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("screening-entity-projector")
public class ScreeningEntityProjector implements EntityProjector<Screening>{
		
	// core constructor
	public ScreeningEntityProjector(ProjectorRegistry registry,
										ScreeningRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<Screening> getEntityClass() {
		return Screening.class;
	}

    /*
	 * Insert a Screening
	 * 
     * @param	entity Screening
     */
    public Screening create( Screening entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a Screening
	 * 
     * @param	entity Screening
     */
    public Screening update( Screening entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a Screening
	 * 
     * @param	id		UUID
     */
    public Screening delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    Screening entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a KycProfile
     * 
     * @param	parentId	UUID
     * @param	childId		UUID
     * @return	Screening
     */
    public Screening assignKycProfile( UUID parentId, UUID childId ) {
	    LOGGER.info("assigning KycProfile as " + childId.toString());

	    Screening parentEntity = repository.findById( parentId ).get();
		KYCProfile assignment = registry.project( KYCProfile.class, childId);

	    // ------------------------------------------
		// assign the KycProfile to the parent entity
		// ------------------------------------------ 
	    parentEntity.setKycProfile( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the KycProfile
	 * 
	 * @param	parentId		UUID
	 * @return	Screening
	 */
	public Screening unAssignKycProfile( UUID parentId ) {
		Screening parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning KycProfile on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the KycProfile on the parent entithy
		// ------------------------------------------     
	    parentEntity.setKycProfile(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}


    /*
     * Add to the Alerts
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Screening
     */
    public Screening addToAlerts( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling AssignAlertsToScreeningEvent - " );
	    
	    Screening parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			ComplianceAlert child = registry.project(ComplianceAlert.class, childId);
			parentEntity.getAlerts().add(child);
		}

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Alerts
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Screening
     */
	public Screening removeFromAlerts( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling RemoveAlertsFromScreeningEvent " );
	    Screening parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			ComplianceAlert child = registry.project(ComplianceAlert.class, childId);
			parentEntity.getAlerts().remove( child );
		}

	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the Screening via an FindScreeningQuery
     * @return 	query	FindScreeningQuery
     */
    @SuppressWarnings("unused")
    public Screening find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a Screening - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all Screenings
     *
     * @param	query	FindAllScreeningQuery 
     * @return 	List<Screening> 
     */
    @SuppressWarnings("unused")
    public List<Screening> findAll( FindAllScreeningQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all Screening - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final ScreeningRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(ScreeningEntityProjector.class.getName());

}
