
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */

package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>TransactionEntity Projector</h2>
 * <p>
 * The Transaction Entity Projector is responsible for maintaining the read model for
 * Transaction entities. It subscribes to domain events published by the Transaction
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>TransactionRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("transaction-entity-projector")
public class TransactionEntityProjector implements EntityProjector<Transaction>{
		
	// core constructor
	public TransactionEntityProjector(ProjectorRegistry registry,
										TransactionRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<Transaction> getEntityClass() {
		return Transaction.class;
	}

    /*
	 * Insert a Transaction
	 * 
     * @param	entity Transaction
     */
    public Transaction create( Transaction entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a Transaction
	 * 
     * @param	entity Transaction
     */
    public Transaction update( Transaction entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a Transaction
	 * 
     * @param	id		UUID
     */
    public Transaction delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    Transaction entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Account
     * 
     * @param	parentId	UUID
     * @param	childId		UUID
     * @return	Transaction
     */
    public Transaction assignAccount( UUID parentId, UUID childId ) {
	    LOGGER.info("assigning Account as " + childId.toString());

	    Transaction parentEntity = repository.findById( parentId ).get();
		Account assignment = registry.project( Account.class, childId);

	    // ------------------------------------------
		// assign the Account to the parent entity
		// ------------------------------------------ 
	    parentEntity.setAccount( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Account
	 * 
	 * @param	parentId		UUID
	 * @return	Transaction
	 */
	public Transaction unAssignAccount( UUID parentId ) {
		Transaction parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Account on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Account on the parent entithy
		// ------------------------------------------     
	    parentEntity.setAccount(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a Wallet
     * 
     * @param	parentId	UUID
     * @param	childId		UUID
     * @return	Transaction
     */
    public Transaction assignWallet( UUID parentId, UUID childId ) {
	    LOGGER.info("assigning Wallet as " + childId.toString());

	    Transaction parentEntity = repository.findById( parentId ).get();
		Wallet assignment = registry.project( Wallet.class, childId);

	    // ------------------------------------------
		// assign the Wallet to the parent entity
		// ------------------------------------------ 
	    parentEntity.setWallet( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Wallet
	 * 
	 * @param	parentId		UUID
	 * @return	Transaction
	 */
	public Transaction unAssignWallet( UUID parentId ) {
		Transaction parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Wallet on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Wallet on the parent entithy
		// ------------------------------------------     
	    parentEntity.setWallet(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a PaymentOrder
     * 
     * @param	parentId	UUID
     * @param	childId		UUID
     * @return	Transaction
     */
    public Transaction assignPaymentOrder( UUID parentId, UUID childId ) {
	    LOGGER.info("assigning PaymentOrder as " + childId.toString());

	    Transaction parentEntity = repository.findById( parentId ).get();
		PaymentOrder assignment = registry.project( PaymentOrder.class, childId);

	    // ------------------------------------------
		// assign the PaymentOrder to the parent entity
		// ------------------------------------------ 
	    parentEntity.setPaymentOrder( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the PaymentOrder
	 * 
	 * @param	parentId		UUID
	 * @return	Transaction
	 */
	public Transaction unAssignPaymentOrder( UUID parentId ) {
		Transaction parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning PaymentOrder on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the PaymentOrder on the parent entithy
		// ------------------------------------------     
	    parentEntity.setPaymentOrder(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a Merchant
     * 
     * @param	parentId	UUID
     * @param	childId		UUID
     * @return	Transaction
     */
    public Transaction assignMerchant( UUID parentId, UUID childId ) {
	    LOGGER.info("assigning Merchant as " + childId.toString());

	    Transaction parentEntity = repository.findById( parentId ).get();
		Merchant assignment = registry.project( Merchant.class, childId);

	    // ------------------------------------------
		// assign the Merchant to the parent entity
		// ------------------------------------------ 
	    parentEntity.setMerchant( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Merchant
	 * 
	 * @param	parentId		UUID
	 * @return	Transaction
	 */
	public Transaction unAssignMerchant( UUID parentId ) {
		Transaction parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Merchant on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Merchant on the parent entithy
		// ------------------------------------------     
	    parentEntity.setMerchant(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a Card
     * 
     * @param	parentId	UUID
     * @param	childId		UUID
     * @return	Transaction
     */
    public Transaction assignCard( UUID parentId, UUID childId ) {
	    LOGGER.info("assigning Card as " + childId.toString());

	    Transaction parentEntity = repository.findById( parentId ).get();
		PaymentCard assignment = registry.project( PaymentCard.class, childId);

	    // ------------------------------------------
		// assign the Card to the parent entity
		// ------------------------------------------ 
	    parentEntity.setCard( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Card
	 * 
	 * @param	parentId		UUID
	 * @return	Transaction
	 */
	public Transaction unAssignCard( UUID parentId ) {
		Transaction parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Card on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Card on the parent entithy
		// ------------------------------------------     
	    parentEntity.setCard(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}


    /*
     * Add to the RelatedTransactions
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Transaction
     */
    public Transaction addToRelatedTransactions( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling AssignRelatedTransactionsToTransactionEvent - " );
	    
	    Transaction parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			Transaction child = registry.project(Transaction.class, childId);
			parentEntity.getRelatedTransactions().add(child);
		}

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the RelatedTransactions
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Transaction
     */
	public Transaction removeFromRelatedTransactions( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling RemoveRelatedTransactionsFromTransactionEvent " );
	    Transaction parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			Transaction child = registry.project(Transaction.class, childId);
			parentEntity.getRelatedTransactions().remove( child );
		}

	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Alerts
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Transaction
     */
    public Transaction addToAlerts( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling AssignAlertsToTransactionEvent - " );
	    
	    Transaction parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			ComplianceAlert child = registry.project(ComplianceAlert.class, childId);
			parentEntity.getAlerts().add(child);
		}

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Alerts
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Transaction
     */
	public Transaction removeFromAlerts( UUID parentId, List<UUID> children ) {
	    LOGGER.info("handling RemoveAlertsFromTransactionEvent " );
	    Transaction parentEntity = repository.findById(parentId).get();

		for (UUID childId : children) {
			ComplianceAlert child = registry.project(ComplianceAlert.class, childId);
			parentEntity.getAlerts().remove( child );
		}

	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the Transaction via an FindTransactionQuery
     * @return 	query	FindTransactionQuery
     */
    @SuppressWarnings("unused")
    public Transaction find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a Transaction - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all Transactions
     *
     * @param	query	FindAllTransactionQuery 
     * @return 	List<Transaction> 
     */
    @SuppressWarnings("unused")
    public List<Transaction> findAll( FindAllTransactionQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all Transaction - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final TransactionRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(TransactionEntityProjector.class.getName());

}
