/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>AccountValidation</h2>
 * <p>
 * The Account Validation  handles state validation of a Account include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateAccountCommand</li>
 *      <li>UpdateAccountCommand</li>
 *      <li>DeleteAccountCommand</li>
 *set( false = false )
  *       <li>AssignCustomerToAccountCommand</li>
 *       <li>UnAssignCustomerFromAccountCommand</li>
  *       <li>AssignInstitutionToAccountCommand</li>
 *       <li>UnAssignInstitutionFromAccountCommand</li>
   *       <li>AssignTransactionsToAccountCommand</li>
 *       <li>RemoveTransactionsFromAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignCardsToAccountCommand</li>
 *       <li>RemoveCardsFromAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignStatementsToAccountCommand</li>
 *       <li>RemoveStatementsFromAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignMandatesToAccountCommand</li>
 *       <li>RemoveMandatesFromAccountCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class AccountValidator {

	/**
	 * default constructor
	 */
	protected AccountValidator() {
	}


	/**
	 * handles creation validation for a Account
	 */
	public void validate( CreateAccountCommand account )throws ValidationException {
		if ( account == null )
			throw new ValidationException( "Account", "validating CreateAccountCommand" );
		if ( account.getAccountNumber() == null )
			throw new ValidationException( "Account", "validating access on getAccountNumber" );
		if ( account.getIban() == null )
			throw new ValidationException( "Account", "validating access on getIban" );
		if ( account.getBic() == null )
			throw new ValidationException( "Account", "validating access on getBic" );
		if ( account.getOpenedDate() == null )
			throw new ValidationException( "Account", "validating access on getOpenedDate" );
		if ( account.getCurrency() == null )
			throw new ValidationException( "Account", "validating access on getCurrency" );
		if ( account.getBalance() == null )
			throw new ValidationException( "Account", "validating access on getBalance" );
		if ( account.getAvailableBalance() == null )
			throw new ValidationException( "Account", "validating access on getAvailableBalance" );
	}

	/**
	 * handles update validation for a Account
	 */
	public void validate( UpdateAccountCommand account ) throws ValidationException {
		if ( account == null )
			throw new ValidationException( "Account", "validating UpdateAccountCommand" );
		if ( account.getAccountNumber() == null )
			throw new ValidationException( "Account", "validating method getAccountNumber" );
		if ( account.getIban() == null )
			throw new ValidationException( "Account", "validating method getIban" );
		if ( account.getBic() == null )
			throw new ValidationException( "Account", "validating method getBic" );
		if ( account.getOpenedDate() == null )
			throw new ValidationException( "Account", "validating method getOpenedDate" );
		if ( account.getCurrency() == null )
			throw new ValidationException( "Account", "validating method getCurrency" );
		if ( account.getBalance() == null )
			throw new ValidationException( "Account", "validating method getBalance" );
		if ( account.getAvailableBalance() == null )
			throw new ValidationException( "Account", "validating method getAvailableBalance" );
	}

/**
 * handles delete validation for a Account
 */
	public void validate( DeleteAccountCommand account ) throws ValidationException {
		if ( account == null )
			throw new ValidationException( "Account", "validating DeleteAccountCommand" );

		if ( account.getId() == null )
			throw new ValidationException( "Account", "validating DeleteAccountCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Account
 */
	public void validate( AccountFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Account", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Account", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Customer validation for a Account
	 *
	 * @param	command AssignCustomerToAccountCommand
	 */
	public void validate( AssignCustomerToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignCustomerToAccountCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Account", "validating identity on AssignCustomerToAccountCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Customer validation for a Account
	 *
	 * @param	command UnAssignCustomerFromAccountCommand
	 */
	public void validate( UnAssignCustomerFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating UnAssignCustomerFromAccountCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Account", "validating identity on UnAssignCustomerFromAccountCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Institution validation for a Account
	 *
	 * @param	command AssignInstitutionToAccountCommand
	 */
	public void validate( AssignInstitutionToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignInstitutionToAccountCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Account", "validating identity on AssignInstitutionToAccountCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Institution validation for a Account
	 *
	 * @param	command UnAssignInstitutionFromAccountCommand
	 */
	public void validate( UnAssignInstitutionFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating UnAssignInstitutionFromAccountCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Account", "validating identity on UnAssignInstitutionFromAccountCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Transactions validation for a Account
	 *
	 * @param	command AssignTransactionsToAccountCommand
	 */
	public void validate( AssignTransactionsToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignTransactionsToAccountCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Account", "validating identity on AssignTransactionsToAccountCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Transactions validation for a Account
	 *
	 * @param	command RemoveTransactionsFromAccountCommand
	 */
	public void validate( RemoveTransactionsFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Account", "validating RemoveTransactionsFromAccountCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Account", "validating identity on RemoveTransactionsFromAccountCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Cards validation for a Account
	 *
	 * @param	command AssignCardsToAccountCommand
	 */
	public void validate( AssignCardsToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignCardsToAccountCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Account", "validating identity on AssignCardsToAccountCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Cards validation for a Account
	 *
	 * @param	command RemoveCardsFromAccountCommand
	 */
	public void validate( RemoveCardsFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Account", "validating RemoveCardsFromAccountCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Account", "validating identity on RemoveCardsFromAccountCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Statements validation for a Account
	 *
	 * @param	command AssignStatementsToAccountCommand
	 */
	public void validate( AssignStatementsToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignStatementsToAccountCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Account", "validating identity on AssignStatementsToAccountCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Statements validation for a Account
	 *
	 * @param	command RemoveStatementsFromAccountCommand
	 */
	public void validate( RemoveStatementsFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Account", "validating RemoveStatementsFromAccountCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Account", "validating identity on RemoveStatementsFromAccountCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Mandates validation for a Account
	 *
	 * @param	command AssignMandatesToAccountCommand
	 */
	public void validate( AssignMandatesToAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Account", "validating AssignMandatesToAccountCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Account", "validating identity on AssignMandatesToAccountCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Mandates validation for a Account
	 *
	 * @param	command RemoveMandatesFromAccountCommand
	 */
	public void validate( RemoveMandatesFromAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Account", "validating RemoveMandatesFromAccountCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Account", "validating identity on RemoveMandatesFromAccountCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
