/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>APIClientValidation</h2>
 * <p>
 * The APIClient Validation  handles state validation of a APIClient include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateAPIClientCommand</li>
 *      <li>UpdateAPIClientCommand</li>
 *      <li>DeleteAPIClientCommand</li>
 *set( false = false )
   *       <li>AssignConsentsToAPIClientCommand</li>
 *       <li>RemoveConsentsFromAPIClientCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class APIClientValidator {

	/**
	 * default constructor
	 */
	protected APIClientValidator() {
	}


	/**
	 * handles creation validation for a APIClient
	 */
	public void validate( CreateAPIClientCommand aPIClient )throws ValidationException {
		if ( aPIClient == null )
			throw new ValidationException( "APIClient", "validating CreateAPIClientCommand" );
		if ( aPIClient.getName() == null )
			throw new ValidationException( "APIClient", "validating access on getName" );
		if ( aPIClient.getClientId() == null )
			throw new ValidationException( "APIClient", "validating access on getClientId" );
		if ( aPIClient.getRedirectUri() == null )
			throw new ValidationException( "APIClient", "validating access on getRedirectUri" );
	}

	/**
	 * handles update validation for a APIClient
	 */
	public void validate( UpdateAPIClientCommand aPIClient ) throws ValidationException {
		if ( aPIClient == null )
			throw new ValidationException( "APIClient", "validating UpdateAPIClientCommand" );
		if ( aPIClient.getName() == null )
			throw new ValidationException( "APIClient", "validating method getName" );
		if ( aPIClient.getClientId() == null )
			throw new ValidationException( "APIClient", "validating method getClientId" );
		if ( aPIClient.getRedirectUri() == null )
			throw new ValidationException( "APIClient", "validating method getRedirectUri" );
	}

/**
 * handles delete validation for a APIClient
 */
	public void validate( DeleteAPIClientCommand aPIClient ) throws ValidationException {
		if ( aPIClient == null )
			throw new ValidationException( "APIClient", "validating DeleteAPIClientCommand" );

		if ( aPIClient.getId() == null )
			throw new ValidationException( "APIClient", "validating DeleteAPIClientCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a APIClient
 */
	public void validate( APIClientFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "APIClient", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "APIClient", "validating FetchOneSummary identifier discovered as null" );
	}


	/**
	 * handles add to Consents validation for a APIClient
	 *
	 * @param	command AssignConsentsToAPIClientCommand
	 */
	public void validate( AssignConsentsToAPIClientCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "APIClient", "validating AssignConsentsToAPIClientCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "APIClient", "validating identity on AssignConsentsToAPIClientCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Consents validation for a APIClient
	 *
	 * @param	command RemoveConsentsFromAPIClientCommand
	 */
	public void validate( RemoveConsentsFromAPIClientCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("APIClient", "validating RemoveConsentsFromAPIClientCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "APIClient", "validating identity on RemoveConsentsFromAPIClientCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
