/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>BranchValidation</h2>
 * <p>
 * The Branch Validation  handles state validation of a Branch include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateBranchCommand</li>
 *      <li>UpdateBranchCommand</li>
 *      <li>DeleteBranchCommand</li>
 *set( false = false )
  *       <li>AssignInstitutionToBranchCommand</li>
 *       <li>UnAssignInstitutionFromBranchCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class BranchValidator {

	/**
	 * default constructor
	 */
	protected BranchValidator() {
	}


	/**
	 * handles creation validation for a Branch
	 */
	public void validate( CreateBranchCommand branch )throws ValidationException {
		if ( branch == null )
			throw new ValidationException( "Branch", "validating CreateBranchCommand" );
		if ( branch.getName() == null )
			throw new ValidationException( "Branch", "validating access on getName" );
		if ( branch.getBranchCode() == null )
			throw new ValidationException( "Branch", "validating access on getBranchCode" );
		if ( branch.getAddress() == null )
			throw new ValidationException( "Branch", "validating access on getAddress" );
	}

	/**
	 * handles update validation for a Branch
	 */
	public void validate( UpdateBranchCommand branch ) throws ValidationException {
		if ( branch == null )
			throw new ValidationException( "Branch", "validating UpdateBranchCommand" );
		if ( branch.getName() == null )
			throw new ValidationException( "Branch", "validating method getName" );
		if ( branch.getBranchCode() == null )
			throw new ValidationException( "Branch", "validating method getBranchCode" );
		if ( branch.getAddress() == null )
			throw new ValidationException( "Branch", "validating method getAddress" );
	}

/**
 * handles delete validation for a Branch
 */
	public void validate( DeleteBranchCommand branch ) throws ValidationException {
		if ( branch == null )
			throw new ValidationException( "Branch", "validating DeleteBranchCommand" );

		if ( branch.getId() == null )
			throw new ValidationException( "Branch", "validating DeleteBranchCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Branch
 */
	public void validate( BranchFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Branch", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Branch", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Institution validation for a Branch
	 *
	 * @param	command AssignInstitutionToBranchCommand
	 */
	public void validate( AssignInstitutionToBranchCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Branch", "validating AssignInstitutionToBranchCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Branch", "validating identity on AssignInstitutionToBranchCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Institution validation for a Branch
	 *
	 * @param	command UnAssignInstitutionFromBranchCommand
	 */
	public void validate( UnAssignInstitutionFromBranchCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Branch", "validating UnAssignInstitutionFromBranchCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Branch", "validating identity on UnAssignInstitutionFromBranchCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}


}
