/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>ConsentValidation</h2>
 * <p>
 * The Consent Validation  handles state validation of a Consent include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateConsentCommand</li>
 *      <li>UpdateConsentCommand</li>
 *      <li>DeleteConsentCommand</li>
 *set( false = false )
  *       <li>AssignCustomerToConsentCommand</li>
 *       <li>UnAssignCustomerFromConsentCommand</li>
  *       <li>AssignApiClientToConsentCommand</li>
 *       <li>UnAssignApiClientFromConsentCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class ConsentValidator {

	/**
	 * default constructor
	 */
	protected ConsentValidator() {
	}


	/**
	 * handles creation validation for a Consent
	 */
	public void validate( CreateConsentCommand consent )throws ValidationException {
		if ( consent == null )
			throw new ValidationException( "Consent", "validating CreateConsentCommand" );
		if ( consent.getGrantedAt() == null )
			throw new ValidationException( "Consent", "validating access on getGrantedAt" );
		if ( consent.getExpiresAt() == null )
			throw new ValidationException( "Consent", "validating access on getExpiresAt" );
		if ( consent.getScope() == null )
			throw new ValidationException( "Consent", "validating access on getScope" );
	}

	/**
	 * handles update validation for a Consent
	 */
	public void validate( UpdateConsentCommand consent ) throws ValidationException {
		if ( consent == null )
			throw new ValidationException( "Consent", "validating UpdateConsentCommand" );
		if ( consent.getGrantedAt() == null )
			throw new ValidationException( "Consent", "validating method getGrantedAt" );
		if ( consent.getExpiresAt() == null )
			throw new ValidationException( "Consent", "validating method getExpiresAt" );
		if ( consent.getScope() == null )
			throw new ValidationException( "Consent", "validating method getScope" );
	}

/**
 * handles delete validation for a Consent
 */
	public void validate( DeleteConsentCommand consent ) throws ValidationException {
		if ( consent == null )
			throw new ValidationException( "Consent", "validating DeleteConsentCommand" );

		if ( consent.getId() == null )
			throw new ValidationException( "Consent", "validating DeleteConsentCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Consent
 */
	public void validate( ConsentFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Consent", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Consent", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Customer validation for a Consent
	 *
	 * @param	command AssignCustomerToConsentCommand
	 */
	public void validate( AssignCustomerToConsentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Consent", "validating AssignCustomerToConsentCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Consent", "validating identity on AssignCustomerToConsentCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Customer validation for a Consent
	 *
	 * @param	command UnAssignCustomerFromConsentCommand
	 */
	public void validate( UnAssignCustomerFromConsentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Consent", "validating UnAssignCustomerFromConsentCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Consent", "validating identity on UnAssignCustomerFromConsentCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign ApiClient validation for a Consent
	 *
	 * @param	command AssignApiClientToConsentCommand
	 */
	public void validate( AssignApiClientToConsentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Consent", "validating AssignApiClientToConsentCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Consent", "validating identity on AssignApiClientToConsentCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign ApiClient validation for a Consent
	 *
	 * @param	command UnAssignApiClientFromConsentCommand
	 */
	public void validate( UnAssignApiClientFromConsentCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Consent", "validating UnAssignApiClientFromConsentCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Consent", "validating identity on UnAssignApiClientFromConsentCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}


}
