/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>CreditorValidation</h2>
 * <p>
 * The Creditor Validation  handles state validation of a Creditor include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateCreditorCommand</li>
 *      <li>UpdateCreditorCommand</li>
 *      <li>DeleteCreditorCommand</li>
 *set( false = false )
   *       <li>AssignMandatesToCreditorCommand</li>
 *       <li>RemoveMandatesFromCreditorCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class CreditorValidator {

	/**
	 * default constructor
	 */
	protected CreditorValidator() {
	}


	/**
	 * handles creation validation for a Creditor
	 */
	public void validate( CreateCreditorCommand creditor )throws ValidationException {
		if ( creditor == null )
			throw new ValidationException( "Creditor", "validating CreateCreditorCommand" );
		if ( creditor.getName() == null )
			throw new ValidationException( "Creditor", "validating access on getName" );
		if ( creditor.getBic() == null )
			throw new ValidationException( "Creditor", "validating access on getBic" );
		if ( creditor.getAddress() == null )
			throw new ValidationException( "Creditor", "validating access on getAddress" );
	}

	/**
	 * handles update validation for a Creditor
	 */
	public void validate( UpdateCreditorCommand creditor ) throws ValidationException {
		if ( creditor == null )
			throw new ValidationException( "Creditor", "validating UpdateCreditorCommand" );
		if ( creditor.getName() == null )
			throw new ValidationException( "Creditor", "validating method getName" );
		if ( creditor.getBic() == null )
			throw new ValidationException( "Creditor", "validating method getBic" );
		if ( creditor.getAddress() == null )
			throw new ValidationException( "Creditor", "validating method getAddress" );
	}

/**
 * handles delete validation for a Creditor
 */
	public void validate( DeleteCreditorCommand creditor ) throws ValidationException {
		if ( creditor == null )
			throw new ValidationException( "Creditor", "validating DeleteCreditorCommand" );

		if ( creditor.getId() == null )
			throw new ValidationException( "Creditor", "validating DeleteCreditorCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Creditor
 */
	public void validate( CreditorFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Creditor", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Creditor", "validating FetchOneSummary identifier discovered as null" );
	}


	/**
	 * handles add to Mandates validation for a Creditor
	 *
	 * @param	command AssignMandatesToCreditorCommand
	 */
	public void validate( AssignMandatesToCreditorCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Creditor", "validating AssignMandatesToCreditorCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Creditor", "validating identity on AssignMandatesToCreditorCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Mandates validation for a Creditor
	 *
	 * @param	command RemoveMandatesFromCreditorCommand
	 */
	public void validate( RemoveMandatesFromCreditorCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Creditor", "validating RemoveMandatesFromCreditorCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Creditor", "validating identity on RemoveMandatesFromCreditorCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
