/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>CustomerValidation</h2>
 * <p>
 * The Customer Validation  handles state validation of a Customer include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateCustomerCommand</li>
 *      <li>UpdateCustomerCommand</li>
 *      <li>DeleteCustomerCommand</li>
 *set( false = false )
  *       <li>AssignInstitutionToCustomerCommand</li>
 *       <li>UnAssignInstitutionFromCustomerCommand</li>
   *       <li>AssignAccountsToCustomerCommand</li>
 *       <li>RemoveAccountsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignWalletsToCustomerCommand</li>
 *       <li>RemoveWalletsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignCardsToCustomerCommand</li>
 *       <li>RemoveCardsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignKycProfilesToCustomerCommand</li>
 *       <li>RemoveKycProfilesFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignConsentsToCustomerCommand</li>
 *       <li>RemoveConsentsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignAgreementsToCustomerCommand</li>
 *       <li>RemoveAgreementsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignLoanApplicationsToCustomerCommand</li>
 *       <li>RemoveLoanApplicationsFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignLoansToCustomerCommand</li>
 *       <li>RemoveLoansFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignPortfoliosToCustomerCommand</li>
 *       <li>RemovePortfoliosFromCustomerCommand</li>
 *   </ul>
 *
  *       <li>AssignDisputesToCustomerCommand</li>
 *       <li>RemoveDisputesFromCustomerCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class CustomerValidator {

	/**
	 * default constructor
	 */
	protected CustomerValidator() {
	}


	/**
	 * handles creation validation for a Customer
	 */
	public void validate( CreateCustomerCommand customer )throws ValidationException {
		if ( customer == null )
			throw new ValidationException( "Customer", "validating CreateCustomerCommand" );
		if ( customer.getFirstName() == null )
			throw new ValidationException( "Customer", "validating access on getFirstName" );
		if ( customer.getLastName() == null )
			throw new ValidationException( "Customer", "validating access on getLastName" );
		if ( customer.getDateOfBirth() == null )
			throw new ValidationException( "Customer", "validating access on getDateOfBirth" );
		if ( customer.getEmail() == null )
			throw new ValidationException( "Customer", "validating access on getEmail" );
		if ( customer.getPhone() == null )
			throw new ValidationException( "Customer", "validating access on getPhone" );
		if ( customer.getAddress() == null )
			throw new ValidationException( "Customer", "validating access on getAddress" );
		if ( customer.getTaxId() == null )
			throw new ValidationException( "Customer", "validating access on getTaxId" );
		if ( customer.getRiskScore() == null )
			throw new ValidationException( "Customer", "validating access on getRiskScore" );
	}

	/**
	 * handles update validation for a Customer
	 */
	public void validate( UpdateCustomerCommand customer ) throws ValidationException {
		if ( customer == null )
			throw new ValidationException( "Customer", "validating UpdateCustomerCommand" );
		if ( customer.getFirstName() == null )
			throw new ValidationException( "Customer", "validating method getFirstName" );
		if ( customer.getLastName() == null )
			throw new ValidationException( "Customer", "validating method getLastName" );
		if ( customer.getDateOfBirth() == null )
			throw new ValidationException( "Customer", "validating method getDateOfBirth" );
		if ( customer.getEmail() == null )
			throw new ValidationException( "Customer", "validating method getEmail" );
		if ( customer.getPhone() == null )
			throw new ValidationException( "Customer", "validating method getPhone" );
		if ( customer.getAddress() == null )
			throw new ValidationException( "Customer", "validating method getAddress" );
		if ( customer.getTaxId() == null )
			throw new ValidationException( "Customer", "validating method getTaxId" );
		if ( customer.getRiskScore() == null )
			throw new ValidationException( "Customer", "validating method getRiskScore" );
	}

/**
 * handles delete validation for a Customer
 */
	public void validate( DeleteCustomerCommand customer ) throws ValidationException {
		if ( customer == null )
			throw new ValidationException( "Customer", "validating DeleteCustomerCommand" );

		if ( customer.getId() == null )
			throw new ValidationException( "Customer", "validating DeleteCustomerCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Customer
 */
	public void validate( CustomerFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Customer", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Customer", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Institution validation for a Customer
	 *
	 * @param	command AssignInstitutionToCustomerCommand
	 */
	public void validate( AssignInstitutionToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignInstitutionToCustomerCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Customer", "validating identity on AssignInstitutionToCustomerCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Institution validation for a Customer
	 *
	 * @param	command UnAssignInstitutionFromCustomerCommand
	 */
	public void validate( UnAssignInstitutionFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating UnAssignInstitutionFromCustomerCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Customer", "validating identity on UnAssignInstitutionFromCustomerCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Accounts validation for a Customer
	 *
	 * @param	command AssignAccountsToCustomerCommand
	 */
	public void validate( AssignAccountsToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignAccountsToCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on AssignAccountsToCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Accounts validation for a Customer
	 *
	 * @param	command RemoveAccountsFromCustomerCommand
	 */
	public void validate( RemoveAccountsFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveAccountsFromCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on RemoveAccountsFromCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Wallets validation for a Customer
	 *
	 * @param	command AssignWalletsToCustomerCommand
	 */
	public void validate( AssignWalletsToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignWalletsToCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on AssignWalletsToCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Wallets validation for a Customer
	 *
	 * @param	command RemoveWalletsFromCustomerCommand
	 */
	public void validate( RemoveWalletsFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveWalletsFromCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on RemoveWalletsFromCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Cards validation for a Customer
	 *
	 * @param	command AssignCardsToCustomerCommand
	 */
	public void validate( AssignCardsToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignCardsToCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on AssignCardsToCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Cards validation for a Customer
	 *
	 * @param	command RemoveCardsFromCustomerCommand
	 */
	public void validate( RemoveCardsFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveCardsFromCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on RemoveCardsFromCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to KycProfiles validation for a Customer
	 *
	 * @param	command AssignKycProfilesToCustomerCommand
	 */
	public void validate( AssignKycProfilesToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignKycProfilesToCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on AssignKycProfilesToCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from KycProfiles validation for a Customer
	 *
	 * @param	command RemoveKycProfilesFromCustomerCommand
	 */
	public void validate( RemoveKycProfilesFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveKycProfilesFromCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on RemoveKycProfilesFromCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Consents validation for a Customer
	 *
	 * @param	command AssignConsentsToCustomerCommand
	 */
	public void validate( AssignConsentsToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignConsentsToCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on AssignConsentsToCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Consents validation for a Customer
	 *
	 * @param	command RemoveConsentsFromCustomerCommand
	 */
	public void validate( RemoveConsentsFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveConsentsFromCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on RemoveConsentsFromCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Agreements validation for a Customer
	 *
	 * @param	command AssignAgreementsToCustomerCommand
	 */
	public void validate( AssignAgreementsToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignAgreementsToCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on AssignAgreementsToCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Agreements validation for a Customer
	 *
	 * @param	command RemoveAgreementsFromCustomerCommand
	 */
	public void validate( RemoveAgreementsFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveAgreementsFromCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on RemoveAgreementsFromCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to LoanApplications validation for a Customer
	 *
	 * @param	command AssignLoanApplicationsToCustomerCommand
	 */
	public void validate( AssignLoanApplicationsToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignLoanApplicationsToCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on AssignLoanApplicationsToCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from LoanApplications validation for a Customer
	 *
	 * @param	command RemoveLoanApplicationsFromCustomerCommand
	 */
	public void validate( RemoveLoanApplicationsFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveLoanApplicationsFromCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on RemoveLoanApplicationsFromCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Loans validation for a Customer
	 *
	 * @param	command AssignLoansToCustomerCommand
	 */
	public void validate( AssignLoansToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignLoansToCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on AssignLoansToCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Loans validation for a Customer
	 *
	 * @param	command RemoveLoansFromCustomerCommand
	 */
	public void validate( RemoveLoansFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveLoansFromCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on RemoveLoansFromCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Portfolios validation for a Customer
	 *
	 * @param	command AssignPortfoliosToCustomerCommand
	 */
	public void validate( AssignPortfoliosToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignPortfoliosToCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on AssignPortfoliosToCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Portfolios validation for a Customer
	 *
	 * @param	command RemovePortfoliosFromCustomerCommand
	 */
	public void validate( RemovePortfoliosFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemovePortfoliosFromCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on RemovePortfoliosFromCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Disputes validation for a Customer
	 *
	 * @param	command AssignDisputesToCustomerCommand
	 */
	public void validate( AssignDisputesToCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Customer", "validating AssignDisputesToCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on AssignDisputesToCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Disputes validation for a Customer
	 *
	 * @param	command RemoveDisputesFromCustomerCommand
	 */
	public void validate( RemoveDisputesFromCustomerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Customer", "validating RemoveDisputesFromCustomerCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Customer", "validating identity on RemoveDisputesFromCustomerCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
