/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>DisputeValidation</h2>
 * <p>
 * The Dispute Validation  handles state validation of a Dispute include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateDisputeCommand</li>
 *      <li>UpdateDisputeCommand</li>
 *      <li>DeleteDisputeCommand</li>
 *set( false = false )
  *       <li>AssignTransactionToDisputeCommand</li>
 *       <li>UnAssignTransactionFromDisputeCommand</li>
  *       <li>AssignCardToDisputeCommand</li>
 *       <li>UnAssignCardFromDisputeCommand</li>
  *       <li>AssignMerchantToDisputeCommand</li>
 *       <li>UnAssignMerchantFromDisputeCommand</li>
   *       <li>AssignChargebacksToDisputeCommand</li>
 *       <li>RemoveChargebacksFromDisputeCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class DisputeValidator {

	/**
	 * default constructor
	 */
	protected DisputeValidator() {
	}


	/**
	 * handles creation validation for a Dispute
	 */
	public void validate( CreateDisputeCommand dispute )throws ValidationException {
		if ( dispute == null )
			throw new ValidationException( "Dispute", "validating CreateDisputeCommand" );
		if ( dispute.getDisputeReference() == null )
			throw new ValidationException( "Dispute", "validating access on getDisputeReference" );
		if ( dispute.getOpenedAt() == null )
			throw new ValidationException( "Dispute", "validating access on getOpenedAt" );
		if ( dispute.getClosedAt() == null )
			throw new ValidationException( "Dispute", "validating access on getClosedAt" );
	}

	/**
	 * handles update validation for a Dispute
	 */
	public void validate( UpdateDisputeCommand dispute ) throws ValidationException {
		if ( dispute == null )
			throw new ValidationException( "Dispute", "validating UpdateDisputeCommand" );
		if ( dispute.getDisputeReference() == null )
			throw new ValidationException( "Dispute", "validating method getDisputeReference" );
		if ( dispute.getOpenedAt() == null )
			throw new ValidationException( "Dispute", "validating method getOpenedAt" );
		if ( dispute.getClosedAt() == null )
			throw new ValidationException( "Dispute", "validating method getClosedAt" );
	}

/**
 * handles delete validation for a Dispute
 */
	public void validate( DeleteDisputeCommand dispute ) throws ValidationException {
		if ( dispute == null )
			throw new ValidationException( "Dispute", "validating DeleteDisputeCommand" );

		if ( dispute.getId() == null )
			throw new ValidationException( "Dispute", "validating DeleteDisputeCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Dispute
 */
	public void validate( DisputeFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Dispute", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Dispute", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Transaction validation for a Dispute
	 *
	 * @param	command AssignTransactionToDisputeCommand
	 */
	public void validate( AssignTransactionToDisputeCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Dispute", "validating AssignTransactionToDisputeCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Dispute", "validating identity on AssignTransactionToDisputeCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Transaction validation for a Dispute
	 *
	 * @param	command UnAssignTransactionFromDisputeCommand
	 */
	public void validate( UnAssignTransactionFromDisputeCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Dispute", "validating UnAssignTransactionFromDisputeCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Dispute", "validating identity on UnAssignTransactionFromDisputeCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Card validation for a Dispute
	 *
	 * @param	command AssignCardToDisputeCommand
	 */
	public void validate( AssignCardToDisputeCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Dispute", "validating AssignCardToDisputeCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Dispute", "validating identity on AssignCardToDisputeCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Card validation for a Dispute
	 *
	 * @param	command UnAssignCardFromDisputeCommand
	 */
	public void validate( UnAssignCardFromDisputeCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Dispute", "validating UnAssignCardFromDisputeCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Dispute", "validating identity on UnAssignCardFromDisputeCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Merchant validation for a Dispute
	 *
	 * @param	command AssignMerchantToDisputeCommand
	 */
	public void validate( AssignMerchantToDisputeCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Dispute", "validating AssignMerchantToDisputeCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Dispute", "validating identity on AssignMerchantToDisputeCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Merchant validation for a Dispute
	 *
	 * @param	command UnAssignMerchantFromDisputeCommand
	 */
	public void validate( UnAssignMerchantFromDisputeCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Dispute", "validating UnAssignMerchantFromDisputeCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Dispute", "validating identity on UnAssignMerchantFromDisputeCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Chargebacks validation for a Dispute
	 *
	 * @param	command AssignChargebacksToDisputeCommand
	 */
	public void validate( AssignChargebacksToDisputeCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Dispute", "validating AssignChargebacksToDisputeCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Dispute", "validating identity on AssignChargebacksToDisputeCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Chargebacks validation for a Dispute
	 *
	 * @param	command RemoveChargebacksFromDisputeCommand
	 */
	public void validate( RemoveChargebacksFromDisputeCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Dispute", "validating RemoveChargebacksFromDisputeCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Dispute", "validating identity on RemoveChargebacksFromDisputeCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
