/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>ExchangeRateValidation</h2>
 * <p>
 * The ExchangeRate Validation  handles state validation of a ExchangeRate include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateExchangeRateCommand</li>
 *      <li>UpdateExchangeRateCommand</li>
 *      <li>DeleteExchangeRateCommand</li>
 *set( false = false )
   *       <li>AssignUsedByQuotesToExchangeRateCommand</li>
 *       <li>RemoveUsedByQuotesFromExchangeRateCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class ExchangeRateValidator {

	/**
	 * default constructor
	 */
	protected ExchangeRateValidator() {
	}


	/**
	 * handles creation validation for a ExchangeRate
	 */
	public void validate( CreateExchangeRateCommand exchangeRate )throws ValidationException {
		if ( exchangeRate == null )
			throw new ValidationException( "ExchangeRate", "validating CreateExchangeRateCommand" );
		if ( exchangeRate.getBaseCurrency() == null )
			throw new ValidationException( "ExchangeRate", "validating access on getBaseCurrency" );
		if ( exchangeRate.getQuoteCurrency() == null )
			throw new ValidationException( "ExchangeRate", "validating access on getQuoteCurrency" );
		if ( exchangeRate.getRate() == null )
			throw new ValidationException( "ExchangeRate", "validating access on getRate" );
		if ( exchangeRate.getAsOf() == null )
			throw new ValidationException( "ExchangeRate", "validating access on getAsOf" );
		if ( exchangeRate.getSource() == null )
			throw new ValidationException( "ExchangeRate", "validating access on getSource" );
	}

	/**
	 * handles update validation for a ExchangeRate
	 */
	public void validate( UpdateExchangeRateCommand exchangeRate ) throws ValidationException {
		if ( exchangeRate == null )
			throw new ValidationException( "ExchangeRate", "validating UpdateExchangeRateCommand" );
		if ( exchangeRate.getBaseCurrency() == null )
			throw new ValidationException( "ExchangeRate", "validating method getBaseCurrency" );
		if ( exchangeRate.getQuoteCurrency() == null )
			throw new ValidationException( "ExchangeRate", "validating method getQuoteCurrency" );
		if ( exchangeRate.getRate() == null )
			throw new ValidationException( "ExchangeRate", "validating method getRate" );
		if ( exchangeRate.getAsOf() == null )
			throw new ValidationException( "ExchangeRate", "validating method getAsOf" );
		if ( exchangeRate.getSource() == null )
			throw new ValidationException( "ExchangeRate", "validating method getSource" );
	}

/**
 * handles delete validation for a ExchangeRate
 */
	public void validate( DeleteExchangeRateCommand exchangeRate ) throws ValidationException {
		if ( exchangeRate == null )
			throw new ValidationException( "ExchangeRate", "validating DeleteExchangeRateCommand" );

		if ( exchangeRate.getId() == null )
			throw new ValidationException( "ExchangeRate", "validating DeleteExchangeRateCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a ExchangeRate
 */
	public void validate( ExchangeRateFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "ExchangeRate", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "ExchangeRate", "validating FetchOneSummary identifier discovered as null" );
	}


	/**
	 * handles add to UsedByQuotes validation for a ExchangeRate
	 *
	 * @param	command AssignUsedByQuotesToExchangeRateCommand
	 */
	public void validate( AssignUsedByQuotesToExchangeRateCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "ExchangeRate", "validating AssignUsedByQuotesToExchangeRateCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "ExchangeRate", "validating identity on AssignUsedByQuotesToExchangeRateCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from UsedByQuotes validation for a ExchangeRate
	 *
	 * @param	command RemoveUsedByQuotesFromExchangeRateCommand
	 */
	public void validate( RemoveUsedByQuotesFromExchangeRateCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("ExchangeRate", "validating RemoveUsedByQuotesFromExchangeRateCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "ExchangeRate", "validating identity on RemoveUsedByQuotesFromExchangeRateCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
