/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>FinancialInstitutionValidation</h2>
 * <p>
 * The FinancialInstitution Validation  handles state validation of a FinancialInstitution include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateFinancialInstitutionCommand</li>
 *      <li>UpdateFinancialInstitutionCommand</li>
 *      <li>DeleteFinancialInstitutionCommand</li>
 *set( false = false )
   *       <li>AssignBranchesToFinancialInstitutionCommand</li>
 *       <li>RemoveBranchesFromFinancialInstitutionCommand</li>
 *   </ul>
 *
  *       <li>AssignCustomersToFinancialInstitutionCommand</li>
 *       <li>RemoveCustomersFromFinancialInstitutionCommand</li>
 *   </ul>
 *
  *       <li>AssignProductOfferingsToFinancialInstitutionCommand</li>
 *       <li>RemoveProductOfferingsFromFinancialInstitutionCommand</li>
 *   </ul>
 *
  *       <li>AssignPaymentProcessorsToFinancialInstitutionCommand</li>
 *       <li>RemovePaymentProcessorsFromFinancialInstitutionCommand</li>
 *   </ul>
 *
  *       <li>AssignCompliancePoliciesToFinancialInstitutionCommand</li>
 *       <li>RemoveCompliancePoliciesFromFinancialInstitutionCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class FinancialInstitutionValidator {

	/**
	 * default constructor
	 */
	protected FinancialInstitutionValidator() {
	}


	/**
	 * handles creation validation for a FinancialInstitution
	 */
	public void validate( CreateFinancialInstitutionCommand financialInstitution )throws ValidationException {
		if ( financialInstitution == null )
			throw new ValidationException( "FinancialInstitution", "validating CreateFinancialInstitutionCommand" );
		if ( financialInstitution.getName() == null )
			throw new ValidationException( "FinancialInstitution", "validating access on getName" );
		if ( financialInstitution.getLegalName() == null )
			throw new ValidationException( "FinancialInstitution", "validating access on getLegalName" );
		if ( financialInstitution.getCountryOfIncorporation() == null )
			throw new ValidationException( "FinancialInstitution", "validating access on getCountryOfIncorporation" );
		if ( financialInstitution.getBic() == null )
			throw new ValidationException( "FinancialInstitution", "validating access on getBic" );
		if ( financialInstitution.getWebsite() == null )
			throw new ValidationException( "FinancialInstitution", "validating access on getWebsite" );
	}

	/**
	 * handles update validation for a FinancialInstitution
	 */
	public void validate( UpdateFinancialInstitutionCommand financialInstitution ) throws ValidationException {
		if ( financialInstitution == null )
			throw new ValidationException( "FinancialInstitution", "validating UpdateFinancialInstitutionCommand" );
		if ( financialInstitution.getName() == null )
			throw new ValidationException( "FinancialInstitution", "validating method getName" );
		if ( financialInstitution.getLegalName() == null )
			throw new ValidationException( "FinancialInstitution", "validating method getLegalName" );
		if ( financialInstitution.getCountryOfIncorporation() == null )
			throw new ValidationException( "FinancialInstitution", "validating method getCountryOfIncorporation" );
		if ( financialInstitution.getBic() == null )
			throw new ValidationException( "FinancialInstitution", "validating method getBic" );
		if ( financialInstitution.getWebsite() == null )
			throw new ValidationException( "FinancialInstitution", "validating method getWebsite" );
	}

/**
 * handles delete validation for a FinancialInstitution
 */
	public void validate( DeleteFinancialInstitutionCommand financialInstitution ) throws ValidationException {
		if ( financialInstitution == null )
			throw new ValidationException( "FinancialInstitution", "validating DeleteFinancialInstitutionCommand" );

		if ( financialInstitution.getId() == null )
			throw new ValidationException( "FinancialInstitution", "validating DeleteFinancialInstitutionCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a FinancialInstitution
 */
	public void validate( FinancialInstitutionFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "FinancialInstitution", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "FinancialInstitution", "validating FetchOneSummary identifier discovered as null" );
	}


	/**
	 * handles add to Branches validation for a FinancialInstitution
	 *
	 * @param	command AssignBranchesToFinancialInstitutionCommand
	 */
	public void validate( AssignBranchesToFinancialInstitutionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FinancialInstitution", "validating AssignBranchesToFinancialInstitutionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "FinancialInstitution", "validating identity on AssignBranchesToFinancialInstitutionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Branches validation for a FinancialInstitution
	 *
	 * @param	command RemoveBranchesFromFinancialInstitutionCommand
	 */
	public void validate( RemoveBranchesFromFinancialInstitutionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("FinancialInstitution", "validating RemoveBranchesFromFinancialInstitutionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "FinancialInstitution", "validating identity on RemoveBranchesFromFinancialInstitutionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Customers validation for a FinancialInstitution
	 *
	 * @param	command AssignCustomersToFinancialInstitutionCommand
	 */
	public void validate( AssignCustomersToFinancialInstitutionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FinancialInstitution", "validating AssignCustomersToFinancialInstitutionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "FinancialInstitution", "validating identity on AssignCustomersToFinancialInstitutionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Customers validation for a FinancialInstitution
	 *
	 * @param	command RemoveCustomersFromFinancialInstitutionCommand
	 */
	public void validate( RemoveCustomersFromFinancialInstitutionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("FinancialInstitution", "validating RemoveCustomersFromFinancialInstitutionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "FinancialInstitution", "validating identity on RemoveCustomersFromFinancialInstitutionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to ProductOfferings validation for a FinancialInstitution
	 *
	 * @param	command AssignProductOfferingsToFinancialInstitutionCommand
	 */
	public void validate( AssignProductOfferingsToFinancialInstitutionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FinancialInstitution", "validating AssignProductOfferingsToFinancialInstitutionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "FinancialInstitution", "validating identity on AssignProductOfferingsToFinancialInstitutionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from ProductOfferings validation for a FinancialInstitution
	 *
	 * @param	command RemoveProductOfferingsFromFinancialInstitutionCommand
	 */
	public void validate( RemoveProductOfferingsFromFinancialInstitutionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("FinancialInstitution", "validating RemoveProductOfferingsFromFinancialInstitutionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "FinancialInstitution", "validating identity on RemoveProductOfferingsFromFinancialInstitutionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to PaymentProcessors validation for a FinancialInstitution
	 *
	 * @param	command AssignPaymentProcessorsToFinancialInstitutionCommand
	 */
	public void validate( AssignPaymentProcessorsToFinancialInstitutionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FinancialInstitution", "validating AssignPaymentProcessorsToFinancialInstitutionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "FinancialInstitution", "validating identity on AssignPaymentProcessorsToFinancialInstitutionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from PaymentProcessors validation for a FinancialInstitution
	 *
	 * @param	command RemovePaymentProcessorsFromFinancialInstitutionCommand
	 */
	public void validate( RemovePaymentProcessorsFromFinancialInstitutionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("FinancialInstitution", "validating RemovePaymentProcessorsFromFinancialInstitutionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "FinancialInstitution", "validating identity on RemovePaymentProcessorsFromFinancialInstitutionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to CompliancePolicies validation for a FinancialInstitution
	 *
	 * @param	command AssignCompliancePoliciesToFinancialInstitutionCommand
	 */
	public void validate( AssignCompliancePoliciesToFinancialInstitutionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "FinancialInstitution", "validating AssignCompliancePoliciesToFinancialInstitutionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "FinancialInstitution", "validating identity on AssignCompliancePoliciesToFinancialInstitutionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from CompliancePolicies validation for a FinancialInstitution
	 *
	 * @param	command RemoveCompliancePoliciesFromFinancialInstitutionCommand
	 */
	public void validate( RemoveCompliancePoliciesFromFinancialInstitutionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("FinancialInstitution", "validating RemoveCompliancePoliciesFromFinancialInstitutionCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "FinancialInstitution", "validating identity on RemoveCompliancePoliciesFromFinancialInstitutionCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
