/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>InvestmentPortfolioValidation</h2>
 * <p>
 * The InvestmentPortfolio Validation  handles state validation of a InvestmentPortfolio include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateInvestmentPortfolioCommand</li>
 *      <li>UpdateInvestmentPortfolioCommand</li>
 *      <li>DeleteInvestmentPortfolioCommand</li>
 *set( false = false )
  *       <li>AssignCustomerToInvestmentPortfolioCommand</li>
 *       <li>UnAssignCustomerFromInvestmentPortfolioCommand</li>
   *       <li>AssignAccountsToInvestmentPortfolioCommand</li>
 *       <li>RemoveAccountsFromInvestmentPortfolioCommand</li>
 *   </ul>
 *
  *       <li>AssignOrdersToInvestmentPortfolioCommand</li>
 *       <li>RemoveOrdersFromInvestmentPortfolioCommand</li>
 *   </ul>
 *
  *       <li>AssignHoldingsToInvestmentPortfolioCommand</li>
 *       <li>RemoveHoldingsFromInvestmentPortfolioCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class InvestmentPortfolioValidator {

	/**
	 * default constructor
	 */
	protected InvestmentPortfolioValidator() {
	}


	/**
	 * handles creation validation for a InvestmentPortfolio
	 */
	public void validate( CreateInvestmentPortfolioCommand investmentPortfolio )throws ValidationException {
		if ( investmentPortfolio == null )
			throw new ValidationException( "InvestmentPortfolio", "validating CreateInvestmentPortfolioCommand" );
		if ( investmentPortfolio.getPortfolioCode() == null )
			throw new ValidationException( "InvestmentPortfolio", "validating access on getPortfolioCode" );
		if ( investmentPortfolio.getBaseCurrency() == null )
			throw new ValidationException( "InvestmentPortfolio", "validating access on getBaseCurrency" );
		if ( investmentPortfolio.getCreatedAt() == null )
			throw new ValidationException( "InvestmentPortfolio", "validating access on getCreatedAt" );
	}

	/**
	 * handles update validation for a InvestmentPortfolio
	 */
	public void validate( UpdateInvestmentPortfolioCommand investmentPortfolio ) throws ValidationException {
		if ( investmentPortfolio == null )
			throw new ValidationException( "InvestmentPortfolio", "validating UpdateInvestmentPortfolioCommand" );
		if ( investmentPortfolio.getPortfolioCode() == null )
			throw new ValidationException( "InvestmentPortfolio", "validating method getPortfolioCode" );
		if ( investmentPortfolio.getBaseCurrency() == null )
			throw new ValidationException( "InvestmentPortfolio", "validating method getBaseCurrency" );
		if ( investmentPortfolio.getCreatedAt() == null )
			throw new ValidationException( "InvestmentPortfolio", "validating method getCreatedAt" );
	}

/**
 * handles delete validation for a InvestmentPortfolio
 */
	public void validate( DeleteInvestmentPortfolioCommand investmentPortfolio ) throws ValidationException {
		if ( investmentPortfolio == null )
			throw new ValidationException( "InvestmentPortfolio", "validating DeleteInvestmentPortfolioCommand" );

		if ( investmentPortfolio.getId() == null )
			throw new ValidationException( "InvestmentPortfolio", "validating DeleteInvestmentPortfolioCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a InvestmentPortfolio
 */
	public void validate( InvestmentPortfolioFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "InvestmentPortfolio", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "InvestmentPortfolio", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Customer validation for a InvestmentPortfolio
	 *
	 * @param	command AssignCustomerToInvestmentPortfolioCommand
	 */
	public void validate( AssignCustomerToInvestmentPortfolioCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "InvestmentPortfolio", "validating AssignCustomerToInvestmentPortfolioCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "InvestmentPortfolio", "validating identity on AssignCustomerToInvestmentPortfolioCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Customer validation for a InvestmentPortfolio
	 *
	 * @param	command UnAssignCustomerFromInvestmentPortfolioCommand
	 */
	public void validate( UnAssignCustomerFromInvestmentPortfolioCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "InvestmentPortfolio", "validating UnAssignCustomerFromInvestmentPortfolioCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "InvestmentPortfolio", "validating identity on UnAssignCustomerFromInvestmentPortfolioCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Accounts validation for a InvestmentPortfolio
	 *
	 * @param	command AssignAccountsToInvestmentPortfolioCommand
	 */
	public void validate( AssignAccountsToInvestmentPortfolioCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "InvestmentPortfolio", "validating AssignAccountsToInvestmentPortfolioCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "InvestmentPortfolio", "validating identity on AssignAccountsToInvestmentPortfolioCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Accounts validation for a InvestmentPortfolio
	 *
	 * @param	command RemoveAccountsFromInvestmentPortfolioCommand
	 */
	public void validate( RemoveAccountsFromInvestmentPortfolioCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("InvestmentPortfolio", "validating RemoveAccountsFromInvestmentPortfolioCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "InvestmentPortfolio", "validating identity on RemoveAccountsFromInvestmentPortfolioCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Orders validation for a InvestmentPortfolio
	 *
	 * @param	command AssignOrdersToInvestmentPortfolioCommand
	 */
	public void validate( AssignOrdersToInvestmentPortfolioCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "InvestmentPortfolio", "validating AssignOrdersToInvestmentPortfolioCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "InvestmentPortfolio", "validating identity on AssignOrdersToInvestmentPortfolioCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Orders validation for a InvestmentPortfolio
	 *
	 * @param	command RemoveOrdersFromInvestmentPortfolioCommand
	 */
	public void validate( RemoveOrdersFromInvestmentPortfolioCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("InvestmentPortfolio", "validating RemoveOrdersFromInvestmentPortfolioCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "InvestmentPortfolio", "validating identity on RemoveOrdersFromInvestmentPortfolioCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Holdings validation for a InvestmentPortfolio
	 *
	 * @param	command AssignHoldingsToInvestmentPortfolioCommand
	 */
	public void validate( AssignHoldingsToInvestmentPortfolioCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "InvestmentPortfolio", "validating AssignHoldingsToInvestmentPortfolioCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "InvestmentPortfolio", "validating identity on AssignHoldingsToInvestmentPortfolioCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Holdings validation for a InvestmentPortfolio
	 *
	 * @param	command RemoveHoldingsFromInvestmentPortfolioCommand
	 */
	public void validate( RemoveHoldingsFromInvestmentPortfolioCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("InvestmentPortfolio", "validating RemoveHoldingsFromInvestmentPortfolioCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "InvestmentPortfolio", "validating identity on RemoveHoldingsFromInvestmentPortfolioCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
