/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>InvestmentAccountValidation</h2>
 * <p>
 * The InvestmentAccount Validation  handles state validation of a InvestmentAccount include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateInvestmentAccountCommand</li>
 *      <li>UpdateInvestmentAccountCommand</li>
 *      <li>DeleteInvestmentAccountCommand</li>
 *set( false = false )
  *       <li>AssignPortfolioToInvestmentAccountCommand</li>
 *       <li>UnAssignPortfolioFromInvestmentAccountCommand</li>
   *       <li>AssignTradesToInvestmentAccountCommand</li>
 *       <li>RemoveTradesFromInvestmentAccountCommand</li>
 *   </ul>
 *
  *       <li>AssignOrdersToInvestmentAccountCommand</li>
 *       <li>RemoveOrdersFromInvestmentAccountCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class InvestmentAccountValidator {

	/**
	 * default constructor
	 */
	protected InvestmentAccountValidator() {
	}


	/**
	 * handles creation validation for a InvestmentAccount
	 */
	public void validate( CreateInvestmentAccountCommand investmentAccount )throws ValidationException {
		if ( investmentAccount == null )
			throw new ValidationException( "InvestmentAccount", "validating CreateInvestmentAccountCommand" );
		if ( investmentAccount.getAccountNumber() == null )
			throw new ValidationException( "InvestmentAccount", "validating access on getAccountNumber" );
		if ( investmentAccount.getBaseCurrency() == null )
			throw new ValidationException( "InvestmentAccount", "validating access on getBaseCurrency" );
		if ( investmentAccount.getBalance() == null )
			throw new ValidationException( "InvestmentAccount", "validating access on getBalance" );
	}

	/**
	 * handles update validation for a InvestmentAccount
	 */
	public void validate( UpdateInvestmentAccountCommand investmentAccount ) throws ValidationException {
		if ( investmentAccount == null )
			throw new ValidationException( "InvestmentAccount", "validating UpdateInvestmentAccountCommand" );
		if ( investmentAccount.getAccountNumber() == null )
			throw new ValidationException( "InvestmentAccount", "validating method getAccountNumber" );
		if ( investmentAccount.getBaseCurrency() == null )
			throw new ValidationException( "InvestmentAccount", "validating method getBaseCurrency" );
		if ( investmentAccount.getBalance() == null )
			throw new ValidationException( "InvestmentAccount", "validating method getBalance" );
	}

/**
 * handles delete validation for a InvestmentAccount
 */
	public void validate( DeleteInvestmentAccountCommand investmentAccount ) throws ValidationException {
		if ( investmentAccount == null )
			throw new ValidationException( "InvestmentAccount", "validating DeleteInvestmentAccountCommand" );

		if ( investmentAccount.getId() == null )
			throw new ValidationException( "InvestmentAccount", "validating DeleteInvestmentAccountCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a InvestmentAccount
 */
	public void validate( InvestmentAccountFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "InvestmentAccount", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "InvestmentAccount", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Portfolio validation for a InvestmentAccount
	 *
	 * @param	command AssignPortfolioToInvestmentAccountCommand
	 */
	public void validate( AssignPortfolioToInvestmentAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "InvestmentAccount", "validating AssignPortfolioToInvestmentAccountCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "InvestmentAccount", "validating identity on AssignPortfolioToInvestmentAccountCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Portfolio validation for a InvestmentAccount
	 *
	 * @param	command UnAssignPortfolioFromInvestmentAccountCommand
	 */
	public void validate( UnAssignPortfolioFromInvestmentAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "InvestmentAccount", "validating UnAssignPortfolioFromInvestmentAccountCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "InvestmentAccount", "validating identity on UnAssignPortfolioFromInvestmentAccountCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Trades validation for a InvestmentAccount
	 *
	 * @param	command AssignTradesToInvestmentAccountCommand
	 */
	public void validate( AssignTradesToInvestmentAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "InvestmentAccount", "validating AssignTradesToInvestmentAccountCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "InvestmentAccount", "validating identity on AssignTradesToInvestmentAccountCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Trades validation for a InvestmentAccount
	 *
	 * @param	command RemoveTradesFromInvestmentAccountCommand
	 */
	public void validate( RemoveTradesFromInvestmentAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("InvestmentAccount", "validating RemoveTradesFromInvestmentAccountCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "InvestmentAccount", "validating identity on RemoveTradesFromInvestmentAccountCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Orders validation for a InvestmentAccount
	 *
	 * @param	command AssignOrdersToInvestmentAccountCommand
	 */
	public void validate( AssignOrdersToInvestmentAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "InvestmentAccount", "validating AssignOrdersToInvestmentAccountCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "InvestmentAccount", "validating identity on AssignOrdersToInvestmentAccountCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Orders validation for a InvestmentAccount
	 *
	 * @param	command RemoveOrdersFromInvestmentAccountCommand
	 */
	public void validate( RemoveOrdersFromInvestmentAccountCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("InvestmentAccount", "validating RemoveOrdersFromInvestmentAccountCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "InvestmentAccount", "validating identity on RemoveOrdersFromInvestmentAccountCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
