/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>KYCProfileValidation</h2>
 * <p>
 * The KYCProfile Validation  handles state validation of a KYCProfile include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateKYCProfileCommand</li>
 *      <li>UpdateKYCProfileCommand</li>
 *      <li>DeleteKYCProfileCommand</li>
 *set( false = false )
  *       <li>AssignCustomerToKYCProfileCommand</li>
 *       <li>UnAssignCustomerFromKYCProfileCommand</li>
   *       <li>AssignDocumentsToKYCProfileCommand</li>
 *       <li>RemoveDocumentsFromKYCProfileCommand</li>
 *   </ul>
 *
  *       <li>AssignScreeningsToKYCProfileCommand</li>
 *       <li>RemoveScreeningsFromKYCProfileCommand</li>
 *   </ul>
 *
  *       <li>AssignAddressesToKYCProfileCommand</li>
 *       <li>RemoveAddressesFromKYCProfileCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class KYCProfileValidator {

	/**
	 * default constructor
	 */
	protected KYCProfileValidator() {
	}


	/**
	 * handles creation validation for a KYCProfile
	 */
	public void validate( CreateKYCProfileCommand kYCProfile )throws ValidationException {
		if ( kYCProfile == null )
			throw new ValidationException( "KYCProfile", "validating CreateKYCProfileCommand" );
		if ( kYCProfile.getProfileId() == null )
			throw new ValidationException( "KYCProfile", "validating access on getProfileId" );
		if ( kYCProfile.getCreatedAt() == null )
			throw new ValidationException( "KYCProfile", "validating access on getCreatedAt" );
	}

	/**
	 * handles update validation for a KYCProfile
	 */
	public void validate( UpdateKYCProfileCommand kYCProfile ) throws ValidationException {
		if ( kYCProfile == null )
			throw new ValidationException( "KYCProfile", "validating UpdateKYCProfileCommand" );
		if ( kYCProfile.getProfileId() == null )
			throw new ValidationException( "KYCProfile", "validating method getProfileId" );
		if ( kYCProfile.getCreatedAt() == null )
			throw new ValidationException( "KYCProfile", "validating method getCreatedAt" );
	}

/**
 * handles delete validation for a KYCProfile
 */
	public void validate( DeleteKYCProfileCommand kYCProfile ) throws ValidationException {
		if ( kYCProfile == null )
			throw new ValidationException( "KYCProfile", "validating DeleteKYCProfileCommand" );

		if ( kYCProfile.getId() == null )
			throw new ValidationException( "KYCProfile", "validating DeleteKYCProfileCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a KYCProfile
 */
	public void validate( KYCProfileFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "KYCProfile", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "KYCProfile", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Customer validation for a KYCProfile
	 *
	 * @param	command AssignCustomerToKYCProfileCommand
	 */
	public void validate( AssignCustomerToKYCProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "KYCProfile", "validating AssignCustomerToKYCProfileCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "KYCProfile", "validating identity on AssignCustomerToKYCProfileCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Customer validation for a KYCProfile
	 *
	 * @param	command UnAssignCustomerFromKYCProfileCommand
	 */
	public void validate( UnAssignCustomerFromKYCProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "KYCProfile", "validating UnAssignCustomerFromKYCProfileCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "KYCProfile", "validating identity on UnAssignCustomerFromKYCProfileCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Documents validation for a KYCProfile
	 *
	 * @param	command AssignDocumentsToKYCProfileCommand
	 */
	public void validate( AssignDocumentsToKYCProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "KYCProfile", "validating AssignDocumentsToKYCProfileCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "KYCProfile", "validating identity on AssignDocumentsToKYCProfileCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Documents validation for a KYCProfile
	 *
	 * @param	command RemoveDocumentsFromKYCProfileCommand
	 */
	public void validate( RemoveDocumentsFromKYCProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("KYCProfile", "validating RemoveDocumentsFromKYCProfileCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "KYCProfile", "validating identity on RemoveDocumentsFromKYCProfileCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Screenings validation for a KYCProfile
	 *
	 * @param	command AssignScreeningsToKYCProfileCommand
	 */
	public void validate( AssignScreeningsToKYCProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "KYCProfile", "validating AssignScreeningsToKYCProfileCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "KYCProfile", "validating identity on AssignScreeningsToKYCProfileCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Screenings validation for a KYCProfile
	 *
	 * @param	command RemoveScreeningsFromKYCProfileCommand
	 */
	public void validate( RemoveScreeningsFromKYCProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("KYCProfile", "validating RemoveScreeningsFromKYCProfileCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "KYCProfile", "validating identity on RemoveScreeningsFromKYCProfileCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Addresses validation for a KYCProfile
	 *
	 * @param	command AssignAddressesToKYCProfileCommand
	 */
	public void validate( AssignAddressesToKYCProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "KYCProfile", "validating AssignAddressesToKYCProfileCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "KYCProfile", "validating identity on AssignAddressesToKYCProfileCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Addresses validation for a KYCProfile
	 *
	 * @param	command RemoveAddressesFromKYCProfileCommand
	 */
	public void validate( RemoveAddressesFromKYCProfileCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("KYCProfile", "validating RemoveAddressesFromKYCProfileCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "KYCProfile", "validating identity on RemoveAddressesFromKYCProfileCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
