/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>LoanTransactionValidation</h2>
 * <p>
 * The LoanTransaction Validation  handles state validation of a LoanTransaction include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateLoanTransactionCommand</li>
 *      <li>UpdateLoanTransactionCommand</li>
 *      <li>DeleteLoanTransactionCommand</li>
 *set( false = false )
  *       <li>AssignLoanToLoanTransactionCommand</li>
 *       <li>UnAssignLoanFromLoanTransactionCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class LoanTransactionValidator {

	/**
	 * default constructor
	 */
	protected LoanTransactionValidator() {
	}


	/**
	 * handles creation validation for a LoanTransaction
	 */
	public void validate( CreateLoanTransactionCommand loanTransaction )throws ValidationException {
		if ( loanTransaction == null )
			throw new ValidationException( "LoanTransaction", "validating CreateLoanTransactionCommand" );
		if ( loanTransaction.getTransactionId() == null )
			throw new ValidationException( "LoanTransaction", "validating access on getTransactionId" );
		if ( loanTransaction.getAmount() == null )
			throw new ValidationException( "LoanTransaction", "validating access on getAmount" );
		if ( loanTransaction.getPostingDate() == null )
			throw new ValidationException( "LoanTransaction", "validating access on getPostingDate" );
	}

	/**
	 * handles update validation for a LoanTransaction
	 */
	public void validate( UpdateLoanTransactionCommand loanTransaction ) throws ValidationException {
		if ( loanTransaction == null )
			throw new ValidationException( "LoanTransaction", "validating UpdateLoanTransactionCommand" );
		if ( loanTransaction.getTransactionId() == null )
			throw new ValidationException( "LoanTransaction", "validating method getTransactionId" );
		if ( loanTransaction.getAmount() == null )
			throw new ValidationException( "LoanTransaction", "validating method getAmount" );
		if ( loanTransaction.getPostingDate() == null )
			throw new ValidationException( "LoanTransaction", "validating method getPostingDate" );
	}

/**
 * handles delete validation for a LoanTransaction
 */
	public void validate( DeleteLoanTransactionCommand loanTransaction ) throws ValidationException {
		if ( loanTransaction == null )
			throw new ValidationException( "LoanTransaction", "validating DeleteLoanTransactionCommand" );

		if ( loanTransaction.getId() == null )
			throw new ValidationException( "LoanTransaction", "validating DeleteLoanTransactionCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a LoanTransaction
 */
	public void validate( LoanTransactionFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "LoanTransaction", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "LoanTransaction", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Loan validation for a LoanTransaction
	 *
	 * @param	command AssignLoanToLoanTransactionCommand
	 */
	public void validate( AssignLoanToLoanTransactionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "LoanTransaction", "validating AssignLoanToLoanTransactionCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "LoanTransaction", "validating identity on AssignLoanToLoanTransactionCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Loan validation for a LoanTransaction
	 *
	 * @param	command UnAssignLoanFromLoanTransactionCommand
	 */
	public void validate( UnAssignLoanFromLoanTransactionCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "LoanTransaction", "validating UnAssignLoanFromLoanTransactionCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "LoanTransaction", "validating identity on UnAssignLoanFromLoanTransactionCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}


}
