/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>PaymentCardValidation</h2>
 * <p>
 * The PaymentCard Validation  handles state validation of a PaymentCard include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreatePaymentCardCommand</li>
 *      <li>UpdatePaymentCardCommand</li>
 *      <li>DeletePaymentCardCommand</li>
 *set( false = false )
  *       <li>AssignCustomerToPaymentCardCommand</li>
 *       <li>UnAssignCustomerFromPaymentCardCommand</li>
  *       <li>AssignAccountToPaymentCardCommand</li>
 *       <li>UnAssignAccountFromPaymentCardCommand</li>
   *       <li>AssignTokenizationsToPaymentCardCommand</li>
 *       <li>RemoveTokenizationsFromPaymentCardCommand</li>
 *   </ul>
 *
  *       <li>AssignDisputesToPaymentCardCommand</li>
 *       <li>RemoveDisputesFromPaymentCardCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class PaymentCardValidator {

	/**
	 * default constructor
	 */
	protected PaymentCardValidator() {
	}


	/**
	 * handles creation validation for a PaymentCard
	 */
	public void validate( CreatePaymentCardCommand paymentCard )throws ValidationException {
		if ( paymentCard == null )
			throw new ValidationException( "PaymentCard", "validating CreatePaymentCardCommand" );
		if ( paymentCard.getCardToken() == null )
			throw new ValidationException( "PaymentCard", "validating access on getCardToken" );
		if ( paymentCard.getMaskedPan() == null )
			throw new ValidationException( "PaymentCard", "validating access on getMaskedPan" );
		if ( paymentCard.getExpiryMonth() == null )
			throw new ValidationException( "PaymentCard", "validating access on getExpiryMonth" );
		if ( paymentCard.getExpiryYear() == null )
			throw new ValidationException( "PaymentCard", "validating access on getExpiryYear" );
		if ( paymentCard.getCardholderName() == null )
			throw new ValidationException( "PaymentCard", "validating access on getCardholderName" );
	}

	/**
	 * handles update validation for a PaymentCard
	 */
	public void validate( UpdatePaymentCardCommand paymentCard ) throws ValidationException {
		if ( paymentCard == null )
			throw new ValidationException( "PaymentCard", "validating UpdatePaymentCardCommand" );
		if ( paymentCard.getCardToken() == null )
			throw new ValidationException( "PaymentCard", "validating method getCardToken" );
		if ( paymentCard.getMaskedPan() == null )
			throw new ValidationException( "PaymentCard", "validating method getMaskedPan" );
		if ( paymentCard.getExpiryMonth() == null )
			throw new ValidationException( "PaymentCard", "validating method getExpiryMonth" );
		if ( paymentCard.getExpiryYear() == null )
			throw new ValidationException( "PaymentCard", "validating method getExpiryYear" );
		if ( paymentCard.getCardholderName() == null )
			throw new ValidationException( "PaymentCard", "validating method getCardholderName" );
	}

/**
 * handles delete validation for a PaymentCard
 */
	public void validate( DeletePaymentCardCommand paymentCard ) throws ValidationException {
		if ( paymentCard == null )
			throw new ValidationException( "PaymentCard", "validating DeletePaymentCardCommand" );

		if ( paymentCard.getId() == null )
			throw new ValidationException( "PaymentCard", "validating DeletePaymentCardCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a PaymentCard
 */
	public void validate( PaymentCardFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "PaymentCard", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "PaymentCard", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Customer validation for a PaymentCard
	 *
	 * @param	command AssignCustomerToPaymentCardCommand
	 */
	public void validate( AssignCustomerToPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentCard", "validating AssignCustomerToPaymentCardCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentCard", "validating identity on AssignCustomerToPaymentCardCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Customer validation for a PaymentCard
	 *
	 * @param	command UnAssignCustomerFromPaymentCardCommand
	 */
	public void validate( UnAssignCustomerFromPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentCard", "validating UnAssignCustomerFromPaymentCardCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentCard", "validating identity on UnAssignCustomerFromPaymentCardCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Account validation for a PaymentCard
	 *
	 * @param	command AssignAccountToPaymentCardCommand
	 */
	public void validate( AssignAccountToPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentCard", "validating AssignAccountToPaymentCardCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentCard", "validating identity on AssignAccountToPaymentCardCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Account validation for a PaymentCard
	 *
	 * @param	command UnAssignAccountFromPaymentCardCommand
	 */
	public void validate( UnAssignAccountFromPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentCard", "validating UnAssignAccountFromPaymentCardCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentCard", "validating identity on UnAssignAccountFromPaymentCardCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Tokenizations validation for a PaymentCard
	 *
	 * @param	command AssignTokenizationsToPaymentCardCommand
	 */
	public void validate( AssignTokenizationsToPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentCard", "validating AssignTokenizationsToPaymentCardCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PaymentCard", "validating identity on AssignTokenizationsToPaymentCardCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Tokenizations validation for a PaymentCard
	 *
	 * @param	command RemoveTokenizationsFromPaymentCardCommand
	 */
	public void validate( RemoveTokenizationsFromPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("PaymentCard", "validating RemoveTokenizationsFromPaymentCardCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PaymentCard", "validating identity on RemoveTokenizationsFromPaymentCardCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Disputes validation for a PaymentCard
	 *
	 * @param	command AssignDisputesToPaymentCardCommand
	 */
	public void validate( AssignDisputesToPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentCard", "validating AssignDisputesToPaymentCardCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PaymentCard", "validating identity on AssignDisputesToPaymentCardCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Disputes validation for a PaymentCard
	 *
	 * @param	command RemoveDisputesFromPaymentCardCommand
	 */
	public void validate( RemoveDisputesFromPaymentCardCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("PaymentCard", "validating RemoveDisputesFromPaymentCardCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PaymentCard", "validating identity on RemoveDisputesFromPaymentCardCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
