/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>PaymentContractValidation</h2>
 * <p>
 * The PaymentContract Validation  handles state validation of a PaymentContract include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreatePaymentContractCommand</li>
 *      <li>UpdatePaymentContractCommand</li>
 *      <li>DeletePaymentContractCommand</li>
 *set( false = false )
  *       <li>AssignMerchantToPaymentContractCommand</li>
 *       <li>UnAssignMerchantFromPaymentContractCommand</li>
  *       <li>AssignAcquirerToPaymentContractCommand</li>
 *       <li>UnAssignAcquirerFromPaymentContractCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class PaymentContractValidator {

	/**
	 * default constructor
	 */
	protected PaymentContractValidator() {
	}


	/**
	 * handles creation validation for a PaymentContract
	 */
	public void validate( CreatePaymentContractCommand paymentContract )throws ValidationException {
		if ( paymentContract == null )
			throw new ValidationException( "PaymentContract", "validating CreatePaymentContractCommand" );
		if ( paymentContract.getContractNumber() == null )
			throw new ValidationException( "PaymentContract", "validating access on getContractNumber" );
		if ( paymentContract.getPricingPlanCode() == null )
			throw new ValidationException( "PaymentContract", "validating access on getPricingPlanCode" );
	}

	/**
	 * handles update validation for a PaymentContract
	 */
	public void validate( UpdatePaymentContractCommand paymentContract ) throws ValidationException {
		if ( paymentContract == null )
			throw new ValidationException( "PaymentContract", "validating UpdatePaymentContractCommand" );
		if ( paymentContract.getContractNumber() == null )
			throw new ValidationException( "PaymentContract", "validating method getContractNumber" );
		if ( paymentContract.getPricingPlanCode() == null )
			throw new ValidationException( "PaymentContract", "validating method getPricingPlanCode" );
	}

/**
 * handles delete validation for a PaymentContract
 */
	public void validate( DeletePaymentContractCommand paymentContract ) throws ValidationException {
		if ( paymentContract == null )
			throw new ValidationException( "PaymentContract", "validating DeletePaymentContractCommand" );

		if ( paymentContract.getId() == null )
			throw new ValidationException( "PaymentContract", "validating DeletePaymentContractCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a PaymentContract
 */
	public void validate( PaymentContractFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "PaymentContract", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "PaymentContract", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Merchant validation for a PaymentContract
	 *
	 * @param	command AssignMerchantToPaymentContractCommand
	 */
	public void validate( AssignMerchantToPaymentContractCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentContract", "validating AssignMerchantToPaymentContractCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentContract", "validating identity on AssignMerchantToPaymentContractCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Merchant validation for a PaymentContract
	 *
	 * @param	command UnAssignMerchantFromPaymentContractCommand
	 */
	public void validate( UnAssignMerchantFromPaymentContractCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentContract", "validating UnAssignMerchantFromPaymentContractCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentContract", "validating identity on UnAssignMerchantFromPaymentContractCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Acquirer validation for a PaymentContract
	 *
	 * @param	command AssignAcquirerToPaymentContractCommand
	 */
	public void validate( AssignAcquirerToPaymentContractCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentContract", "validating AssignAcquirerToPaymentContractCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentContract", "validating identity on AssignAcquirerToPaymentContractCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Acquirer validation for a PaymentContract
	 *
	 * @param	command UnAssignAcquirerFromPaymentContractCommand
	 */
	public void validate( UnAssignAcquirerFromPaymentContractCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentContract", "validating UnAssignAcquirerFromPaymentContractCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentContract", "validating identity on UnAssignAcquirerFromPaymentContractCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}


}
