/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>PaymentOrderValidation</h2>
 * <p>
 * The PaymentOrder Validation  handles state validation of a PaymentOrder include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreatePaymentOrderCommand</li>
 *      <li>UpdatePaymentOrderCommand</li>
 *      <li>DeletePaymentOrderCommand</li>
 *set( false = false )
  *       <li>AssignSourceAccountToPaymentOrderCommand</li>
 *       <li>UnAssignSourceAccountFromPaymentOrderCommand</li>
  *       <li>AssignDestinationAccountToPaymentOrderCommand</li>
 *       <li>UnAssignDestinationAccountFromPaymentOrderCommand</li>
  *       <li>AssignBeneficiaryToPaymentOrderCommand</li>
 *       <li>UnAssignBeneficiaryFromPaymentOrderCommand</li>
  *       <li>AssignFxDealToPaymentOrderCommand</li>
 *       <li>UnAssignFxDealFromPaymentOrderCommand</li>
   *       <li>AssignTransactionsToPaymentOrderCommand</li>
 *       <li>RemoveTransactionsFromPaymentOrderCommand</li>
 *   </ul>
 *
  *       <li>AssignFeesToPaymentOrderCommand</li>
 *       <li>RemoveFeesFromPaymentOrderCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class PaymentOrderValidator {

	/**
	 * default constructor
	 */
	protected PaymentOrderValidator() {
	}


	/**
	 * handles creation validation for a PaymentOrder
	 */
	public void validate( CreatePaymentOrderCommand paymentOrder )throws ValidationException {
		if ( paymentOrder == null )
			throw new ValidationException( "PaymentOrder", "validating CreatePaymentOrderCommand" );
		if ( paymentOrder.getOrderReference() == null )
			throw new ValidationException( "PaymentOrder", "validating access on getOrderReference" );
		if ( paymentOrder.getRequestedExecutionDate() == null )
			throw new ValidationException( "PaymentOrder", "validating access on getRequestedExecutionDate" );
		if ( paymentOrder.getPurpose() == null )
			throw new ValidationException( "PaymentOrder", "validating access on getPurpose" );
	}

	/**
	 * handles update validation for a PaymentOrder
	 */
	public void validate( UpdatePaymentOrderCommand paymentOrder ) throws ValidationException {
		if ( paymentOrder == null )
			throw new ValidationException( "PaymentOrder", "validating UpdatePaymentOrderCommand" );
		if ( paymentOrder.getOrderReference() == null )
			throw new ValidationException( "PaymentOrder", "validating method getOrderReference" );
		if ( paymentOrder.getRequestedExecutionDate() == null )
			throw new ValidationException( "PaymentOrder", "validating method getRequestedExecutionDate" );
		if ( paymentOrder.getPurpose() == null )
			throw new ValidationException( "PaymentOrder", "validating method getPurpose" );
	}

/**
 * handles delete validation for a PaymentOrder
 */
	public void validate( DeletePaymentOrderCommand paymentOrder ) throws ValidationException {
		if ( paymentOrder == null )
			throw new ValidationException( "PaymentOrder", "validating DeletePaymentOrderCommand" );

		if ( paymentOrder.getId() == null )
			throw new ValidationException( "PaymentOrder", "validating DeletePaymentOrderCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a PaymentOrder
 */
	public void validate( PaymentOrderFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "PaymentOrder", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "PaymentOrder", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign SourceAccount validation for a PaymentOrder
	 *
	 * @param	command AssignSourceAccountToPaymentOrderCommand
	 */
	public void validate( AssignSourceAccountToPaymentOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentOrder", "validating AssignSourceAccountToPaymentOrderCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentOrder", "validating identity on AssignSourceAccountToPaymentOrderCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign SourceAccount validation for a PaymentOrder
	 *
	 * @param	command UnAssignSourceAccountFromPaymentOrderCommand
	 */
	public void validate( UnAssignSourceAccountFromPaymentOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentOrder", "validating UnAssignSourceAccountFromPaymentOrderCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentOrder", "validating identity on UnAssignSourceAccountFromPaymentOrderCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign DestinationAccount validation for a PaymentOrder
	 *
	 * @param	command AssignDestinationAccountToPaymentOrderCommand
	 */
	public void validate( AssignDestinationAccountToPaymentOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentOrder", "validating AssignDestinationAccountToPaymentOrderCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentOrder", "validating identity on AssignDestinationAccountToPaymentOrderCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign DestinationAccount validation for a PaymentOrder
	 *
	 * @param	command UnAssignDestinationAccountFromPaymentOrderCommand
	 */
	public void validate( UnAssignDestinationAccountFromPaymentOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentOrder", "validating UnAssignDestinationAccountFromPaymentOrderCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentOrder", "validating identity on UnAssignDestinationAccountFromPaymentOrderCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Beneficiary validation for a PaymentOrder
	 *
	 * @param	command AssignBeneficiaryToPaymentOrderCommand
	 */
	public void validate( AssignBeneficiaryToPaymentOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentOrder", "validating AssignBeneficiaryToPaymentOrderCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentOrder", "validating identity on AssignBeneficiaryToPaymentOrderCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Beneficiary validation for a PaymentOrder
	 *
	 * @param	command UnAssignBeneficiaryFromPaymentOrderCommand
	 */
	public void validate( UnAssignBeneficiaryFromPaymentOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentOrder", "validating UnAssignBeneficiaryFromPaymentOrderCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentOrder", "validating identity on UnAssignBeneficiaryFromPaymentOrderCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign FxDeal validation for a PaymentOrder
	 *
	 * @param	command AssignFxDealToPaymentOrderCommand
	 */
	public void validate( AssignFxDealToPaymentOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentOrder", "validating AssignFxDealToPaymentOrderCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentOrder", "validating identity on AssignFxDealToPaymentOrderCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign FxDeal validation for a PaymentOrder
	 *
	 * @param	command UnAssignFxDealFromPaymentOrderCommand
	 */
	public void validate( UnAssignFxDealFromPaymentOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentOrder", "validating UnAssignFxDealFromPaymentOrderCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "PaymentOrder", "validating identity on UnAssignFxDealFromPaymentOrderCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Transactions validation for a PaymentOrder
	 *
	 * @param	command AssignTransactionsToPaymentOrderCommand
	 */
	public void validate( AssignTransactionsToPaymentOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentOrder", "validating AssignTransactionsToPaymentOrderCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PaymentOrder", "validating identity on AssignTransactionsToPaymentOrderCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Transactions validation for a PaymentOrder
	 *
	 * @param	command RemoveTransactionsFromPaymentOrderCommand
	 */
	public void validate( RemoveTransactionsFromPaymentOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("PaymentOrder", "validating RemoveTransactionsFromPaymentOrderCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PaymentOrder", "validating identity on RemoveTransactionsFromPaymentOrderCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Fees validation for a PaymentOrder
	 *
	 * @param	command AssignFeesToPaymentOrderCommand
	 */
	public void validate( AssignFeesToPaymentOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "PaymentOrder", "validating AssignFeesToPaymentOrderCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PaymentOrder", "validating identity on AssignFeesToPaymentOrderCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Fees validation for a PaymentOrder
	 *
	 * @param	command RemoveFeesFromPaymentOrderCommand
	 */
	public void validate( RemoveFeesFromPaymentOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("PaymentOrder", "validating RemoveFeesFromPaymentOrderCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "PaymentOrder", "validating identity on RemoveFeesFromPaymentOrderCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
