/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>PayoutValidation</h2>
 * <p>
 * The Payout Validation  handles state validation of a Payout include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreatePayoutCommand</li>
 *      <li>UpdatePayoutCommand</li>
 *      <li>DeletePayoutCommand</li>
 *set( false = false )
  *       <li>AssignMerchantToPayoutCommand</li>
 *       <li>UnAssignMerchantFromPayoutCommand</li>
  *       <li>AssignSettlementBatchToPayoutCommand</li>
 *       <li>UnAssignSettlementBatchFromPayoutCommand</li>
  *       <li>AssignDestinationAccountToPayoutCommand</li>
 *       <li>UnAssignDestinationAccountFromPayoutCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class PayoutValidator {

	/**
	 * default constructor
	 */
	protected PayoutValidator() {
	}


	/**
	 * handles creation validation for a Payout
	 */
	public void validate( CreatePayoutCommand payout )throws ValidationException {
		if ( payout == null )
			throw new ValidationException( "Payout", "validating CreatePayoutCommand" );
		if ( payout.getPayoutReference() == null )
			throw new ValidationException( "Payout", "validating access on getPayoutReference" );
		if ( payout.getAmount() == null )
			throw new ValidationException( "Payout", "validating access on getAmount" );
		if ( payout.getCurrency() == null )
			throw new ValidationException( "Payout", "validating access on getCurrency" );
		if ( payout.getScheduledDate() == null )
			throw new ValidationException( "Payout", "validating access on getScheduledDate" );
		if ( payout.getPaidDate() == null )
			throw new ValidationException( "Payout", "validating access on getPaidDate" );
	}

	/**
	 * handles update validation for a Payout
	 */
	public void validate( UpdatePayoutCommand payout ) throws ValidationException {
		if ( payout == null )
			throw new ValidationException( "Payout", "validating UpdatePayoutCommand" );
		if ( payout.getPayoutReference() == null )
			throw new ValidationException( "Payout", "validating method getPayoutReference" );
		if ( payout.getAmount() == null )
			throw new ValidationException( "Payout", "validating method getAmount" );
		if ( payout.getCurrency() == null )
			throw new ValidationException( "Payout", "validating method getCurrency" );
		if ( payout.getScheduledDate() == null )
			throw new ValidationException( "Payout", "validating method getScheduledDate" );
		if ( payout.getPaidDate() == null )
			throw new ValidationException( "Payout", "validating method getPaidDate" );
	}

/**
 * handles delete validation for a Payout
 */
	public void validate( DeletePayoutCommand payout ) throws ValidationException {
		if ( payout == null )
			throw new ValidationException( "Payout", "validating DeletePayoutCommand" );

		if ( payout.getId() == null )
			throw new ValidationException( "Payout", "validating DeletePayoutCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Payout
 */
	public void validate( PayoutFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Payout", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Payout", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Merchant validation for a Payout
	 *
	 * @param	command AssignMerchantToPayoutCommand
	 */
	public void validate( AssignMerchantToPayoutCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Payout", "validating AssignMerchantToPayoutCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Payout", "validating identity on AssignMerchantToPayoutCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Merchant validation for a Payout
	 *
	 * @param	command UnAssignMerchantFromPayoutCommand
	 */
	public void validate( UnAssignMerchantFromPayoutCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Payout", "validating UnAssignMerchantFromPayoutCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Payout", "validating identity on UnAssignMerchantFromPayoutCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign SettlementBatch validation for a Payout
	 *
	 * @param	command AssignSettlementBatchToPayoutCommand
	 */
	public void validate( AssignSettlementBatchToPayoutCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Payout", "validating AssignSettlementBatchToPayoutCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Payout", "validating identity on AssignSettlementBatchToPayoutCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign SettlementBatch validation for a Payout
	 *
	 * @param	command UnAssignSettlementBatchFromPayoutCommand
	 */
	public void validate( UnAssignSettlementBatchFromPayoutCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Payout", "validating UnAssignSettlementBatchFromPayoutCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Payout", "validating identity on UnAssignSettlementBatchFromPayoutCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign DestinationAccount validation for a Payout
	 *
	 * @param	command AssignDestinationAccountToPayoutCommand
	 */
	public void validate( AssignDestinationAccountToPayoutCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Payout", "validating AssignDestinationAccountToPayoutCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Payout", "validating identity on AssignDestinationAccountToPayoutCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign DestinationAccount validation for a Payout
	 *
	 * @param	command UnAssignDestinationAccountFromPayoutCommand
	 */
	public void validate( UnAssignDestinationAccountFromPayoutCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Payout", "validating UnAssignDestinationAccountFromPayoutCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Payout", "validating identity on UnAssignDestinationAccountFromPayoutCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}


}
