/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>ProductOfferingValidation</h2>
 * <p>
 * The ProductOffering Validation  handles state validation of a ProductOffering include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateProductOfferingCommand</li>
 *      <li>UpdateProductOfferingCommand</li>
 *      <li>DeleteProductOfferingCommand</li>
 *set( false = false )
  *       <li>AssignInstitutionToProductOfferingCommand</li>
 *       <li>UnAssignInstitutionFromProductOfferingCommand</li>
   *       <li>AssignPricingPlansToProductOfferingCommand</li>
 *       <li>RemovePricingPlansFromProductOfferingCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class ProductOfferingValidator {

	/**
	 * default constructor
	 */
	protected ProductOfferingValidator() {
	}


	/**
	 * handles creation validation for a ProductOffering
	 */
	public void validate( CreateProductOfferingCommand productOffering )throws ValidationException {
		if ( productOffering == null )
			throw new ValidationException( "ProductOffering", "validating CreateProductOfferingCommand" );
		if ( productOffering.getName() == null )
			throw new ValidationException( "ProductOffering", "validating access on getName" );
		if ( productOffering.getProductCode() == null )
			throw new ValidationException( "ProductOffering", "validating access on getProductCode" );
	}

	/**
	 * handles update validation for a ProductOffering
	 */
	public void validate( UpdateProductOfferingCommand productOffering ) throws ValidationException {
		if ( productOffering == null )
			throw new ValidationException( "ProductOffering", "validating UpdateProductOfferingCommand" );
		if ( productOffering.getName() == null )
			throw new ValidationException( "ProductOffering", "validating method getName" );
		if ( productOffering.getProductCode() == null )
			throw new ValidationException( "ProductOffering", "validating method getProductCode" );
	}

/**
 * handles delete validation for a ProductOffering
 */
	public void validate( DeleteProductOfferingCommand productOffering ) throws ValidationException {
		if ( productOffering == null )
			throw new ValidationException( "ProductOffering", "validating DeleteProductOfferingCommand" );

		if ( productOffering.getId() == null )
			throw new ValidationException( "ProductOffering", "validating DeleteProductOfferingCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a ProductOffering
 */
	public void validate( ProductOfferingFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "ProductOffering", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "ProductOffering", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Institution validation for a ProductOffering
	 *
	 * @param	command AssignInstitutionToProductOfferingCommand
	 */
	public void validate( AssignInstitutionToProductOfferingCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "ProductOffering", "validating AssignInstitutionToProductOfferingCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "ProductOffering", "validating identity on AssignInstitutionToProductOfferingCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Institution validation for a ProductOffering
	 *
	 * @param	command UnAssignInstitutionFromProductOfferingCommand
	 */
	public void validate( UnAssignInstitutionFromProductOfferingCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "ProductOffering", "validating UnAssignInstitutionFromProductOfferingCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "ProductOffering", "validating identity on UnAssignInstitutionFromProductOfferingCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to PricingPlans validation for a ProductOffering
	 *
	 * @param	command AssignPricingPlansToProductOfferingCommand
	 */
	public void validate( AssignPricingPlansToProductOfferingCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "ProductOffering", "validating AssignPricingPlansToProductOfferingCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "ProductOffering", "validating identity on AssignPricingPlansToProductOfferingCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from PricingPlans validation for a ProductOffering
	 *
	 * @param	command RemovePricingPlansFromProductOfferingCommand
	 */
	public void validate( RemovePricingPlansFromProductOfferingCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("ProductOffering", "validating RemovePricingPlansFromProductOfferingCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "ProductOffering", "validating identity on RemovePricingPlansFromProductOfferingCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
