/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>ScreeningValidation</h2>
 * <p>
 * The Screening Validation  handles state validation of a Screening include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateScreeningCommand</li>
 *      <li>UpdateScreeningCommand</li>
 *      <li>DeleteScreeningCommand</li>
 *set( false = false )
  *       <li>AssignKycProfileToScreeningCommand</li>
 *       <li>UnAssignKycProfileFromScreeningCommand</li>
   *       <li>AssignAlertsToScreeningCommand</li>
 *       <li>RemoveAlertsFromScreeningCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class ScreeningValidator {

	/**
	 * default constructor
	 */
	protected ScreeningValidator() {
	}


	/**
	 * handles creation validation for a Screening
	 */
	public void validate( CreateScreeningCommand screening )throws ValidationException {
		if ( screening == null )
			throw new ValidationException( "Screening", "validating CreateScreeningCommand" );
		if ( screening.getScore() == null )
			throw new ValidationException( "Screening", "validating access on getScore" );
		if ( screening.getScreenedAt() == null )
			throw new ValidationException( "Screening", "validating access on getScreenedAt" );
	}

	/**
	 * handles update validation for a Screening
	 */
	public void validate( UpdateScreeningCommand screening ) throws ValidationException {
		if ( screening == null )
			throw new ValidationException( "Screening", "validating UpdateScreeningCommand" );
		if ( screening.getScore() == null )
			throw new ValidationException( "Screening", "validating method getScore" );
		if ( screening.getScreenedAt() == null )
			throw new ValidationException( "Screening", "validating method getScreenedAt" );
	}

/**
 * handles delete validation for a Screening
 */
	public void validate( DeleteScreeningCommand screening ) throws ValidationException {
		if ( screening == null )
			throw new ValidationException( "Screening", "validating DeleteScreeningCommand" );

		if ( screening.getId() == null )
			throw new ValidationException( "Screening", "validating DeleteScreeningCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Screening
 */
	public void validate( ScreeningFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Screening", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Screening", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign KycProfile validation for a Screening
	 *
	 * @param	command AssignKycProfileToScreeningCommand
	 */
	public void validate( AssignKycProfileToScreeningCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Screening", "validating AssignKycProfileToScreeningCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Screening", "validating identity on AssignKycProfileToScreeningCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign KycProfile validation for a Screening
	 *
	 * @param	command UnAssignKycProfileFromScreeningCommand
	 */
	public void validate( UnAssignKycProfileFromScreeningCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Screening", "validating UnAssignKycProfileFromScreeningCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Screening", "validating identity on UnAssignKycProfileFromScreeningCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Alerts validation for a Screening
	 *
	 * @param	command AssignAlertsToScreeningCommand
	 */
	public void validate( AssignAlertsToScreeningCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Screening", "validating AssignAlertsToScreeningCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Screening", "validating identity on AssignAlertsToScreeningCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Alerts validation for a Screening
	 *
	 * @param	command RemoveAlertsFromScreeningCommand
	 */
	public void validate( RemoveAlertsFromScreeningCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Screening", "validating RemoveAlertsFromScreeningCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Screening", "validating identity on RemoveAlertsFromScreeningCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
