/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>SecurityValidation</h2>
 * <p>
 * The Security Validation  handles state validation of a Security include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateSecurityCommand</li>
 *      <li>UpdateSecurityCommand</li>
 *      <li>DeleteSecurityCommand</li>
 *set( false = false )
   *       <li>AssignPositionsToSecurityCommand</li>
 *       <li>RemovePositionsFromSecurityCommand</li>
 *   </ul>
 *
  *       <li>AssignTradesToSecurityCommand</li>
 *       <li>RemoveTradesFromSecurityCommand</li>
 *   </ul>
 *
  *       <li>AssignOrdersToSecurityCommand</li>
 *       <li>RemoveOrdersFromSecurityCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class SecurityValidator {

	/**
	 * default constructor
	 */
	protected SecurityValidator() {
	}


	/**
	 * handles creation validation for a Security
	 */
	public void validate( CreateSecurityCommand security )throws ValidationException {
		if ( security == null )
			throw new ValidationException( "Security", "validating CreateSecurityCommand" );
		if ( security.getSymbol() == null )
			throw new ValidationException( "Security", "validating access on getSymbol" );
		if ( security.getIsin() == null )
			throw new ValidationException( "Security", "validating access on getIsin" );
		if ( security.getCusip() == null )
			throw new ValidationException( "Security", "validating access on getCusip" );
		if ( security.getCurrency() == null )
			throw new ValidationException( "Security", "validating access on getCurrency" );
	}

	/**
	 * handles update validation for a Security
	 */
	public void validate( UpdateSecurityCommand security ) throws ValidationException {
		if ( security == null )
			throw new ValidationException( "Security", "validating UpdateSecurityCommand" );
		if ( security.getSymbol() == null )
			throw new ValidationException( "Security", "validating method getSymbol" );
		if ( security.getIsin() == null )
			throw new ValidationException( "Security", "validating method getIsin" );
		if ( security.getCusip() == null )
			throw new ValidationException( "Security", "validating method getCusip" );
		if ( security.getCurrency() == null )
			throw new ValidationException( "Security", "validating method getCurrency" );
	}

/**
 * handles delete validation for a Security
 */
	public void validate( DeleteSecurityCommand security ) throws ValidationException {
		if ( security == null )
			throw new ValidationException( "Security", "validating DeleteSecurityCommand" );

		if ( security.getId() == null )
			throw new ValidationException( "Security", "validating DeleteSecurityCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Security
 */
	public void validate( SecurityFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Security", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Security", "validating FetchOneSummary identifier discovered as null" );
	}


	/**
	 * handles add to Positions validation for a Security
	 *
	 * @param	command AssignPositionsToSecurityCommand
	 */
	public void validate( AssignPositionsToSecurityCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Security", "validating AssignPositionsToSecurityCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Security", "validating identity on AssignPositionsToSecurityCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Positions validation for a Security
	 *
	 * @param	command RemovePositionsFromSecurityCommand
	 */
	public void validate( RemovePositionsFromSecurityCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Security", "validating RemovePositionsFromSecurityCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Security", "validating identity on RemovePositionsFromSecurityCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Trades validation for a Security
	 *
	 * @param	command AssignTradesToSecurityCommand
	 */
	public void validate( AssignTradesToSecurityCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Security", "validating AssignTradesToSecurityCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Security", "validating identity on AssignTradesToSecurityCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Trades validation for a Security
	 *
	 * @param	command RemoveTradesFromSecurityCommand
	 */
	public void validate( RemoveTradesFromSecurityCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Security", "validating RemoveTradesFromSecurityCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Security", "validating identity on RemoveTradesFromSecurityCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Orders validation for a Security
	 *
	 * @param	command AssignOrdersToSecurityCommand
	 */
	public void validate( AssignOrdersToSecurityCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Security", "validating AssignOrdersToSecurityCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Security", "validating identity on AssignOrdersToSecurityCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Orders validation for a Security
	 *
	 * @param	command RemoveOrdersFromSecurityCommand
	 */
	public void validate( RemoveOrdersFromSecurityCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Security", "validating RemoveOrdersFromSecurityCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "Security", "validating identity on RemoveOrdersFromSecurityCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
