/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>SettlementBatchValidation</h2>
 * <p>
 * The SettlementBatch Validation  handles state validation of a SettlementBatch include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateSettlementBatchCommand</li>
 *      <li>UpdateSettlementBatchCommand</li>
 *      <li>DeleteSettlementBatchCommand</li>
 *set( false = false )
  *       <li>AssignProcessorToSettlementBatchCommand</li>
 *       <li>UnAssignProcessorFromSettlementBatchCommand</li>
  *       <li>AssignMerchantToSettlementBatchCommand</li>
 *       <li>UnAssignMerchantFromSettlementBatchCommand</li>
   *       <li>AssignPayoutsToSettlementBatchCommand</li>
 *       <li>RemovePayoutsFromSettlementBatchCommand</li>
 *   </ul>
 *
  *       <li>AssignTransactionsToSettlementBatchCommand</li>
 *       <li>RemoveTransactionsFromSettlementBatchCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class SettlementBatchValidator {

	/**
	 * default constructor
	 */
	protected SettlementBatchValidator() {
	}


	/**
	 * handles creation validation for a SettlementBatch
	 */
	public void validate( CreateSettlementBatchCommand settlementBatch )throws ValidationException {
		if ( settlementBatch == null )
			throw new ValidationException( "SettlementBatch", "validating CreateSettlementBatchCommand" );
		if ( settlementBatch.getBatchId() == null )
			throw new ValidationException( "SettlementBatch", "validating access on getBatchId" );
		if ( settlementBatch.getPeriodStart() == null )
			throw new ValidationException( "SettlementBatch", "validating access on getPeriodStart" );
		if ( settlementBatch.getPeriodEnd() == null )
			throw new ValidationException( "SettlementBatch", "validating access on getPeriodEnd" );
		if ( settlementBatch.getTotalVolume() == null )
			throw new ValidationException( "SettlementBatch", "validating access on getTotalVolume" );
		if ( settlementBatch.getTotalCount() == null )
			throw new ValidationException( "SettlementBatch", "validating access on getTotalCount" );
	}

	/**
	 * handles update validation for a SettlementBatch
	 */
	public void validate( UpdateSettlementBatchCommand settlementBatch ) throws ValidationException {
		if ( settlementBatch == null )
			throw new ValidationException( "SettlementBatch", "validating UpdateSettlementBatchCommand" );
		if ( settlementBatch.getBatchId() == null )
			throw new ValidationException( "SettlementBatch", "validating method getBatchId" );
		if ( settlementBatch.getPeriodStart() == null )
			throw new ValidationException( "SettlementBatch", "validating method getPeriodStart" );
		if ( settlementBatch.getPeriodEnd() == null )
			throw new ValidationException( "SettlementBatch", "validating method getPeriodEnd" );
		if ( settlementBatch.getTotalVolume() == null )
			throw new ValidationException( "SettlementBatch", "validating method getTotalVolume" );
		if ( settlementBatch.getTotalCount() == null )
			throw new ValidationException( "SettlementBatch", "validating method getTotalCount" );
	}

/**
 * handles delete validation for a SettlementBatch
 */
	public void validate( DeleteSettlementBatchCommand settlementBatch ) throws ValidationException {
		if ( settlementBatch == null )
			throw new ValidationException( "SettlementBatch", "validating DeleteSettlementBatchCommand" );

		if ( settlementBatch.getId() == null )
			throw new ValidationException( "SettlementBatch", "validating DeleteSettlementBatchCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a SettlementBatch
 */
	public void validate( SettlementBatchFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "SettlementBatch", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "SettlementBatch", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Processor validation for a SettlementBatch
	 *
	 * @param	command AssignProcessorToSettlementBatchCommand
	 */
	public void validate( AssignProcessorToSettlementBatchCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "SettlementBatch", "validating AssignProcessorToSettlementBatchCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "SettlementBatch", "validating identity on AssignProcessorToSettlementBatchCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Processor validation for a SettlementBatch
	 *
	 * @param	command UnAssignProcessorFromSettlementBatchCommand
	 */
	public void validate( UnAssignProcessorFromSettlementBatchCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "SettlementBatch", "validating UnAssignProcessorFromSettlementBatchCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "SettlementBatch", "validating identity on UnAssignProcessorFromSettlementBatchCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Merchant validation for a SettlementBatch
	 *
	 * @param	command AssignMerchantToSettlementBatchCommand
	 */
	public void validate( AssignMerchantToSettlementBatchCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "SettlementBatch", "validating AssignMerchantToSettlementBatchCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "SettlementBatch", "validating identity on AssignMerchantToSettlementBatchCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Merchant validation for a SettlementBatch
	 *
	 * @param	command UnAssignMerchantFromSettlementBatchCommand
	 */
	public void validate( UnAssignMerchantFromSettlementBatchCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "SettlementBatch", "validating UnAssignMerchantFromSettlementBatchCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "SettlementBatch", "validating identity on UnAssignMerchantFromSettlementBatchCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Payouts validation for a SettlementBatch
	 *
	 * @param	command AssignPayoutsToSettlementBatchCommand
	 */
	public void validate( AssignPayoutsToSettlementBatchCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "SettlementBatch", "validating AssignPayoutsToSettlementBatchCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "SettlementBatch", "validating identity on AssignPayoutsToSettlementBatchCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Payouts validation for a SettlementBatch
	 *
	 * @param	command RemovePayoutsFromSettlementBatchCommand
	 */
	public void validate( RemovePayoutsFromSettlementBatchCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("SettlementBatch", "validating RemovePayoutsFromSettlementBatchCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "SettlementBatch", "validating identity on RemovePayoutsFromSettlementBatchCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}

	/**
	 * handles add to Transactions validation for a SettlementBatch
	 *
	 * @param	command AssignTransactionsToSettlementBatchCommand
	 */
	public void validate( AssignTransactionsToSettlementBatchCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "SettlementBatch", "validating AssignTransactionsToSettlementBatchCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "SettlementBatch", "validating identity on AssignTransactionsToSettlementBatchCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Transactions validation for a SettlementBatch
	 *
	 * @param	command RemoveTransactionsFromSettlementBatchCommand
	 */
	public void validate( RemoveTransactionsFromSettlementBatchCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("SettlementBatch", "validating RemoveTransactionsFromSettlementBatchCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "SettlementBatch", "validating identity on RemoveTransactionsFromSettlementBatchCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
