/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>TerminalValidation</h2>
 * <p>
 * The Terminal Validation  handles state validation of a Terminal include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateTerminalCommand</li>
 *      <li>UpdateTerminalCommand</li>
 *      <li>DeleteTerminalCommand</li>
 *set( false = false )
  *       <li>AssignMerchantToTerminalCommand</li>
 *       <li>UnAssignMerchantFromTerminalCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class TerminalValidator {

	/**
	 * default constructor
	 */
	protected TerminalValidator() {
	}


	/**
	 * handles creation validation for a Terminal
	 */
	public void validate( CreateTerminalCommand terminal )throws ValidationException {
		if ( terminal == null )
			throw new ValidationException( "Terminal", "validating CreateTerminalCommand" );
		if ( terminal.getLocation() == null )
			throw new ValidationException( "Terminal", "validating access on getLocation" );
	}

	/**
	 * handles update validation for a Terminal
	 */
	public void validate( UpdateTerminalCommand terminal ) throws ValidationException {
		if ( terminal == null )
			throw new ValidationException( "Terminal", "validating UpdateTerminalCommand" );
		if ( terminal.getLocation() == null )
			throw new ValidationException( "Terminal", "validating method getLocation" );
	}

/**
 * handles delete validation for a Terminal
 */
	public void validate( DeleteTerminalCommand terminal ) throws ValidationException {
		if ( terminal == null )
			throw new ValidationException( "Terminal", "validating DeleteTerminalCommand" );

		if ( terminal.getId() == null )
			throw new ValidationException( "Terminal", "validating DeleteTerminalCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a Terminal
 */
	public void validate( TerminalFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Terminal", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "Terminal", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Merchant validation for a Terminal
	 *
	 * @param	command AssignMerchantToTerminalCommand
	 */
	public void validate( AssignMerchantToTerminalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Terminal", "validating AssignMerchantToTerminalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Terminal", "validating identity on AssignMerchantToTerminalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Merchant validation for a Terminal
	 *
	 * @param	command UnAssignMerchantFromTerminalCommand
	 */
	public void validate( UnAssignMerchantFromTerminalCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Terminal", "validating UnAssignMerchantFromTerminalCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "Terminal", "validating identity on UnAssignMerchantFromTerminalCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}


}
