/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>TradeOrderValidation</h2>
 * <p>
 * The TradeOrder Validation  handles state validation of a TradeOrder include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateTradeOrderCommand</li>
 *      <li>UpdateTradeOrderCommand</li>
 *      <li>DeleteTradeOrderCommand</li>
 *set( false = false )
  *       <li>AssignPortfolioToTradeOrderCommand</li>
 *       <li>UnAssignPortfolioFromTradeOrderCommand</li>
  *       <li>AssignSecurityToTradeOrderCommand</li>
 *       <li>UnAssignSecurityFromTradeOrderCommand</li>
   *       <li>AssignTradesToTradeOrderCommand</li>
 *       <li>RemoveTradesFromTradeOrderCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class TradeOrderValidator {

	/**
	 * default constructor
	 */
	protected TradeOrderValidator() {
	}


	/**
	 * handles creation validation for a TradeOrder
	 */
	public void validate( CreateTradeOrderCommand tradeOrder )throws ValidationException {
		if ( tradeOrder == null )
			throw new ValidationException( "TradeOrder", "validating CreateTradeOrderCommand" );
		if ( tradeOrder.getOrderId() == null )
			throw new ValidationException( "TradeOrder", "validating access on getOrderId" );
		if ( tradeOrder.getQuantity() == null )
			throw new ValidationException( "TradeOrder", "validating access on getQuantity" );
		if ( tradeOrder.getLimitPrice() == null )
			throw new ValidationException( "TradeOrder", "validating access on getLimitPrice" );
		if ( tradeOrder.getPlacedAt() == null )
			throw new ValidationException( "TradeOrder", "validating access on getPlacedAt" );
	}

	/**
	 * handles update validation for a TradeOrder
	 */
	public void validate( UpdateTradeOrderCommand tradeOrder ) throws ValidationException {
		if ( tradeOrder == null )
			throw new ValidationException( "TradeOrder", "validating UpdateTradeOrderCommand" );
		if ( tradeOrder.getOrderId() == null )
			throw new ValidationException( "TradeOrder", "validating method getOrderId" );
		if ( tradeOrder.getQuantity() == null )
			throw new ValidationException( "TradeOrder", "validating method getQuantity" );
		if ( tradeOrder.getLimitPrice() == null )
			throw new ValidationException( "TradeOrder", "validating method getLimitPrice" );
		if ( tradeOrder.getPlacedAt() == null )
			throw new ValidationException( "TradeOrder", "validating method getPlacedAt" );
	}

/**
 * handles delete validation for a TradeOrder
 */
	public void validate( DeleteTradeOrderCommand tradeOrder ) throws ValidationException {
		if ( tradeOrder == null )
			throw new ValidationException( "TradeOrder", "validating DeleteTradeOrderCommand" );

		if ( tradeOrder.getId() == null )
			throw new ValidationException( "TradeOrder", "validating DeleteTradeOrderCommand identifier discovered as null" );
	}

/**
 * handles fetchOne validation for a TradeOrder
 */
	public void validate( TradeOrderFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "TradeOrder", "validating FetchOneSummary" );

		if ( summary.getId() == null )
			throw new ValidationException( "TradeOrder", "validating FetchOneSummary identifier discovered as null" );
	}

	/**
	 * handles assign Portfolio validation for a TradeOrder
	 *
	 * @param	command AssignPortfolioToTradeOrderCommand
	 */
	public void validate( AssignPortfolioToTradeOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "TradeOrder", "validating AssignPortfolioToTradeOrderCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "TradeOrder", "validating identity on AssignPortfolioToTradeOrderCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Portfolio validation for a TradeOrder
	 *
	 * @param	command UnAssignPortfolioFromTradeOrderCommand
	 */
	public void validate( UnAssignPortfolioFromTradeOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "TradeOrder", "validating UnAssignPortfolioFromTradeOrderCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "TradeOrder", "validating identity on UnAssignPortfolioFromTradeOrderCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	/**
	 * handles assign Security validation for a TradeOrder
	 *
	 * @param	command AssignSecurityToTradeOrderCommand
	 */
	public void validate( AssignSecurityToTradeOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "TradeOrder", "validating AssignSecurityToTradeOrderCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "TradeOrder", "validating identity on AssignSecurityToTradeOrderCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles unassign Security validation for a TradeOrder
	 *
	 * @param	command UnAssignSecurityFromTradeOrderCommand
	 */
	public void validate( UnAssignSecurityFromTradeOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "TradeOrder", "validating UnAssignSecurityFromTradeOrderCommand" );

		if ( command.getParentId() == null || command.getChildId() == null  )
			throw new ValidationException( "TradeOrder", "validating identity on UnAssignSecurityFromTradeOrderCommand parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

	/**
	 * handles add to Trades validation for a TradeOrder
	 *
	 * @param	command AssignTradesToTradeOrderCommand
	 */
	public void validate( AssignTradesToTradeOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "TradeOrder", "validating AssignTradesToTradeOrderCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "TradeOrder", "validating identity on AssignTradesToTradeOrderCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );


	}

	/**
	 * handles remove from Trades validation for a TradeOrder
	 *
	 * @param	command RemoveTradesFromTradeOrderCommand
	 */
	public void validate( RemoveTradesFromTradeOrderCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("TradeOrder", "validating RemoveTradesFromTradeOrderCommand" );

		if ( command.getParentId() == null || command.getChildIds() == null  )
			throw new ValidationException( "TradeOrder", "validating identity on RemoveTradesFromTradeOrderCommand parentId:" + command.getParentId() + ", childIds:" + command.getChildIds() );
	}


}
