
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * AgreementRestController as REST API
 *
 * <p>Exposes REST endpoints for the Agreement entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	AgreementService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateAgreementCommand</li>
 *      <li></li>UpdateAgreementCommand</li>
 *      <liDeleteAgreementCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Agreement")
public class AgreementRestController extends BaseSpringRestController {

	public AgreementRestController( AgreementService service ) {
		this.service = service;
	}
    /**
     * Handles create a Agreement.  if not key provided, calls create, otherwise calls save
     * @param		Agreement	agreement
     * @return		Agreement 
     */
	@PostMapping("/create")
    public Agreement create( @RequestBody(required=true) CreateAgreementCommand command ) {
    	Agreement entity = null;

		entity = service.createAgreement( command );
		LOGGER.info( "Successfully created Agreement with Id " + entity.getAgreementId()  );

		return entity;
    }

    /**
     * Handles updating a Agreement.  if no key provided, calls create, otherwise calls save
     * @param		Agreement agreement
     * @return		Agreement
     */
	@PutMapping("/update")
    public Agreement update( @RequestBody(required=true) UpdateAgreementCommand command ) {
		Agreement entity = null;

		entity = service.updateAgreement(command);
		LOGGER.info( "Successfully updated Agreement with Id " + command.getAgreementId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Agreement entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteAgreementCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Agreement with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Agreement using a UUID
     * @param		UUID uuid 
     * @return		Agreement
     */    
    @GetMapping("/get")
    public Agreement get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Agreement entity = service.getAgreement( new AgreementFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Agreement with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Agreement business objects
     * @return		List<Agreement>
     */
    @GetMapping("/")
    public List<Agreement> getAll() {
    	List<Agreement> agreementList = null;

		agreementList = service.getAllAgreement();
		LOGGER.info( "successfully loaded all Agreements" );

        return agreementList;
                            
    }

	/**
	 * Handles loading all Customer} business objects
	 * @return		List<Agreement>

    @GetMapping("/Customer")
    public List<Agreement> Customer(UUID parentId) {
		List<Agreement> agreementList = load(parentId).getCustomer;
		return agreementList;
	}
	 */
    /**
     * save Customer on Agreement
     * @param		command AssignCustomerToAgreementCommand
     */     
	@PutMapping("/assignCustomer")
	public void assignCustomer( @RequestBody AssignCustomerToAgreementCommand command ) {
		service.assignCustomer( command );
		LOGGER.info( "Successfully assigned Customer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Customer on Agreement
     * @param		 command UnAssignCustomerFromAgreementCommand
     */     
	@PutMapping("/unassignCustomer")
	public void unAssignCustomer( @RequestBody(required=true)  UnAssignCustomerFromAgreementCommand command ) {
		service.unAssignCustomer( command );
		LOGGER.info( "Successfully unassigned Customer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all ProductOffering} business objects
	 * @return		List<Agreement>

    @GetMapping("/ProductOffering")
    public List<Agreement> ProductOffering(UUID parentId) {
		List<Agreement> agreementList = load(parentId).getProductOffering;
		return agreementList;
	}
	 */
    /**
     * save ProductOffering on Agreement
     * @param		command AssignProductOfferingToAgreementCommand
     */     
	@PutMapping("/assignProductOffering")
	public void assignProductOffering( @RequestBody AssignProductOfferingToAgreementCommand command ) {
		service.assignProductOffering( command );
		LOGGER.info( "Successfully assigned ProductOffering with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign ProductOffering on Agreement
     * @param		 command UnAssignProductOfferingFromAgreementCommand
     */     
	@PutMapping("/unassignProductOffering")
	public void unAssignProductOffering( @RequestBody(required=true)  UnAssignProductOfferingFromAgreementCommand command ) {
		service.unAssignProductOffering( command );
		LOGGER.info( "Successfully unassigned ProductOffering with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Agreement agreement = null;
	protected AgreementService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(AgreementRestController.class.getName());
    
}
