
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * CollateralRestController as REST API
 *
 * <p>Exposes REST endpoints for the Collateral entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	CollateralService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateCollateralCommand</li>
 *      <li></li>UpdateCollateralCommand</li>
 *      <liDeleteCollateralCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Collateral")
public class CollateralRestController extends BaseSpringRestController {

	public CollateralRestController( CollateralService service ) {
		this.service = service;
	}
    /**
     * Handles create a Collateral.  if not key provided, calls create, otherwise calls save
     * @param		Collateral	collateral
     * @return		Collateral 
     */
	@PostMapping("/create")
    public Collateral create( @RequestBody(required=true) CreateCollateralCommand command ) {
    	Collateral entity = null;

		entity = service.createCollateral( command );
		LOGGER.info( "Successfully created Collateral with Id " + entity.getCollateralId()  );

		return entity;
    }

    /**
     * Handles updating a Collateral.  if no key provided, calls create, otherwise calls save
     * @param		Collateral collateral
     * @return		Collateral
     */
	@PutMapping("/update")
    public Collateral update( @RequestBody(required=true) UpdateCollateralCommand command ) {
		Collateral entity = null;

		entity = service.updateCollateral(command);
		LOGGER.info( "Successfully updated Collateral with Id " + command.getCollateralId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Collateral entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteCollateralCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Collateral with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Collateral using a UUID
     * @param		UUID uuid 
     * @return		Collateral
     */    
    @GetMapping("/get")
    public Collateral get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Collateral entity = service.getCollateral( new CollateralFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Collateral with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Collateral business objects
     * @return		List<Collateral>
     */
    @GetMapping("/")
    public List<Collateral> getAll() {
    	List<Collateral> collateralList = null;

		collateralList = service.getAllCollateral();
		LOGGER.info( "successfully loaded all Collaterals" );

        return collateralList;
                            
    }

	/**
	 * Handles loading all Loan} business objects
	 * @return		List<Collateral>

    @GetMapping("/Loan")
    public List<Collateral> Loan(UUID parentId) {
		List<Collateral> collateralList = load(parentId).getLoan;
		return collateralList;
	}
	 */
    /**
     * save Loan on Collateral
     * @param		command AssignLoanToCollateralCommand
     */     
	@PutMapping("/assignLoan")
	public void assignLoan( @RequestBody AssignLoanToCollateralCommand command ) {
		service.assignLoan( command );
		LOGGER.info( "Successfully assigned Loan with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Loan on Collateral
     * @param		 command UnAssignLoanFromCollateralCommand
     */     
	@PutMapping("/unassignLoan")
	public void unAssignLoan( @RequestBody(required=true)  UnAssignLoanFromCollateralCommand command ) {
		service.unAssignLoan( command );
		LOGGER.info( "Successfully unassigned Loan with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Collateral collateral = null;
	protected CollateralService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(CollateralRestController.class.getName());
    
}
