
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * ComplianceAlertRestController as REST API
 *
 * <p>Exposes REST endpoints for the ComplianceAlert entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	ComplianceAlertService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateComplianceAlertCommand</li>
 *      <li></li>UpdateComplianceAlertCommand</li>
 *      <liDeleteComplianceAlertCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/ComplianceAlert")
public class ComplianceAlertRestController extends BaseSpringRestController {

	public ComplianceAlertRestController( ComplianceAlertService service ) {
		this.service = service;
	}
    /**
     * Handles create a ComplianceAlert.  if not key provided, calls create, otherwise calls save
     * @param		ComplianceAlert	complianceAlert
     * @return		ComplianceAlert 
     */
	@PostMapping("/create")
    public ComplianceAlert create( @RequestBody(required=true) CreateComplianceAlertCommand command ) {
    	ComplianceAlert entity = null;

		entity = service.createComplianceAlert( command );
		LOGGER.info( "Successfully created ComplianceAlert with Id " + entity.getComplianceAlertId()  );

		return entity;
    }

    /**
     * Handles updating a ComplianceAlert.  if no key provided, calls create, otherwise calls save
     * @param		ComplianceAlert complianceAlert
     * @return		ComplianceAlert
     */
	@PutMapping("/update")
    public ComplianceAlert update( @RequestBody(required=true) UpdateComplianceAlertCommand command ) {
		ComplianceAlert entity = null;

		entity = service.updateComplianceAlert(command);
		LOGGER.info( "Successfully updated ComplianceAlert with Id " + command.getComplianceAlertId()  );

		return entity;
	}
 
    /**
     * Handles deleting a ComplianceAlert entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteComplianceAlertCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted ComplianceAlert with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a ComplianceAlert using a UUID
     * @param		UUID uuid 
     * @return		ComplianceAlert
     */    
    @GetMapping("/get")
    public ComplianceAlert get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	ComplianceAlert entity = service.getComplianceAlert( new ComplianceAlertFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded ComplianceAlert with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all ComplianceAlert business objects
     * @return		List<ComplianceAlert>
     */
    @GetMapping("/")
    public List<ComplianceAlert> getAll() {
    	List<ComplianceAlert> complianceAlertList = null;

		complianceAlertList = service.getAllComplianceAlert();
		LOGGER.info( "successfully loaded all ComplianceAlerts" );

        return complianceAlertList;
                            
    }

	/**
	 * Handles loading all Screening} business objects
	 * @return		List<ComplianceAlert>

    @GetMapping("/Screening")
    public List<ComplianceAlert> Screening(UUID parentId) {
		List<ComplianceAlert> complianceAlertList = load(parentId).getScreening;
		return complianceAlertList;
	}
	 */
    /**
     * save Screening on ComplianceAlert
     * @param		command AssignScreeningToComplianceAlertCommand
     */     
	@PutMapping("/assignScreening")
	public void assignScreening( @RequestBody AssignScreeningToComplianceAlertCommand command ) {
		service.assignScreening( command );
		LOGGER.info( "Successfully assigned Screening with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Screening on ComplianceAlert
     * @param		 command UnAssignScreeningFromComplianceAlertCommand
     */     
	@PutMapping("/unassignScreening")
	public void unAssignScreening( @RequestBody(required=true)  UnAssignScreeningFromComplianceAlertCommand command ) {
		service.unAssignScreening( command );
		LOGGER.info( "Successfully unassigned Screening with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Transaction} business objects
	 * @return		List<ComplianceAlert>

    @GetMapping("/Transaction")
    public List<ComplianceAlert> Transaction(UUID parentId) {
		List<ComplianceAlert> complianceAlertList = load(parentId).getTransaction;
		return complianceAlertList;
	}
	 */
    /**
     * save Transaction on ComplianceAlert
     * @param		command AssignTransactionToComplianceAlertCommand
     */     
	@PutMapping("/assignTransaction")
	public void assignTransaction( @RequestBody AssignTransactionToComplianceAlertCommand command ) {
		service.assignTransaction( command );
		LOGGER.info( "Successfully assigned Transaction with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Transaction on ComplianceAlert
     * @param		 command UnAssignTransactionFromComplianceAlertCommand
     */     
	@PutMapping("/unassignTransaction")
	public void unAssignTransaction( @RequestBody(required=true)  UnAssignTransactionFromComplianceAlertCommand command ) {
		service.unAssignTransaction( command );
		LOGGER.info( "Successfully unassigned Transaction with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected ComplianceAlert complianceAlert = null;
	protected ComplianceAlertService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(ComplianceAlertRestController.class.getName());
    
}
