
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * ConsentRestController as REST API
 *
 * <p>Exposes REST endpoints for the Consent entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	ConsentService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateConsentCommand</li>
 *      <li></li>UpdateConsentCommand</li>
 *      <liDeleteConsentCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Consent")
public class ConsentRestController extends BaseSpringRestController {

	public ConsentRestController( ConsentService service ) {
		this.service = service;
	}
    /**
     * Handles create a Consent.  if not key provided, calls create, otherwise calls save
     * @param		Consent	consent
     * @return		Consent 
     */
	@PostMapping("/create")
    public Consent create( @RequestBody(required=true) CreateConsentCommand command ) {
    	Consent entity = null;

		entity = service.createConsent( command );
		LOGGER.info( "Successfully created Consent with Id " + entity.getConsentId()  );

		return entity;
    }

    /**
     * Handles updating a Consent.  if no key provided, calls create, otherwise calls save
     * @param		Consent consent
     * @return		Consent
     */
	@PutMapping("/update")
    public Consent update( @RequestBody(required=true) UpdateConsentCommand command ) {
		Consent entity = null;

		entity = service.updateConsent(command);
		LOGGER.info( "Successfully updated Consent with Id " + command.getConsentId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Consent entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteConsentCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Consent with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Consent using a UUID
     * @param		UUID uuid 
     * @return		Consent
     */    
    @GetMapping("/get")
    public Consent get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Consent entity = service.getConsent( new ConsentFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Consent with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Consent business objects
     * @return		List<Consent>
     */
    @GetMapping("/")
    public List<Consent> getAll() {
    	List<Consent> consentList = null;

		consentList = service.getAllConsent();
		LOGGER.info( "successfully loaded all Consents" );

        return consentList;
                            
    }

	/**
	 * Handles loading all Customer} business objects
	 * @return		List<Consent>

    @GetMapping("/Customer")
    public List<Consent> Customer(UUID parentId) {
		List<Consent> consentList = load(parentId).getCustomer;
		return consentList;
	}
	 */
    /**
     * save Customer on Consent
     * @param		command AssignCustomerToConsentCommand
     */     
	@PutMapping("/assignCustomer")
	public void assignCustomer( @RequestBody AssignCustomerToConsentCommand command ) {
		service.assignCustomer( command );
		LOGGER.info( "Successfully assigned Customer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Customer on Consent
     * @param		 command UnAssignCustomerFromConsentCommand
     */     
	@PutMapping("/unassignCustomer")
	public void unAssignCustomer( @RequestBody(required=true)  UnAssignCustomerFromConsentCommand command ) {
		service.unAssignCustomer( command );
		LOGGER.info( "Successfully unassigned Customer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all ApiClient} business objects
	 * @return		List<Consent>

    @GetMapping("/ApiClient")
    public List<Consent> ApiClient(UUID parentId) {
		List<Consent> consentList = load(parentId).getApiClient;
		return consentList;
	}
	 */
    /**
     * save ApiClient on Consent
     * @param		command AssignApiClientToConsentCommand
     */     
	@PutMapping("/assignApiClient")
	public void assignApiClient( @RequestBody AssignApiClientToConsentCommand command ) {
		service.assignApiClient( command );
		LOGGER.info( "Successfully assigned ApiClient with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign ApiClient on Consent
     * @param		 command UnAssignApiClientFromConsentCommand
     */     
	@PutMapping("/unassignApiClient")
	public void unAssignApiClient( @RequestBody(required=true)  UnAssignApiClientFromConsentCommand command ) {
		service.unAssignApiClient( command );
		LOGGER.info( "Successfully unassigned ApiClient with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Consent consent = null;
	protected ConsentService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(ConsentRestController.class.getName());
    
}
