
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * CustomerRestController as REST API
 *
 * <p>Exposes REST endpoints for the Customer entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	CustomerService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateCustomerCommand</li>
 *      <li></li>UpdateCustomerCommand</li>
 *      <liDeleteCustomerCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Customer")
public class CustomerRestController extends BaseSpringRestController {

	public CustomerRestController( CustomerService service ) {
		this.service = service;
	}
    /**
     * Handles create a Customer.  if not key provided, calls create, otherwise calls save
     * @param		Customer	customer
     * @return		Customer 
     */
	@PostMapping("/create")
    public Customer create( @RequestBody(required=true) CreateCustomerCommand command ) {
    	Customer entity = null;

		entity = service.createCustomer( command );
		LOGGER.info( "Successfully created Customer with Id " + entity.getCustomerId()  );

		return entity;
    }

    /**
     * Handles updating a Customer.  if no key provided, calls create, otherwise calls save
     * @param		Customer customer
     * @return		Customer
     */
	@PutMapping("/update")
    public Customer update( @RequestBody(required=true) UpdateCustomerCommand command ) {
		Customer entity = null;

		entity = service.updateCustomer(command);
		LOGGER.info( "Successfully updated Customer with Id " + command.getCustomerId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Customer entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteCustomerCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Customer with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Customer using a UUID
     * @param		UUID uuid 
     * @return		Customer
     */    
    @GetMapping("/get")
    public Customer get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Customer entity = service.getCustomer( new CustomerFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Customer with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Customer business objects
     * @return		List<Customer>
     */
    @GetMapping("/")
    public List<Customer> getAll() {
    	List<Customer> customerList = null;

		customerList = service.getAllCustomer();
		LOGGER.info( "successfully loaded all Customers" );

        return customerList;
                            
    }

	/**
	 * Handles loading all Institution} business objects
	 * @return		List<Customer>

    @GetMapping("/Institution")
    public List<Customer> Institution(UUID parentId) {
		List<Customer> customerList = load(parentId).getInstitution;
		return customerList;
	}
	 */
    /**
     * save Institution on Customer
     * @param		command AssignInstitutionToCustomerCommand
     */     
	@PutMapping("/assignInstitution")
	public void assignInstitution( @RequestBody AssignInstitutionToCustomerCommand command ) {
		service.assignInstitution( command );
		LOGGER.info( "Successfully assigned Institution with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Institution on Customer
     * @param		 command UnAssignInstitutionFromCustomerCommand
     */     
	@PutMapping("/unassignInstitution")
	public void unAssignInstitution( @RequestBody(required=true)  UnAssignInstitutionFromCustomerCommand command ) {
		service.unAssignInstitution( command );
		LOGGER.info( "Successfully unassigned Institution with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Accounts} business objects
	 * @return		List<Customer>

    @GetMapping("/Accounts")
    public List<Customer> Accounts(UUID parentId) {
		List<Customer> customerList = load(parentId).getAccounts;
		return customerList;
	}

    /**
     * save Accounts on Customer
     * @param		command AssignAccountsToCustomerCommand
     */     
	@PutMapping("/addToAccounts")
	public void addToAccounts( @RequestBody(required=true) AssignAccountsToCustomerCommand command ) {
		service.addToAccounts( command );
		LOGGER.info( "Successfully added Accounts with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Accounts on Customer
     * @param		command RemoveAccountsFromCustomerCommand
     */     	
	@PutMapping("/removeFromAccounts")
	public void removeFromAccounts( 	@RequestBody(required=true) RemoveAccountsFromCustomerCommand command )
	{		
		service.removeFromAccounts( command );
		LOGGER.info( "Successfully removed Accounts with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Wallets} business objects
	 * @return		List<Customer>

    @GetMapping("/Wallets")
    public List<Customer> Wallets(UUID parentId) {
		List<Customer> customerList = load(parentId).getWallets;
		return customerList;
	}

    /**
     * save Wallets on Customer
     * @param		command AssignWalletsToCustomerCommand
     */     
	@PutMapping("/addToWallets")
	public void addToWallets( @RequestBody(required=true) AssignWalletsToCustomerCommand command ) {
		service.addToWallets( command );
		LOGGER.info( "Successfully added Wallets with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Wallets on Customer
     * @param		command RemoveWalletsFromCustomerCommand
     */     	
	@PutMapping("/removeFromWallets")
	public void removeFromWallets( 	@RequestBody(required=true) RemoveWalletsFromCustomerCommand command )
	{		
		service.removeFromWallets( command );
		LOGGER.info( "Successfully removed Wallets with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Cards} business objects
	 * @return		List<Customer>

    @GetMapping("/Cards")
    public List<Customer> Cards(UUID parentId) {
		List<Customer> customerList = load(parentId).getCards;
		return customerList;
	}

    /**
     * save Cards on Customer
     * @param		command AssignCardsToCustomerCommand
     */     
	@PutMapping("/addToCards")
	public void addToCards( @RequestBody(required=true) AssignCardsToCustomerCommand command ) {
		service.addToCards( command );
		LOGGER.info( "Successfully added Cards with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Cards on Customer
     * @param		command RemoveCardsFromCustomerCommand
     */     	
	@PutMapping("/removeFromCards")
	public void removeFromCards( 	@RequestBody(required=true) RemoveCardsFromCustomerCommand command )
	{		
		service.removeFromCards( command );
		LOGGER.info( "Successfully removed Cards with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all KycProfiles} business objects
	 * @return		List<Customer>

    @GetMapping("/KycProfiles")
    public List<Customer> KycProfiles(UUID parentId) {
		List<Customer> customerList = load(parentId).getKycProfiles;
		return customerList;
	}

    /**
     * save KycProfiles on Customer
     * @param		command AssignKycProfilesToCustomerCommand
     */     
	@PutMapping("/addToKycProfiles")
	public void addToKycProfiles( @RequestBody(required=true) AssignKycProfilesToCustomerCommand command ) {
		service.addToKycProfiles( command );
		LOGGER.info( "Successfully added KycProfiles with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove KycProfiles on Customer
     * @param		command RemoveKycProfilesFromCustomerCommand
     */     	
	@PutMapping("/removeFromKycProfiles")
	public void removeFromKycProfiles( 	@RequestBody(required=true) RemoveKycProfilesFromCustomerCommand command )
	{		
		service.removeFromKycProfiles( command );
		LOGGER.info( "Successfully removed KycProfiles with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Consents} business objects
	 * @return		List<Customer>

    @GetMapping("/Consents")
    public List<Customer> Consents(UUID parentId) {
		List<Customer> customerList = load(parentId).getConsents;
		return customerList;
	}

    /**
     * save Consents on Customer
     * @param		command AssignConsentsToCustomerCommand
     */     
	@PutMapping("/addToConsents")
	public void addToConsents( @RequestBody(required=true) AssignConsentsToCustomerCommand command ) {
		service.addToConsents( command );
		LOGGER.info( "Successfully added Consents with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Consents on Customer
     * @param		command RemoveConsentsFromCustomerCommand
     */     	
	@PutMapping("/removeFromConsents")
	public void removeFromConsents( 	@RequestBody(required=true) RemoveConsentsFromCustomerCommand command )
	{		
		service.removeFromConsents( command );
		LOGGER.info( "Successfully removed Consents with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Agreements} business objects
	 * @return		List<Customer>

    @GetMapping("/Agreements")
    public List<Customer> Agreements(UUID parentId) {
		List<Customer> customerList = load(parentId).getAgreements;
		return customerList;
	}

    /**
     * save Agreements on Customer
     * @param		command AssignAgreementsToCustomerCommand
     */     
	@PutMapping("/addToAgreements")
	public void addToAgreements( @RequestBody(required=true) AssignAgreementsToCustomerCommand command ) {
		service.addToAgreements( command );
		LOGGER.info( "Successfully added Agreements with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Agreements on Customer
     * @param		command RemoveAgreementsFromCustomerCommand
     */     	
	@PutMapping("/removeFromAgreements")
	public void removeFromAgreements( 	@RequestBody(required=true) RemoveAgreementsFromCustomerCommand command )
	{		
		service.removeFromAgreements( command );
		LOGGER.info( "Successfully removed Agreements with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all LoanApplications} business objects
	 * @return		List<Customer>

    @GetMapping("/LoanApplications")
    public List<Customer> LoanApplications(UUID parentId) {
		List<Customer> customerList = load(parentId).getLoanApplications;
		return customerList;
	}

    /**
     * save LoanApplications on Customer
     * @param		command AssignLoanApplicationsToCustomerCommand
     */     
	@PutMapping("/addToLoanApplications")
	public void addToLoanApplications( @RequestBody(required=true) AssignLoanApplicationsToCustomerCommand command ) {
		service.addToLoanApplications( command );
		LOGGER.info( "Successfully added LoanApplications with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove LoanApplications on Customer
     * @param		command RemoveLoanApplicationsFromCustomerCommand
     */     	
	@PutMapping("/removeFromLoanApplications")
	public void removeFromLoanApplications( 	@RequestBody(required=true) RemoveLoanApplicationsFromCustomerCommand command )
	{		
		service.removeFromLoanApplications( command );
		LOGGER.info( "Successfully removed LoanApplications with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Loans} business objects
	 * @return		List<Customer>

    @GetMapping("/Loans")
    public List<Customer> Loans(UUID parentId) {
		List<Customer> customerList = load(parentId).getLoans;
		return customerList;
	}

    /**
     * save Loans on Customer
     * @param		command AssignLoansToCustomerCommand
     */     
	@PutMapping("/addToLoans")
	public void addToLoans( @RequestBody(required=true) AssignLoansToCustomerCommand command ) {
		service.addToLoans( command );
		LOGGER.info( "Successfully added Loans with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Loans on Customer
     * @param		command RemoveLoansFromCustomerCommand
     */     	
	@PutMapping("/removeFromLoans")
	public void removeFromLoans( 	@RequestBody(required=true) RemoveLoansFromCustomerCommand command )
	{		
		service.removeFromLoans( command );
		LOGGER.info( "Successfully removed Loans with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Portfolios} business objects
	 * @return		List<Customer>

    @GetMapping("/Portfolios")
    public List<Customer> Portfolios(UUID parentId) {
		List<Customer> customerList = load(parentId).getPortfolios;
		return customerList;
	}

    /**
     * save Portfolios on Customer
     * @param		command AssignPortfoliosToCustomerCommand
     */     
	@PutMapping("/addToPortfolios")
	public void addToPortfolios( @RequestBody(required=true) AssignPortfoliosToCustomerCommand command ) {
		service.addToPortfolios( command );
		LOGGER.info( "Successfully added Portfolios with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Portfolios on Customer
     * @param		command RemovePortfoliosFromCustomerCommand
     */     	
	@PutMapping("/removeFromPortfolios")
	public void removeFromPortfolios( 	@RequestBody(required=true) RemovePortfoliosFromCustomerCommand command )
	{		
		service.removeFromPortfolios( command );
		LOGGER.info( "Successfully removed Portfolios with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Disputes} business objects
	 * @return		List<Customer>

    @GetMapping("/Disputes")
    public List<Customer> Disputes(UUID parentId) {
		List<Customer> customerList = load(parentId).getDisputes;
		return customerList;
	}

    /**
     * save Disputes on Customer
     * @param		command AssignDisputesToCustomerCommand
     */     
	@PutMapping("/addToDisputes")
	public void addToDisputes( @RequestBody(required=true) AssignDisputesToCustomerCommand command ) {
		service.addToDisputes( command );
		LOGGER.info( "Successfully added Disputes with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Disputes on Customer
     * @param		command RemoveDisputesFromCustomerCommand
     */     	
	@PutMapping("/removeFromDisputes")
	public void removeFromDisputes( 	@RequestBody(required=true) RemoveDisputesFromCustomerCommand command )
	{		
		service.removeFromDisputes( command );
		LOGGER.info( "Successfully removed Disputes with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Customer customer = null;
	protected CustomerService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(CustomerRestController.class.getName());
    
}
