
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * InvestmentPortfolioRestController as REST API
 *
 * <p>Exposes REST endpoints for the InvestmentPortfolio entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	InvestmentPortfolioService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateInvestmentPortfolioCommand</li>
 *      <li></li>UpdateInvestmentPortfolioCommand</li>
 *      <liDeleteInvestmentPortfolioCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/InvestmentPortfolio")
public class InvestmentPortfolioRestController extends BaseSpringRestController {

	public InvestmentPortfolioRestController( InvestmentPortfolioService service ) {
		this.service = service;
	}
    /**
     * Handles create a InvestmentPortfolio.  if not key provided, calls create, otherwise calls save
     * @param		InvestmentPortfolio	investmentPortfolio
     * @return		InvestmentPortfolio 
     */
	@PostMapping("/create")
    public InvestmentPortfolio create( @RequestBody(required=true) CreateInvestmentPortfolioCommand command ) {
    	InvestmentPortfolio entity = null;

		entity = service.createInvestmentPortfolio( command );
		LOGGER.info( "Successfully created InvestmentPortfolio with Id " + entity.getInvestmentPortfolioId()  );

		return entity;
    }

    /**
     * Handles updating a InvestmentPortfolio.  if no key provided, calls create, otherwise calls save
     * @param		InvestmentPortfolio investmentPortfolio
     * @return		InvestmentPortfolio
     */
	@PutMapping("/update")
    public InvestmentPortfolio update( @RequestBody(required=true) UpdateInvestmentPortfolioCommand command ) {
		InvestmentPortfolio entity = null;

		entity = service.updateInvestmentPortfolio(command);
		LOGGER.info( "Successfully updated InvestmentPortfolio with Id " + command.getInvestmentPortfolioId()  );

		return entity;
	}
 
    /**
     * Handles deleting a InvestmentPortfolio entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteInvestmentPortfolioCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted InvestmentPortfolio with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a InvestmentPortfolio using a UUID
     * @param		UUID uuid 
     * @return		InvestmentPortfolio
     */    
    @GetMapping("/get")
    public InvestmentPortfolio get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	InvestmentPortfolio entity = service.getInvestmentPortfolio( new InvestmentPortfolioFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded InvestmentPortfolio with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all InvestmentPortfolio business objects
     * @return		List<InvestmentPortfolio>
     */
    @GetMapping("/")
    public List<InvestmentPortfolio> getAll() {
    	List<InvestmentPortfolio> investmentPortfolioList = null;

		investmentPortfolioList = service.getAllInvestmentPortfolio();
		LOGGER.info( "successfully loaded all InvestmentPortfolios" );

        return investmentPortfolioList;
                            
    }

	/**
	 * Handles loading all Customer} business objects
	 * @return		List<InvestmentPortfolio>

    @GetMapping("/Customer")
    public List<InvestmentPortfolio> Customer(UUID parentId) {
		List<InvestmentPortfolio> investmentPortfolioList = load(parentId).getCustomer;
		return investmentPortfolioList;
	}
	 */
    /**
     * save Customer on InvestmentPortfolio
     * @param		command AssignCustomerToInvestmentPortfolioCommand
     */     
	@PutMapping("/assignCustomer")
	public void assignCustomer( @RequestBody AssignCustomerToInvestmentPortfolioCommand command ) {
		service.assignCustomer( command );
		LOGGER.info( "Successfully assigned Customer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Customer on InvestmentPortfolio
     * @param		 command UnAssignCustomerFromInvestmentPortfolioCommand
     */     
	@PutMapping("/unassignCustomer")
	public void unAssignCustomer( @RequestBody(required=true)  UnAssignCustomerFromInvestmentPortfolioCommand command ) {
		service.unAssignCustomer( command );
		LOGGER.info( "Successfully unassigned Customer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Accounts} business objects
	 * @return		List<InvestmentPortfolio>

    @GetMapping("/Accounts")
    public List<InvestmentPortfolio> Accounts(UUID parentId) {
		List<InvestmentPortfolio> investmentPortfolioList = load(parentId).getAccounts;
		return investmentPortfolioList;
	}

    /**
     * save Accounts on InvestmentPortfolio
     * @param		command AssignAccountsToInvestmentPortfolioCommand
     */     
	@PutMapping("/addToAccounts")
	public void addToAccounts( @RequestBody(required=true) AssignAccountsToInvestmentPortfolioCommand command ) {
		service.addToAccounts( command );
		LOGGER.info( "Successfully added Accounts with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Accounts on InvestmentPortfolio
     * @param		command RemoveAccountsFromInvestmentPortfolioCommand
     */     	
	@PutMapping("/removeFromAccounts")
	public void removeFromAccounts( 	@RequestBody(required=true) RemoveAccountsFromInvestmentPortfolioCommand command )
	{		
		service.removeFromAccounts( command );
		LOGGER.info( "Successfully removed Accounts with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Orders} business objects
	 * @return		List<InvestmentPortfolio>

    @GetMapping("/Orders")
    public List<InvestmentPortfolio> Orders(UUID parentId) {
		List<InvestmentPortfolio> investmentPortfolioList = load(parentId).getOrders;
		return investmentPortfolioList;
	}

    /**
     * save Orders on InvestmentPortfolio
     * @param		command AssignOrdersToInvestmentPortfolioCommand
     */     
	@PutMapping("/addToOrders")
	public void addToOrders( @RequestBody(required=true) AssignOrdersToInvestmentPortfolioCommand command ) {
		service.addToOrders( command );
		LOGGER.info( "Successfully added Orders with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Orders on InvestmentPortfolio
     * @param		command RemoveOrdersFromInvestmentPortfolioCommand
     */     	
	@PutMapping("/removeFromOrders")
	public void removeFromOrders( 	@RequestBody(required=true) RemoveOrdersFromInvestmentPortfolioCommand command )
	{		
		service.removeFromOrders( command );
		LOGGER.info( "Successfully removed Orders with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Holdings} business objects
	 * @return		List<InvestmentPortfolio>

    @GetMapping("/Holdings")
    public List<InvestmentPortfolio> Holdings(UUID parentId) {
		List<InvestmentPortfolio> investmentPortfolioList = load(parentId).getHoldings;
		return investmentPortfolioList;
	}

    /**
     * save Holdings on InvestmentPortfolio
     * @param		command AssignHoldingsToInvestmentPortfolioCommand
     */     
	@PutMapping("/addToHoldings")
	public void addToHoldings( @RequestBody(required=true) AssignHoldingsToInvestmentPortfolioCommand command ) {
		service.addToHoldings( command );
		LOGGER.info( "Successfully added Holdings with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Holdings on InvestmentPortfolio
     * @param		command RemoveHoldingsFromInvestmentPortfolioCommand
     */     	
	@PutMapping("/removeFromHoldings")
	public void removeFromHoldings( 	@RequestBody(required=true) RemoveHoldingsFromInvestmentPortfolioCommand command )
	{		
		service.removeFromHoldings( command );
		LOGGER.info( "Successfully removed Holdings with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected InvestmentPortfolio investmentPortfolio = null;
	protected InvestmentPortfolioService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(InvestmentPortfolioRestController.class.getName());
    
}
