
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * InvestmentAccountRestController as REST API
 *
 * <p>Exposes REST endpoints for the InvestmentAccount entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	InvestmentAccountService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateInvestmentAccountCommand</li>
 *      <li></li>UpdateInvestmentAccountCommand</li>
 *      <liDeleteInvestmentAccountCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/InvestmentAccount")
public class InvestmentAccountRestController extends BaseSpringRestController {

	public InvestmentAccountRestController( InvestmentAccountService service ) {
		this.service = service;
	}
    /**
     * Handles create a InvestmentAccount.  if not key provided, calls create, otherwise calls save
     * @param		InvestmentAccount	investmentAccount
     * @return		InvestmentAccount 
     */
	@PostMapping("/create")
    public InvestmentAccount create( @RequestBody(required=true) CreateInvestmentAccountCommand command ) {
    	InvestmentAccount entity = null;

		entity = service.createInvestmentAccount( command );
		LOGGER.info( "Successfully created InvestmentAccount with Id " + entity.getInvestmentAccountId()  );

		return entity;
    }

    /**
     * Handles updating a InvestmentAccount.  if no key provided, calls create, otherwise calls save
     * @param		InvestmentAccount investmentAccount
     * @return		InvestmentAccount
     */
	@PutMapping("/update")
    public InvestmentAccount update( @RequestBody(required=true) UpdateInvestmentAccountCommand command ) {
		InvestmentAccount entity = null;

		entity = service.updateInvestmentAccount(command);
		LOGGER.info( "Successfully updated InvestmentAccount with Id " + command.getInvestmentAccountId()  );

		return entity;
	}
 
    /**
     * Handles deleting a InvestmentAccount entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteInvestmentAccountCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted InvestmentAccount with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a InvestmentAccount using a UUID
     * @param		UUID uuid 
     * @return		InvestmentAccount
     */    
    @GetMapping("/get")
    public InvestmentAccount get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	InvestmentAccount entity = service.getInvestmentAccount( new InvestmentAccountFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded InvestmentAccount with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all InvestmentAccount business objects
     * @return		List<InvestmentAccount>
     */
    @GetMapping("/")
    public List<InvestmentAccount> getAll() {
    	List<InvestmentAccount> investmentAccountList = null;

		investmentAccountList = service.getAllInvestmentAccount();
		LOGGER.info( "successfully loaded all InvestmentAccounts" );

        return investmentAccountList;
                            
    }

	/**
	 * Handles loading all Portfolio} business objects
	 * @return		List<InvestmentAccount>

    @GetMapping("/Portfolio")
    public List<InvestmentAccount> Portfolio(UUID parentId) {
		List<InvestmentAccount> investmentAccountList = load(parentId).getPortfolio;
		return investmentAccountList;
	}
	 */
    /**
     * save Portfolio on InvestmentAccount
     * @param		command AssignPortfolioToInvestmentAccountCommand
     */     
	@PutMapping("/assignPortfolio")
	public void assignPortfolio( @RequestBody AssignPortfolioToInvestmentAccountCommand command ) {
		service.assignPortfolio( command );
		LOGGER.info( "Successfully assigned Portfolio with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Portfolio on InvestmentAccount
     * @param		 command UnAssignPortfolioFromInvestmentAccountCommand
     */     
	@PutMapping("/unassignPortfolio")
	public void unAssignPortfolio( @RequestBody(required=true)  UnAssignPortfolioFromInvestmentAccountCommand command ) {
		service.unAssignPortfolio( command );
		LOGGER.info( "Successfully unassigned Portfolio with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Trades} business objects
	 * @return		List<InvestmentAccount>

    @GetMapping("/Trades")
    public List<InvestmentAccount> Trades(UUID parentId) {
		List<InvestmentAccount> investmentAccountList = load(parentId).getTrades;
		return investmentAccountList;
	}

    /**
     * save Trades on InvestmentAccount
     * @param		command AssignTradesToInvestmentAccountCommand
     */     
	@PutMapping("/addToTrades")
	public void addToTrades( @RequestBody(required=true) AssignTradesToInvestmentAccountCommand command ) {
		service.addToTrades( command );
		LOGGER.info( "Successfully added Trades with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Trades on InvestmentAccount
     * @param		command RemoveTradesFromInvestmentAccountCommand
     */     	
	@PutMapping("/removeFromTrades")
	public void removeFromTrades( 	@RequestBody(required=true) RemoveTradesFromInvestmentAccountCommand command )
	{		
		service.removeFromTrades( command );
		LOGGER.info( "Successfully removed Trades with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Orders} business objects
	 * @return		List<InvestmentAccount>

    @GetMapping("/Orders")
    public List<InvestmentAccount> Orders(UUID parentId) {
		List<InvestmentAccount> investmentAccountList = load(parentId).getOrders;
		return investmentAccountList;
	}

    /**
     * save Orders on InvestmentAccount
     * @param		command AssignOrdersToInvestmentAccountCommand
     */     
	@PutMapping("/addToOrders")
	public void addToOrders( @RequestBody(required=true) AssignOrdersToInvestmentAccountCommand command ) {
		service.addToOrders( command );
		LOGGER.info( "Successfully added Orders with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Orders on InvestmentAccount
     * @param		command RemoveOrdersFromInvestmentAccountCommand
     */     	
	@PutMapping("/removeFromOrders")
	public void removeFromOrders( 	@RequestBody(required=true) RemoveOrdersFromInvestmentAccountCommand command )
	{		
		service.removeFromOrders( command );
		LOGGER.info( "Successfully removed Orders with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected InvestmentAccount investmentAccount = null;
	protected InvestmentAccountService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(InvestmentAccountRestController.class.getName());
    
}
