
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * KYCProfileRestController as REST API
 *
 * <p>Exposes REST endpoints for the KYCProfile entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	KYCProfileService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateKYCProfileCommand</li>
 *      <li></li>UpdateKYCProfileCommand</li>
 *      <liDeleteKYCProfileCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/KYCProfile")
public class KYCProfileRestController extends BaseSpringRestController {

	public KYCProfileRestController( KYCProfileService service ) {
		this.service = service;
	}
    /**
     * Handles create a KYCProfile.  if not key provided, calls create, otherwise calls save
     * @param		KYCProfile	kYCProfile
     * @return		KYCProfile 
     */
	@PostMapping("/create")
    public KYCProfile create( @RequestBody(required=true) CreateKYCProfileCommand command ) {
    	KYCProfile entity = null;

		entity = service.createKYCProfile( command );
		LOGGER.info( "Successfully created KYCProfile with Id " + entity.getKYCProfileId()  );

		return entity;
    }

    /**
     * Handles updating a KYCProfile.  if no key provided, calls create, otherwise calls save
     * @param		KYCProfile kYCProfile
     * @return		KYCProfile
     */
	@PutMapping("/update")
    public KYCProfile update( @RequestBody(required=true) UpdateKYCProfileCommand command ) {
		KYCProfile entity = null;

		entity = service.updateKYCProfile(command);
		LOGGER.info( "Successfully updated KYCProfile with Id " + command.getKYCProfileId()  );

		return entity;
	}
 
    /**
     * Handles deleting a KYCProfile entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteKYCProfileCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted KYCProfile with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a KYCProfile using a UUID
     * @param		UUID uuid 
     * @return		KYCProfile
     */    
    @GetMapping("/get")
    public KYCProfile get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	KYCProfile entity = service.getKYCProfile( new KYCProfileFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded KYCProfile with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all KYCProfile business objects
     * @return		List<KYCProfile>
     */
    @GetMapping("/")
    public List<KYCProfile> getAll() {
    	List<KYCProfile> kYCProfileList = null;

		kYCProfileList = service.getAllKYCProfile();
		LOGGER.info( "successfully loaded all KYCProfiles" );

        return kYCProfileList;
                            
    }

	/**
	 * Handles loading all Customer} business objects
	 * @return		List<KYCProfile>

    @GetMapping("/Customer")
    public List<KYCProfile> Customer(UUID parentId) {
		List<KYCProfile> kYCProfileList = load(parentId).getCustomer;
		return kYCProfileList;
	}
	 */
    /**
     * save Customer on KYCProfile
     * @param		command AssignCustomerToKYCProfileCommand
     */     
	@PutMapping("/assignCustomer")
	public void assignCustomer( @RequestBody AssignCustomerToKYCProfileCommand command ) {
		service.assignCustomer( command );
		LOGGER.info( "Successfully assigned Customer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Customer on KYCProfile
     * @param		 command UnAssignCustomerFromKYCProfileCommand
     */     
	@PutMapping("/unassignCustomer")
	public void unAssignCustomer( @RequestBody(required=true)  UnAssignCustomerFromKYCProfileCommand command ) {
		service.unAssignCustomer( command );
		LOGGER.info( "Successfully unassigned Customer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Documents} business objects
	 * @return		List<KYCProfile>

    @GetMapping("/Documents")
    public List<KYCProfile> Documents(UUID parentId) {
		List<KYCProfile> kYCProfileList = load(parentId).getDocuments;
		return kYCProfileList;
	}

    /**
     * save Documents on KYCProfile
     * @param		command AssignDocumentsToKYCProfileCommand
     */     
	@PutMapping("/addToDocuments")
	public void addToDocuments( @RequestBody(required=true) AssignDocumentsToKYCProfileCommand command ) {
		service.addToDocuments( command );
		LOGGER.info( "Successfully added Documents with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Documents on KYCProfile
     * @param		command RemoveDocumentsFromKYCProfileCommand
     */     	
	@PutMapping("/removeFromDocuments")
	public void removeFromDocuments( 	@RequestBody(required=true) RemoveDocumentsFromKYCProfileCommand command )
	{		
		service.removeFromDocuments( command );
		LOGGER.info( "Successfully removed Documents with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Screenings} business objects
	 * @return		List<KYCProfile>

    @GetMapping("/Screenings")
    public List<KYCProfile> Screenings(UUID parentId) {
		List<KYCProfile> kYCProfileList = load(parentId).getScreenings;
		return kYCProfileList;
	}

    /**
     * save Screenings on KYCProfile
     * @param		command AssignScreeningsToKYCProfileCommand
     */     
	@PutMapping("/addToScreenings")
	public void addToScreenings( @RequestBody(required=true) AssignScreeningsToKYCProfileCommand command ) {
		service.addToScreenings( command );
		LOGGER.info( "Successfully added Screenings with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Screenings on KYCProfile
     * @param		command RemoveScreeningsFromKYCProfileCommand
     */     	
	@PutMapping("/removeFromScreenings")
	public void removeFromScreenings( 	@RequestBody(required=true) RemoveScreeningsFromKYCProfileCommand command )
	{		
		service.removeFromScreenings( command );
		LOGGER.info( "Successfully removed Screenings with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Addresses} business objects
	 * @return		List<KYCProfile>

    @GetMapping("/Addresses")
    public List<KYCProfile> Addresses(UUID parentId) {
		List<KYCProfile> kYCProfileList = load(parentId).getAddresses;
		return kYCProfileList;
	}

    /**
     * save Addresses on KYCProfile
     * @param		command AssignAddressesToKYCProfileCommand
     */     
	@PutMapping("/addToAddresses")
	public void addToAddresses( @RequestBody(required=true) AssignAddressesToKYCProfileCommand command ) {
		service.addToAddresses( command );
		LOGGER.info( "Successfully added Addresses with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Addresses on KYCProfile
     * @param		command RemoveAddressesFromKYCProfileCommand
     */     	
	@PutMapping("/removeFromAddresses")
	public void removeFromAddresses( 	@RequestBody(required=true) RemoveAddressesFromKYCProfileCommand command )
	{		
		service.removeFromAddresses( command );
		LOGGER.info( "Successfully removed Addresses with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected KYCProfile kYCProfile = null;
	protected KYCProfileService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(KYCProfileRestController.class.getName());
    
}
