
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * LoanApplicationRestController as REST API
 *
 * <p>Exposes REST endpoints for the LoanApplication entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	LoanApplicationService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateLoanApplicationCommand</li>
 *      <li></li>UpdateLoanApplicationCommand</li>
 *      <liDeleteLoanApplicationCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/LoanApplication")
public class LoanApplicationRestController extends BaseSpringRestController {

	public LoanApplicationRestController( LoanApplicationService service ) {
		this.service = service;
	}
    /**
     * Handles create a LoanApplication.  if not key provided, calls create, otherwise calls save
     * @param		LoanApplication	loanApplication
     * @return		LoanApplication 
     */
	@PostMapping("/create")
    public LoanApplication create( @RequestBody(required=true) CreateLoanApplicationCommand command ) {
    	LoanApplication entity = null;

		entity = service.createLoanApplication( command );
		LOGGER.info( "Successfully created LoanApplication with Id " + entity.getLoanApplicationId()  );

		return entity;
    }

    /**
     * Handles updating a LoanApplication.  if no key provided, calls create, otherwise calls save
     * @param		LoanApplication loanApplication
     * @return		LoanApplication
     */
	@PutMapping("/update")
    public LoanApplication update( @RequestBody(required=true) UpdateLoanApplicationCommand command ) {
		LoanApplication entity = null;

		entity = service.updateLoanApplication(command);
		LOGGER.info( "Successfully updated LoanApplication with Id " + command.getLoanApplicationId()  );

		return entity;
	}
 
    /**
     * Handles deleting a LoanApplication entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteLoanApplicationCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted LoanApplication with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a LoanApplication using a UUID
     * @param		UUID uuid 
     * @return		LoanApplication
     */    
    @GetMapping("/get")
    public LoanApplication get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	LoanApplication entity = service.getLoanApplication( new LoanApplicationFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded LoanApplication with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all LoanApplication business objects
     * @return		List<LoanApplication>
     */
    @GetMapping("/")
    public List<LoanApplication> getAll() {
    	List<LoanApplication> loanApplicationList = null;

		loanApplicationList = service.getAllLoanApplication();
		LOGGER.info( "successfully loaded all LoanApplications" );

        return loanApplicationList;
                            
    }

	/**
	 * Handles loading all Customer} business objects
	 * @return		List<LoanApplication>

    @GetMapping("/Customer")
    public List<LoanApplication> Customer(UUID parentId) {
		List<LoanApplication> loanApplicationList = load(parentId).getCustomer;
		return loanApplicationList;
	}
	 */
    /**
     * save Customer on LoanApplication
     * @param		command AssignCustomerToLoanApplicationCommand
     */     
	@PutMapping("/assignCustomer")
	public void assignCustomer( @RequestBody AssignCustomerToLoanApplicationCommand command ) {
		service.assignCustomer( command );
		LOGGER.info( "Successfully assigned Customer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Customer on LoanApplication
     * @param		 command UnAssignCustomerFromLoanApplicationCommand
     */     
	@PutMapping("/unassignCustomer")
	public void unAssignCustomer( @RequestBody(required=true)  UnAssignCustomerFromLoanApplicationCommand command ) {
		service.unAssignCustomer( command );
		LOGGER.info( "Successfully unassigned Customer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all RiskAssessment} business objects
	 * @return		List<LoanApplication>

    @GetMapping("/RiskAssessment")
    public List<LoanApplication> RiskAssessment(UUID parentId) {
		List<LoanApplication> loanApplicationList = load(parentId).getRiskAssessment;
		return loanApplicationList;
	}
	 */
    /**
     * save RiskAssessment on LoanApplication
     * @param		command AssignRiskAssessmentToLoanApplicationCommand
     */     
	@PutMapping("/assignRiskAssessment")
	public void assignRiskAssessment( @RequestBody AssignRiskAssessmentToLoanApplicationCommand command ) {
		service.assignRiskAssessment( command );
		LOGGER.info( "Successfully assigned RiskAssessment with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign RiskAssessment on LoanApplication
     * @param		 command UnAssignRiskAssessmentFromLoanApplicationCommand
     */     
	@PutMapping("/unassignRiskAssessment")
	public void unAssignRiskAssessment( @RequestBody(required=true)  UnAssignRiskAssessmentFromLoanApplicationCommand command ) {
		service.unAssignRiskAssessment( command );
		LOGGER.info( "Successfully unassigned RiskAssessment with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Loan} business objects
	 * @return		List<LoanApplication>

    @GetMapping("/Loan")
    public List<LoanApplication> Loan(UUID parentId) {
		List<LoanApplication> loanApplicationList = load(parentId).getLoan;
		return loanApplicationList;
	}
	 */
    /**
     * save Loan on LoanApplication
     * @param		command AssignLoanToLoanApplicationCommand
     */     
	@PutMapping("/assignLoan")
	public void assignLoan( @RequestBody AssignLoanToLoanApplicationCommand command ) {
		service.assignLoan( command );
		LOGGER.info( "Successfully assigned Loan with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Loan on LoanApplication
     * @param		 command UnAssignLoanFromLoanApplicationCommand
     */     
	@PutMapping("/unassignLoan")
	public void unAssignLoan( @RequestBody(required=true)  UnAssignLoanFromLoanApplicationCommand command ) {
		service.unAssignLoan( command );
		LOGGER.info( "Successfully unassigned Loan with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected LoanApplication loanApplication = null;
	protected LoanApplicationService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(LoanApplicationRestController.class.getName());
    
}
