
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * MerchantRestController as REST API
 *
 * <p>Exposes REST endpoints for the Merchant entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	MerchantService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateMerchantCommand</li>
 *      <li></li>UpdateMerchantCommand</li>
 *      <liDeleteMerchantCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Merchant")
public class MerchantRestController extends BaseSpringRestController {

	public MerchantRestController( MerchantService service ) {
		this.service = service;
	}
    /**
     * Handles create a Merchant.  if not key provided, calls create, otherwise calls save
     * @param		Merchant	merchant
     * @return		Merchant 
     */
	@PostMapping("/create")
    public Merchant create( @RequestBody(required=true) CreateMerchantCommand command ) {
    	Merchant entity = null;

		entity = service.createMerchant( command );
		LOGGER.info( "Successfully created Merchant with Id " + entity.getMerchantId()  );

		return entity;
    }

    /**
     * Handles updating a Merchant.  if no key provided, calls create, otherwise calls save
     * @param		Merchant merchant
     * @return		Merchant
     */
	@PutMapping("/update")
    public Merchant update( @RequestBody(required=true) UpdateMerchantCommand command ) {
		Merchant entity = null;

		entity = service.updateMerchant(command);
		LOGGER.info( "Successfully updated Merchant with Id " + command.getMerchantId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Merchant entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteMerchantCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Merchant with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Merchant using a UUID
     * @param		UUID uuid 
     * @return		Merchant
     */    
    @GetMapping("/get")
    public Merchant get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Merchant entity = service.getMerchant( new MerchantFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Merchant with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Merchant business objects
     * @return		List<Merchant>
     */
    @GetMapping("/")
    public List<Merchant> getAll() {
    	List<Merchant> merchantList = null;

		merchantList = service.getAllMerchant();
		LOGGER.info( "successfully loaded all Merchants" );

        return merchantList;
                            
    }


	/**
	 * Handles loading all Terminals} business objects
	 * @return		List<Merchant>

    @GetMapping("/Terminals")
    public List<Merchant> Terminals(UUID parentId) {
		List<Merchant> merchantList = load(parentId).getTerminals;
		return merchantList;
	}

    /**
     * save Terminals on Merchant
     * @param		command AssignTerminalsToMerchantCommand
     */     
	@PutMapping("/addToTerminals")
	public void addToTerminals( @RequestBody(required=true) AssignTerminalsToMerchantCommand command ) {
		service.addToTerminals( command );
		LOGGER.info( "Successfully added Terminals with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Terminals on Merchant
     * @param		command RemoveTerminalsFromMerchantCommand
     */     	
	@PutMapping("/removeFromTerminals")
	public void removeFromTerminals( 	@RequestBody(required=true) RemoveTerminalsFromMerchantCommand command )
	{		
		service.removeFromTerminals( command );
		LOGGER.info( "Successfully removed Terminals with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all PaymentContracts} business objects
	 * @return		List<Merchant>

    @GetMapping("/PaymentContracts")
    public List<Merchant> PaymentContracts(UUID parentId) {
		List<Merchant> merchantList = load(parentId).getPaymentContracts;
		return merchantList;
	}

    /**
     * save PaymentContracts on Merchant
     * @param		command AssignPaymentContractsToMerchantCommand
     */     
	@PutMapping("/addToPaymentContracts")
	public void addToPaymentContracts( @RequestBody(required=true) AssignPaymentContractsToMerchantCommand command ) {
		service.addToPaymentContracts( command );
		LOGGER.info( "Successfully added PaymentContracts with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove PaymentContracts on Merchant
     * @param		command RemovePaymentContractsFromMerchantCommand
     */     	
	@PutMapping("/removeFromPaymentContracts")
	public void removeFromPaymentContracts( 	@RequestBody(required=true) RemovePaymentContractsFromMerchantCommand command )
	{		
		service.removeFromPaymentContracts( command );
		LOGGER.info( "Successfully removed PaymentContracts with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Payouts} business objects
	 * @return		List<Merchant>

    @GetMapping("/Payouts")
    public List<Merchant> Payouts(UUID parentId) {
		List<Merchant> merchantList = load(parentId).getPayouts;
		return merchantList;
	}

    /**
     * save Payouts on Merchant
     * @param		command AssignPayoutsToMerchantCommand
     */     
	@PutMapping("/addToPayouts")
	public void addToPayouts( @RequestBody(required=true) AssignPayoutsToMerchantCommand command ) {
		service.addToPayouts( command );
		LOGGER.info( "Successfully added Payouts with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Payouts on Merchant
     * @param		command RemovePayoutsFromMerchantCommand
     */     	
	@PutMapping("/removeFromPayouts")
	public void removeFromPayouts( 	@RequestBody(required=true) RemovePayoutsFromMerchantCommand command )
	{		
		service.removeFromPayouts( command );
		LOGGER.info( "Successfully removed Payouts with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Settlements} business objects
	 * @return		List<Merchant>

    @GetMapping("/Settlements")
    public List<Merchant> Settlements(UUID parentId) {
		List<Merchant> merchantList = load(parentId).getSettlements;
		return merchantList;
	}

    /**
     * save Settlements on Merchant
     * @param		command AssignSettlementsToMerchantCommand
     */     
	@PutMapping("/addToSettlements")
	public void addToSettlements( @RequestBody(required=true) AssignSettlementsToMerchantCommand command ) {
		service.addToSettlements( command );
		LOGGER.info( "Successfully added Settlements with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Settlements on Merchant
     * @param		command RemoveSettlementsFromMerchantCommand
     */     	
	@PutMapping("/removeFromSettlements")
	public void removeFromSettlements( 	@RequestBody(required=true) RemoveSettlementsFromMerchantCommand command )
	{		
		service.removeFromSettlements( command );
		LOGGER.info( "Successfully removed Settlements with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Disputes} business objects
	 * @return		List<Merchant>

    @GetMapping("/Disputes")
    public List<Merchant> Disputes(UUID parentId) {
		List<Merchant> merchantList = load(parentId).getDisputes;
		return merchantList;
	}

    /**
     * save Disputes on Merchant
     * @param		command AssignDisputesToMerchantCommand
     */     
	@PutMapping("/addToDisputes")
	public void addToDisputes( @RequestBody(required=true) AssignDisputesToMerchantCommand command ) {
		service.addToDisputes( command );
		LOGGER.info( "Successfully added Disputes with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Disputes on Merchant
     * @param		command RemoveDisputesFromMerchantCommand
     */     	
	@PutMapping("/removeFromDisputes")
	public void removeFromDisputes( 	@RequestBody(required=true) RemoveDisputesFromMerchantCommand command )
	{		
		service.removeFromDisputes( command );
		LOGGER.info( "Successfully removed Disputes with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Invoices} business objects
	 * @return		List<Merchant>

    @GetMapping("/Invoices")
    public List<Merchant> Invoices(UUID parentId) {
		List<Merchant> merchantList = load(parentId).getInvoices;
		return merchantList;
	}

    /**
     * save Invoices on Merchant
     * @param		command AssignInvoicesToMerchantCommand
     */     
	@PutMapping("/addToInvoices")
	public void addToInvoices( @RequestBody(required=true) AssignInvoicesToMerchantCommand command ) {
		service.addToInvoices( command );
		LOGGER.info( "Successfully added Invoices with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Invoices on Merchant
     * @param		command RemoveInvoicesFromMerchantCommand
     */     	
	@PutMapping("/removeFromInvoices")
	public void removeFromInvoices( 	@RequestBody(required=true) RemoveInvoicesFromMerchantCommand command )
	{		
		service.removeFromInvoices( command );
		LOGGER.info( "Successfully removed Invoices with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Merchant merchant = null;
	protected MerchantService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(MerchantRestController.class.getName());
    
}
