
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * PaymentProcessorRestController as REST API
 *
 * <p>Exposes REST endpoints for the PaymentProcessor entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	PaymentProcessorService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreatePaymentProcessorCommand</li>
 *      <li></li>UpdatePaymentProcessorCommand</li>
 *      <liDeletePaymentProcessorCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/PaymentProcessor")
public class PaymentProcessorRestController extends BaseSpringRestController {

	public PaymentProcessorRestController( PaymentProcessorService service ) {
		this.service = service;
	}
    /**
     * Handles create a PaymentProcessor.  if not key provided, calls create, otherwise calls save
     * @param		PaymentProcessor	paymentProcessor
     * @return		PaymentProcessor 
     */
	@PostMapping("/create")
    public PaymentProcessor create( @RequestBody(required=true) CreatePaymentProcessorCommand command ) {
    	PaymentProcessor entity = null;

		entity = service.createPaymentProcessor( command );
		LOGGER.info( "Successfully created PaymentProcessor with Id " + entity.getPaymentProcessorId()  );

		return entity;
    }

    /**
     * Handles updating a PaymentProcessor.  if no key provided, calls create, otherwise calls save
     * @param		PaymentProcessor paymentProcessor
     * @return		PaymentProcessor
     */
	@PutMapping("/update")
    public PaymentProcessor update( @RequestBody(required=true) UpdatePaymentProcessorCommand command ) {
		PaymentProcessor entity = null;

		entity = service.updatePaymentProcessor(command);
		LOGGER.info( "Successfully updated PaymentProcessor with Id " + command.getPaymentProcessorId()  );

		return entity;
	}
 
    /**
     * Handles deleting a PaymentProcessor entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeletePaymentProcessorCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted PaymentProcessor with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a PaymentProcessor using a UUID
     * @param		UUID uuid 
     * @return		PaymentProcessor
     */    
    @GetMapping("/get")
    public PaymentProcessor get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	PaymentProcessor entity = service.getPaymentProcessor( new PaymentProcessorFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded PaymentProcessor with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all PaymentProcessor business objects
     * @return		List<PaymentProcessor>
     */
    @GetMapping("/")
    public List<PaymentProcessor> getAll() {
    	List<PaymentProcessor> paymentProcessorList = null;

		paymentProcessorList = service.getAllPaymentProcessor();
		LOGGER.info( "successfully loaded all PaymentProcessors" );

        return paymentProcessorList;
                            
    }


	/**
	 * Handles loading all Institutions} business objects
	 * @return		List<PaymentProcessor>

    @GetMapping("/Institutions")
    public List<PaymentProcessor> Institutions(UUID parentId) {
		List<PaymentProcessor> paymentProcessorList = load(parentId).getInstitutions;
		return paymentProcessorList;
	}

    /**
     * save Institutions on PaymentProcessor
     * @param		command AssignInstitutionsToPaymentProcessorCommand
     */     
	@PutMapping("/addToInstitutions")
	public void addToInstitutions( @RequestBody(required=true) AssignInstitutionsToPaymentProcessorCommand command ) {
		service.addToInstitutions( command );
		LOGGER.info( "Successfully added Institutions with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Institutions on PaymentProcessor
     * @param		command RemoveInstitutionsFromPaymentProcessorCommand
     */     	
	@PutMapping("/removeFromInstitutions")
	public void removeFromInstitutions( 	@RequestBody(required=true) RemoveInstitutionsFromPaymentProcessorCommand command )
	{		
		service.removeFromInstitutions( command );
		LOGGER.info( "Successfully removed Institutions with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Contracts} business objects
	 * @return		List<PaymentProcessor>

    @GetMapping("/Contracts")
    public List<PaymentProcessor> Contracts(UUID parentId) {
		List<PaymentProcessor> paymentProcessorList = load(parentId).getContracts;
		return paymentProcessorList;
	}

    /**
     * save Contracts on PaymentProcessor
     * @param		command AssignContractsToPaymentProcessorCommand
     */     
	@PutMapping("/addToContracts")
	public void addToContracts( @RequestBody(required=true) AssignContractsToPaymentProcessorCommand command ) {
		service.addToContracts( command );
		LOGGER.info( "Successfully added Contracts with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Contracts on PaymentProcessor
     * @param		command RemoveContractsFromPaymentProcessorCommand
     */     	
	@PutMapping("/removeFromContracts")
	public void removeFromContracts( 	@RequestBody(required=true) RemoveContractsFromPaymentProcessorCommand command )
	{		
		service.removeFromContracts( command );
		LOGGER.info( "Successfully removed Contracts with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Settlements} business objects
	 * @return		List<PaymentProcessor>

    @GetMapping("/Settlements")
    public List<PaymentProcessor> Settlements(UUID parentId) {
		List<PaymentProcessor> paymentProcessorList = load(parentId).getSettlements;
		return paymentProcessorList;
	}

    /**
     * save Settlements on PaymentProcessor
     * @param		command AssignSettlementsToPaymentProcessorCommand
     */     
	@PutMapping("/addToSettlements")
	public void addToSettlements( @RequestBody(required=true) AssignSettlementsToPaymentProcessorCommand command ) {
		service.addToSettlements( command );
		LOGGER.info( "Successfully added Settlements with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Settlements on PaymentProcessor
     * @param		command RemoveSettlementsFromPaymentProcessorCommand
     */     	
	@PutMapping("/removeFromSettlements")
	public void removeFromSettlements( 	@RequestBody(required=true) RemoveSettlementsFromPaymentProcessorCommand command )
	{		
		service.removeFromSettlements( command );
		LOGGER.info( "Successfully removed Settlements with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected PaymentProcessor paymentProcessor = null;
	protected PaymentProcessorService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(PaymentProcessorRestController.class.getName());
    
}
