
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * PaymentContractRestController as REST API
 *
 * <p>Exposes REST endpoints for the PaymentContract entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	PaymentContractService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreatePaymentContractCommand</li>
 *      <li></li>UpdatePaymentContractCommand</li>
 *      <liDeletePaymentContractCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/PaymentContract")
public class PaymentContractRestController extends BaseSpringRestController {

	public PaymentContractRestController( PaymentContractService service ) {
		this.service = service;
	}
    /**
     * Handles create a PaymentContract.  if not key provided, calls create, otherwise calls save
     * @param		PaymentContract	paymentContract
     * @return		PaymentContract 
     */
	@PostMapping("/create")
    public PaymentContract create( @RequestBody(required=true) CreatePaymentContractCommand command ) {
    	PaymentContract entity = null;

		entity = service.createPaymentContract( command );
		LOGGER.info( "Successfully created PaymentContract with Id " + entity.getPaymentContractId()  );

		return entity;
    }

    /**
     * Handles updating a PaymentContract.  if no key provided, calls create, otherwise calls save
     * @param		PaymentContract paymentContract
     * @return		PaymentContract
     */
	@PutMapping("/update")
    public PaymentContract update( @RequestBody(required=true) UpdatePaymentContractCommand command ) {
		PaymentContract entity = null;

		entity = service.updatePaymentContract(command);
		LOGGER.info( "Successfully updated PaymentContract with Id " + command.getPaymentContractId()  );

		return entity;
	}
 
    /**
     * Handles deleting a PaymentContract entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeletePaymentContractCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted PaymentContract with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a PaymentContract using a UUID
     * @param		UUID uuid 
     * @return		PaymentContract
     */    
    @GetMapping("/get")
    public PaymentContract get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	PaymentContract entity = service.getPaymentContract( new PaymentContractFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded PaymentContract with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all PaymentContract business objects
     * @return		List<PaymentContract>
     */
    @GetMapping("/")
    public List<PaymentContract> getAll() {
    	List<PaymentContract> paymentContractList = null;

		paymentContractList = service.getAllPaymentContract();
		LOGGER.info( "successfully loaded all PaymentContracts" );

        return paymentContractList;
                            
    }

	/**
	 * Handles loading all Merchant} business objects
	 * @return		List<PaymentContract>

    @GetMapping("/Merchant")
    public List<PaymentContract> Merchant(UUID parentId) {
		List<PaymentContract> paymentContractList = load(parentId).getMerchant;
		return paymentContractList;
	}
	 */
    /**
     * save Merchant on PaymentContract
     * @param		command AssignMerchantToPaymentContractCommand
     */     
	@PutMapping("/assignMerchant")
	public void assignMerchant( @RequestBody AssignMerchantToPaymentContractCommand command ) {
		service.assignMerchant( command );
		LOGGER.info( "Successfully assigned Merchant with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Merchant on PaymentContract
     * @param		 command UnAssignMerchantFromPaymentContractCommand
     */     
	@PutMapping("/unassignMerchant")
	public void unAssignMerchant( @RequestBody(required=true)  UnAssignMerchantFromPaymentContractCommand command ) {
		service.unAssignMerchant( command );
		LOGGER.info( "Successfully unassigned Merchant with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Acquirer} business objects
	 * @return		List<PaymentContract>

    @GetMapping("/Acquirer")
    public List<PaymentContract> Acquirer(UUID parentId) {
		List<PaymentContract> paymentContractList = load(parentId).getAcquirer;
		return paymentContractList;
	}
	 */
    /**
     * save Acquirer on PaymentContract
     * @param		command AssignAcquirerToPaymentContractCommand
     */     
	@PutMapping("/assignAcquirer")
	public void assignAcquirer( @RequestBody AssignAcquirerToPaymentContractCommand command ) {
		service.assignAcquirer( command );
		LOGGER.info( "Successfully assigned Acquirer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Acquirer on PaymentContract
     * @param		 command UnAssignAcquirerFromPaymentContractCommand
     */     
	@PutMapping("/unassignAcquirer")
	public void unAssignAcquirer( @RequestBody(required=true)  UnAssignAcquirerFromPaymentContractCommand command ) {
		service.unAssignAcquirer( command );
		LOGGER.info( "Successfully unassigned Acquirer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected PaymentContract paymentContract = null;
	protected PaymentContractService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(PaymentContractRestController.class.getName());
    
}
