
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * PayoutRestController as REST API
 *
 * <p>Exposes REST endpoints for the Payout entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	PayoutService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreatePayoutCommand</li>
 *      <li></li>UpdatePayoutCommand</li>
 *      <liDeletePayoutCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Payout")
public class PayoutRestController extends BaseSpringRestController {

	public PayoutRestController( PayoutService service ) {
		this.service = service;
	}
    /**
     * Handles create a Payout.  if not key provided, calls create, otherwise calls save
     * @param		Payout	payout
     * @return		Payout 
     */
	@PostMapping("/create")
    public Payout create( @RequestBody(required=true) CreatePayoutCommand command ) {
    	Payout entity = null;

		entity = service.createPayout( command );
		LOGGER.info( "Successfully created Payout with Id " + entity.getPayoutId()  );

		return entity;
    }

    /**
     * Handles updating a Payout.  if no key provided, calls create, otherwise calls save
     * @param		Payout payout
     * @return		Payout
     */
	@PutMapping("/update")
    public Payout update( @RequestBody(required=true) UpdatePayoutCommand command ) {
		Payout entity = null;

		entity = service.updatePayout(command);
		LOGGER.info( "Successfully updated Payout with Id " + command.getPayoutId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Payout entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeletePayoutCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Payout with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Payout using a UUID
     * @param		UUID uuid 
     * @return		Payout
     */    
    @GetMapping("/get")
    public Payout get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Payout entity = service.getPayout( new PayoutFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Payout with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Payout business objects
     * @return		List<Payout>
     */
    @GetMapping("/")
    public List<Payout> getAll() {
    	List<Payout> payoutList = null;

		payoutList = service.getAllPayout();
		LOGGER.info( "successfully loaded all Payouts" );

        return payoutList;
                            
    }

	/**
	 * Handles loading all Merchant} business objects
	 * @return		List<Payout>

    @GetMapping("/Merchant")
    public List<Payout> Merchant(UUID parentId) {
		List<Payout> payoutList = load(parentId).getMerchant;
		return payoutList;
	}
	 */
    /**
     * save Merchant on Payout
     * @param		command AssignMerchantToPayoutCommand
     */     
	@PutMapping("/assignMerchant")
	public void assignMerchant( @RequestBody AssignMerchantToPayoutCommand command ) {
		service.assignMerchant( command );
		LOGGER.info( "Successfully assigned Merchant with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Merchant on Payout
     * @param		 command UnAssignMerchantFromPayoutCommand
     */     
	@PutMapping("/unassignMerchant")
	public void unAssignMerchant( @RequestBody(required=true)  UnAssignMerchantFromPayoutCommand command ) {
		service.unAssignMerchant( command );
		LOGGER.info( "Successfully unassigned Merchant with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all SettlementBatch} business objects
	 * @return		List<Payout>

    @GetMapping("/SettlementBatch")
    public List<Payout> SettlementBatch(UUID parentId) {
		List<Payout> payoutList = load(parentId).getSettlementBatch;
		return payoutList;
	}
	 */
    /**
     * save SettlementBatch on Payout
     * @param		command AssignSettlementBatchToPayoutCommand
     */     
	@PutMapping("/assignSettlementBatch")
	public void assignSettlementBatch( @RequestBody AssignSettlementBatchToPayoutCommand command ) {
		service.assignSettlementBatch( command );
		LOGGER.info( "Successfully assigned SettlementBatch with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign SettlementBatch on Payout
     * @param		 command UnAssignSettlementBatchFromPayoutCommand
     */     
	@PutMapping("/unassignSettlementBatch")
	public void unAssignSettlementBatch( @RequestBody(required=true)  UnAssignSettlementBatchFromPayoutCommand command ) {
		service.unAssignSettlementBatch( command );
		LOGGER.info( "Successfully unassigned SettlementBatch with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all DestinationAccount} business objects
	 * @return		List<Payout>

    @GetMapping("/DestinationAccount")
    public List<Payout> DestinationAccount(UUID parentId) {
		List<Payout> payoutList = load(parentId).getDestinationAccount;
		return payoutList;
	}
	 */
    /**
     * save DestinationAccount on Payout
     * @param		command AssignDestinationAccountToPayoutCommand
     */     
	@PutMapping("/assignDestinationAccount")
	public void assignDestinationAccount( @RequestBody AssignDestinationAccountToPayoutCommand command ) {
		service.assignDestinationAccount( command );
		LOGGER.info( "Successfully assigned DestinationAccount with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign DestinationAccount on Payout
     * @param		 command UnAssignDestinationAccountFromPayoutCommand
     */     
	@PutMapping("/unassignDestinationAccount")
	public void unAssignDestinationAccount( @RequestBody(required=true)  UnAssignDestinationAccountFromPayoutCommand command ) {
		service.unAssignDestinationAccount( command );
		LOGGER.info( "Successfully unassigned DestinationAccount with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Payout payout = null;
	protected PayoutService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(PayoutRestController.class.getName());
    
}
