
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * PositionRestController as REST API
 *
 * <p>Exposes REST endpoints for the Position entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	PositionService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreatePositionCommand</li>
 *      <li></li>UpdatePositionCommand</li>
 *      <liDeletePositionCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Position")
public class PositionRestController extends BaseSpringRestController {

	public PositionRestController( PositionService service ) {
		this.service = service;
	}
    /**
     * Handles create a Position.  if not key provided, calls create, otherwise calls save
     * @param		Position	position
     * @return		Position 
     */
	@PostMapping("/create")
    public Position create( @RequestBody(required=true) CreatePositionCommand command ) {
    	Position entity = null;

		entity = service.createPosition( command );
		LOGGER.info( "Successfully created Position with Id " + entity.getPositionId()  );

		return entity;
    }

    /**
     * Handles updating a Position.  if no key provided, calls create, otherwise calls save
     * @param		Position position
     * @return		Position
     */
	@PutMapping("/update")
    public Position update( @RequestBody(required=true) UpdatePositionCommand command ) {
		Position entity = null;

		entity = service.updatePosition(command);
		LOGGER.info( "Successfully updated Position with Id " + command.getPositionId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Position entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeletePositionCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Position with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Position using a UUID
     * @param		UUID uuid 
     * @return		Position
     */    
    @GetMapping("/get")
    public Position get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Position entity = service.getPosition( new PositionFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Position with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Position business objects
     * @return		List<Position>
     */
    @GetMapping("/")
    public List<Position> getAll() {
    	List<Position> positionList = null;

		positionList = service.getAllPosition();
		LOGGER.info( "successfully loaded all Positions" );

        return positionList;
                            
    }

	/**
	 * Handles loading all Portfolio} business objects
	 * @return		List<Position>

    @GetMapping("/Portfolio")
    public List<Position> Portfolio(UUID parentId) {
		List<Position> positionList = load(parentId).getPortfolio;
		return positionList;
	}
	 */
    /**
     * save Portfolio on Position
     * @param		command AssignPortfolioToPositionCommand
     */     
	@PutMapping("/assignPortfolio")
	public void assignPortfolio( @RequestBody AssignPortfolioToPositionCommand command ) {
		service.assignPortfolio( command );
		LOGGER.info( "Successfully assigned Portfolio with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Portfolio on Position
     * @param		 command UnAssignPortfolioFromPositionCommand
     */     
	@PutMapping("/unassignPortfolio")
	public void unAssignPortfolio( @RequestBody(required=true)  UnAssignPortfolioFromPositionCommand command ) {
		service.unAssignPortfolio( command );
		LOGGER.info( "Successfully unassigned Portfolio with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Security} business objects
	 * @return		List<Position>

    @GetMapping("/Security")
    public List<Position> Security(UUID parentId) {
		List<Position> positionList = load(parentId).getSecurity;
		return positionList;
	}
	 */
    /**
     * save Security on Position
     * @param		command AssignSecurityToPositionCommand
     */     
	@PutMapping("/assignSecurity")
	public void assignSecurity( @RequestBody AssignSecurityToPositionCommand command ) {
		service.assignSecurity( command );
		LOGGER.info( "Successfully assigned Security with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Security on Position
     * @param		 command UnAssignSecurityFromPositionCommand
     */     
	@PutMapping("/unassignSecurity")
	public void unAssignSecurity( @RequestBody(required=true)  UnAssignSecurityFromPositionCommand command ) {
		service.unAssignSecurity( command );
		LOGGER.info( "Successfully unassigned Security with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Position position = null;
	protected PositionService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(PositionRestController.class.getName());
    
}
