
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * PricingPlanRestController as REST API
 *
 * <p>Exposes REST endpoints for the PricingPlan entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	PricingPlanService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreatePricingPlanCommand</li>
 *      <li></li>UpdatePricingPlanCommand</li>
 *      <liDeletePricingPlanCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/PricingPlan")
public class PricingPlanRestController extends BaseSpringRestController {

	public PricingPlanRestController( PricingPlanService service ) {
		this.service = service;
	}
    /**
     * Handles create a PricingPlan.  if not key provided, calls create, otherwise calls save
     * @param		PricingPlan	pricingPlan
     * @return		PricingPlan 
     */
	@PostMapping("/create")
    public PricingPlan create( @RequestBody(required=true) CreatePricingPlanCommand command ) {
    	PricingPlan entity = null;

		entity = service.createPricingPlan( command );
		LOGGER.info( "Successfully created PricingPlan with Id " + entity.getPricingPlanId()  );

		return entity;
    }

    /**
     * Handles updating a PricingPlan.  if no key provided, calls create, otherwise calls save
     * @param		PricingPlan pricingPlan
     * @return		PricingPlan
     */
	@PutMapping("/update")
    public PricingPlan update( @RequestBody(required=true) UpdatePricingPlanCommand command ) {
		PricingPlan entity = null;

		entity = service.updatePricingPlan(command);
		LOGGER.info( "Successfully updated PricingPlan with Id " + command.getPricingPlanId()  );

		return entity;
	}
 
    /**
     * Handles deleting a PricingPlan entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeletePricingPlanCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted PricingPlan with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a PricingPlan using a UUID
     * @param		UUID uuid 
     * @return		PricingPlan
     */    
    @GetMapping("/get")
    public PricingPlan get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	PricingPlan entity = service.getPricingPlan( new PricingPlanFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded PricingPlan with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all PricingPlan business objects
     * @return		List<PricingPlan>
     */
    @GetMapping("/")
    public List<PricingPlan> getAll() {
    	List<PricingPlan> pricingPlanList = null;

		pricingPlanList = service.getAllPricingPlan();
		LOGGER.info( "successfully loaded all PricingPlans" );

        return pricingPlanList;
                            
    }

	/**
	 * Handles loading all ProductOffering} business objects
	 * @return		List<PricingPlan>

    @GetMapping("/ProductOffering")
    public List<PricingPlan> ProductOffering(UUID parentId) {
		List<PricingPlan> pricingPlanList = load(parentId).getProductOffering;
		return pricingPlanList;
	}
	 */
    /**
     * save ProductOffering on PricingPlan
     * @param		command AssignProductOfferingToPricingPlanCommand
     */     
	@PutMapping("/assignProductOffering")
	public void assignProductOffering( @RequestBody AssignProductOfferingToPricingPlanCommand command ) {
		service.assignProductOffering( command );
		LOGGER.info( "Successfully assigned ProductOffering with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign ProductOffering on PricingPlan
     * @param		 command UnAssignProductOfferingFromPricingPlanCommand
     */     
	@PutMapping("/unassignProductOffering")
	public void unAssignProductOffering( @RequestBody(required=true)  UnAssignProductOfferingFromPricingPlanCommand command ) {
		service.unAssignProductOffering( command );
		LOGGER.info( "Successfully unassigned ProductOffering with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all FeeSchedules} business objects
	 * @return		List<PricingPlan>

    @GetMapping("/FeeSchedules")
    public List<PricingPlan> FeeSchedules(UUID parentId) {
		List<PricingPlan> pricingPlanList = load(parentId).getFeeSchedules;
		return pricingPlanList;
	}

    /**
     * save FeeSchedules on PricingPlan
     * @param		command AssignFeeSchedulesToPricingPlanCommand
     */     
	@PutMapping("/addToFeeSchedules")
	public void addToFeeSchedules( @RequestBody(required=true) AssignFeeSchedulesToPricingPlanCommand command ) {
		service.addToFeeSchedules( command );
		LOGGER.info( "Successfully added FeeSchedules with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove FeeSchedules on PricingPlan
     * @param		command RemoveFeeSchedulesFromPricingPlanCommand
     */     	
	@PutMapping("/removeFromFeeSchedules")
	public void removeFromFeeSchedules( 	@RequestBody(required=true) RemoveFeeSchedulesFromPricingPlanCommand command )
	{		
		service.removeFromFeeSchedules( command );
		LOGGER.info( "Successfully removed FeeSchedules with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Limits} business objects
	 * @return		List<PricingPlan>

    @GetMapping("/Limits")
    public List<PricingPlan> Limits(UUID parentId) {
		List<PricingPlan> pricingPlanList = load(parentId).getLimits;
		return pricingPlanList;
	}

    /**
     * save Limits on PricingPlan
     * @param		command AssignLimitsToPricingPlanCommand
     */     
	@PutMapping("/addToLimits")
	public void addToLimits( @RequestBody(required=true) AssignLimitsToPricingPlanCommand command ) {
		service.addToLimits( command );
		LOGGER.info( "Successfully added Limits with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Limits on PricingPlan
     * @param		command RemoveLimitsFromPricingPlanCommand
     */     	
	@PutMapping("/removeFromLimits")
	public void removeFromLimits( 	@RequestBody(required=true) RemoveLimitsFromPricingPlanCommand command )
	{		
		service.removeFromLimits( command );
		LOGGER.info( "Successfully removed Limits with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected PricingPlan pricingPlan = null;
	protected PricingPlanService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(PricingPlanRestController.class.getName());
    
}
