
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * ProductOfferingRestController as REST API
 *
 * <p>Exposes REST endpoints for the ProductOffering entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	ProductOfferingService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateProductOfferingCommand</li>
 *      <li></li>UpdateProductOfferingCommand</li>
 *      <liDeleteProductOfferingCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/ProductOffering")
public class ProductOfferingRestController extends BaseSpringRestController {

	public ProductOfferingRestController( ProductOfferingService service ) {
		this.service = service;
	}
    /**
     * Handles create a ProductOffering.  if not key provided, calls create, otherwise calls save
     * @param		ProductOffering	productOffering
     * @return		ProductOffering 
     */
	@PostMapping("/create")
    public ProductOffering create( @RequestBody(required=true) CreateProductOfferingCommand command ) {
    	ProductOffering entity = null;

		entity = service.createProductOffering( command );
		LOGGER.info( "Successfully created ProductOffering with Id " + entity.getProductOfferingId()  );

		return entity;
    }

    /**
     * Handles updating a ProductOffering.  if no key provided, calls create, otherwise calls save
     * @param		ProductOffering productOffering
     * @return		ProductOffering
     */
	@PutMapping("/update")
    public ProductOffering update( @RequestBody(required=true) UpdateProductOfferingCommand command ) {
		ProductOffering entity = null;

		entity = service.updateProductOffering(command);
		LOGGER.info( "Successfully updated ProductOffering with Id " + command.getProductOfferingId()  );

		return entity;
	}
 
    /**
     * Handles deleting a ProductOffering entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteProductOfferingCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted ProductOffering with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a ProductOffering using a UUID
     * @param		UUID uuid 
     * @return		ProductOffering
     */    
    @GetMapping("/get")
    public ProductOffering get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	ProductOffering entity = service.getProductOffering( new ProductOfferingFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded ProductOffering with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all ProductOffering business objects
     * @return		List<ProductOffering>
     */
    @GetMapping("/")
    public List<ProductOffering> getAll() {
    	List<ProductOffering> productOfferingList = null;

		productOfferingList = service.getAllProductOffering();
		LOGGER.info( "successfully loaded all ProductOfferings" );

        return productOfferingList;
                            
    }

	/**
	 * Handles loading all Institution} business objects
	 * @return		List<ProductOffering>

    @GetMapping("/Institution")
    public List<ProductOffering> Institution(UUID parentId) {
		List<ProductOffering> productOfferingList = load(parentId).getInstitution;
		return productOfferingList;
	}
	 */
    /**
     * save Institution on ProductOffering
     * @param		command AssignInstitutionToProductOfferingCommand
     */     
	@PutMapping("/assignInstitution")
	public void assignInstitution( @RequestBody AssignInstitutionToProductOfferingCommand command ) {
		service.assignInstitution( command );
		LOGGER.info( "Successfully assigned Institution with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Institution on ProductOffering
     * @param		 command UnAssignInstitutionFromProductOfferingCommand
     */     
	@PutMapping("/unassignInstitution")
	public void unAssignInstitution( @RequestBody(required=true)  UnAssignInstitutionFromProductOfferingCommand command ) {
		service.unAssignInstitution( command );
		LOGGER.info( "Successfully unassigned Institution with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all PricingPlans} business objects
	 * @return		List<ProductOffering>

    @GetMapping("/PricingPlans")
    public List<ProductOffering> PricingPlans(UUID parentId) {
		List<ProductOffering> productOfferingList = load(parentId).getPricingPlans;
		return productOfferingList;
	}

    /**
     * save PricingPlans on ProductOffering
     * @param		command AssignPricingPlansToProductOfferingCommand
     */     
	@PutMapping("/addToPricingPlans")
	public void addToPricingPlans( @RequestBody(required=true) AssignPricingPlansToProductOfferingCommand command ) {
		service.addToPricingPlans( command );
		LOGGER.info( "Successfully added PricingPlans with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove PricingPlans on ProductOffering
     * @param		command RemovePricingPlansFromProductOfferingCommand
     */     	
	@PutMapping("/removeFromPricingPlans")
	public void removeFromPricingPlans( 	@RequestBody(required=true) RemovePricingPlansFromProductOfferingCommand command )
	{		
		service.removeFromPricingPlans( command );
		LOGGER.info( "Successfully removed PricingPlans with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected ProductOffering productOffering = null;
	protected ProductOfferingService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(ProductOfferingRestController.class.getName());
    
}
