
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * RepaymentScheduleRestController as REST API
 *
 * <p>Exposes REST endpoints for the RepaymentSchedule entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	RepaymentScheduleService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateRepaymentScheduleCommand</li>
 *      <li></li>UpdateRepaymentScheduleCommand</li>
 *      <liDeleteRepaymentScheduleCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/RepaymentSchedule")
public class RepaymentScheduleRestController extends BaseSpringRestController {

	public RepaymentScheduleRestController( RepaymentScheduleService service ) {
		this.service = service;
	}
    /**
     * Handles create a RepaymentSchedule.  if not key provided, calls create, otherwise calls save
     * @param		RepaymentSchedule	repaymentSchedule
     * @return		RepaymentSchedule 
     */
	@PostMapping("/create")
    public RepaymentSchedule create( @RequestBody(required=true) CreateRepaymentScheduleCommand command ) {
    	RepaymentSchedule entity = null;

		entity = service.createRepaymentSchedule( command );
		LOGGER.info( "Successfully created RepaymentSchedule with Id " + entity.getRepaymentScheduleId()  );

		return entity;
    }

    /**
     * Handles updating a RepaymentSchedule.  if no key provided, calls create, otherwise calls save
     * @param		RepaymentSchedule repaymentSchedule
     * @return		RepaymentSchedule
     */
	@PutMapping("/update")
    public RepaymentSchedule update( @RequestBody(required=true) UpdateRepaymentScheduleCommand command ) {
		RepaymentSchedule entity = null;

		entity = service.updateRepaymentSchedule(command);
		LOGGER.info( "Successfully updated RepaymentSchedule with Id " + command.getRepaymentScheduleId()  );

		return entity;
	}
 
    /**
     * Handles deleting a RepaymentSchedule entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteRepaymentScheduleCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted RepaymentSchedule with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a RepaymentSchedule using a UUID
     * @param		UUID uuid 
     * @return		RepaymentSchedule
     */    
    @GetMapping("/get")
    public RepaymentSchedule get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	RepaymentSchedule entity = service.getRepaymentSchedule( new RepaymentScheduleFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded RepaymentSchedule with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all RepaymentSchedule business objects
     * @return		List<RepaymentSchedule>
     */
    @GetMapping("/")
    public List<RepaymentSchedule> getAll() {
    	List<RepaymentSchedule> repaymentScheduleList = null;

		repaymentScheduleList = service.getAllRepaymentSchedule();
		LOGGER.info( "successfully loaded all RepaymentSchedules" );

        return repaymentScheduleList;
                            
    }

	/**
	 * Handles loading all Loan} business objects
	 * @return		List<RepaymentSchedule>

    @GetMapping("/Loan")
    public List<RepaymentSchedule> Loan(UUID parentId) {
		List<RepaymentSchedule> repaymentScheduleList = load(parentId).getLoan;
		return repaymentScheduleList;
	}
	 */
    /**
     * save Loan on RepaymentSchedule
     * @param		command AssignLoanToRepaymentScheduleCommand
     */     
	@PutMapping("/assignLoan")
	public void assignLoan( @RequestBody AssignLoanToRepaymentScheduleCommand command ) {
		service.assignLoan( command );
		LOGGER.info( "Successfully assigned Loan with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Loan on RepaymentSchedule
     * @param		 command UnAssignLoanFromRepaymentScheduleCommand
     */     
	@PutMapping("/unassignLoan")
	public void unAssignLoan( @RequestBody(required=true)  UnAssignLoanFromRepaymentScheduleCommand command ) {
		service.unAssignLoan( command );
		LOGGER.info( "Successfully unassigned Loan with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Payments} business objects
	 * @return		List<RepaymentSchedule>

    @GetMapping("/Payments")
    public List<RepaymentSchedule> Payments(UUID parentId) {
		List<RepaymentSchedule> repaymentScheduleList = load(parentId).getPayments;
		return repaymentScheduleList;
	}

    /**
     * save Payments on RepaymentSchedule
     * @param		command AssignPaymentsToRepaymentScheduleCommand
     */     
	@PutMapping("/addToPayments")
	public void addToPayments( @RequestBody(required=true) AssignPaymentsToRepaymentScheduleCommand command ) {
		service.addToPayments( command );
		LOGGER.info( "Successfully added Payments with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Payments on RepaymentSchedule
     * @param		command RemovePaymentsFromRepaymentScheduleCommand
     */     	
	@PutMapping("/removeFromPayments")
	public void removeFromPayments( 	@RequestBody(required=true) RemovePaymentsFromRepaymentScheduleCommand command )
	{		
		service.removeFromPayments( command );
		LOGGER.info( "Successfully removed Payments with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected RepaymentSchedule repaymentSchedule = null;
	protected RepaymentScheduleService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(RepaymentScheduleRestController.class.getName());
    
}
