
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * SecurityRestController as REST API
 *
 * <p>Exposes REST endpoints for the Security entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	SecurityService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateSecurityCommand</li>
 *      <li></li>UpdateSecurityCommand</li>
 *      <liDeleteSecurityCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Security")
public class SecurityRestController extends BaseSpringRestController {

	public SecurityRestController( SecurityService service ) {
		this.service = service;
	}
    /**
     * Handles create a Security.  if not key provided, calls create, otherwise calls save
     * @param		Security	security
     * @return		Security 
     */
	@PostMapping("/create")
    public Security create( @RequestBody(required=true) CreateSecurityCommand command ) {
    	Security entity = null;

		entity = service.createSecurity( command );
		LOGGER.info( "Successfully created Security with Id " + entity.getSecurityId()  );

		return entity;
    }

    /**
     * Handles updating a Security.  if no key provided, calls create, otherwise calls save
     * @param		Security security
     * @return		Security
     */
	@PutMapping("/update")
    public Security update( @RequestBody(required=true) UpdateSecurityCommand command ) {
		Security entity = null;

		entity = service.updateSecurity(command);
		LOGGER.info( "Successfully updated Security with Id " + command.getSecurityId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Security entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteSecurityCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Security with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Security using a UUID
     * @param		UUID uuid 
     * @return		Security
     */    
    @GetMapping("/get")
    public Security get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Security entity = service.getSecurity( new SecurityFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Security with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Security business objects
     * @return		List<Security>
     */
    @GetMapping("/")
    public List<Security> getAll() {
    	List<Security> securityList = null;

		securityList = service.getAllSecurity();
		LOGGER.info( "successfully loaded all Securitys" );

        return securityList;
                            
    }


	/**
	 * Handles loading all Positions} business objects
	 * @return		List<Security>

    @GetMapping("/Positions")
    public List<Security> Positions(UUID parentId) {
		List<Security> securityList = load(parentId).getPositions;
		return securityList;
	}

    /**
     * save Positions on Security
     * @param		command AssignPositionsToSecurityCommand
     */     
	@PutMapping("/addToPositions")
	public void addToPositions( @RequestBody(required=true) AssignPositionsToSecurityCommand command ) {
		service.addToPositions( command );
		LOGGER.info( "Successfully added Positions with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Positions on Security
     * @param		command RemovePositionsFromSecurityCommand
     */     	
	@PutMapping("/removeFromPositions")
	public void removeFromPositions( 	@RequestBody(required=true) RemovePositionsFromSecurityCommand command )
	{		
		service.removeFromPositions( command );
		LOGGER.info( "Successfully removed Positions with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Trades} business objects
	 * @return		List<Security>

    @GetMapping("/Trades")
    public List<Security> Trades(UUID parentId) {
		List<Security> securityList = load(parentId).getTrades;
		return securityList;
	}

    /**
     * save Trades on Security
     * @param		command AssignTradesToSecurityCommand
     */     
	@PutMapping("/addToTrades")
	public void addToTrades( @RequestBody(required=true) AssignTradesToSecurityCommand command ) {
		service.addToTrades( command );
		LOGGER.info( "Successfully added Trades with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Trades on Security
     * @param		command RemoveTradesFromSecurityCommand
     */     	
	@PutMapping("/removeFromTrades")
	public void removeFromTrades( 	@RequestBody(required=true) RemoveTradesFromSecurityCommand command )
	{		
		service.removeFromTrades( command );
		LOGGER.info( "Successfully removed Trades with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Orders} business objects
	 * @return		List<Security>

    @GetMapping("/Orders")
    public List<Security> Orders(UUID parentId) {
		List<Security> securityList = load(parentId).getOrders;
		return securityList;
	}

    /**
     * save Orders on Security
     * @param		command AssignOrdersToSecurityCommand
     */     
	@PutMapping("/addToOrders")
	public void addToOrders( @RequestBody(required=true) AssignOrdersToSecurityCommand command ) {
		service.addToOrders( command );
		LOGGER.info( "Successfully added Orders with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Orders on Security
     * @param		command RemoveOrdersFromSecurityCommand
     */     	
	@PutMapping("/removeFromOrders")
	public void removeFromOrders( 	@RequestBody(required=true) RemoveOrdersFromSecurityCommand command )
	{		
		service.removeFromOrders( command );
		LOGGER.info( "Successfully removed Orders with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Security security = null;
	protected SecurityService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(SecurityRestController.class.getName());
    
}
