
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * SettlementBatchRestController as REST API
 *
 * <p>Exposes REST endpoints for the SettlementBatch entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	SettlementBatchService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateSettlementBatchCommand</li>
 *      <li></li>UpdateSettlementBatchCommand</li>
 *      <liDeleteSettlementBatchCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/SettlementBatch")
public class SettlementBatchRestController extends BaseSpringRestController {

	public SettlementBatchRestController( SettlementBatchService service ) {
		this.service = service;
	}
    /**
     * Handles create a SettlementBatch.  if not key provided, calls create, otherwise calls save
     * @param		SettlementBatch	settlementBatch
     * @return		SettlementBatch 
     */
	@PostMapping("/create")
    public SettlementBatch create( @RequestBody(required=true) CreateSettlementBatchCommand command ) {
    	SettlementBatch entity = null;

		entity = service.createSettlementBatch( command );
		LOGGER.info( "Successfully created SettlementBatch with Id " + entity.getSettlementBatchId()  );

		return entity;
    }

    /**
     * Handles updating a SettlementBatch.  if no key provided, calls create, otherwise calls save
     * @param		SettlementBatch settlementBatch
     * @return		SettlementBatch
     */
	@PutMapping("/update")
    public SettlementBatch update( @RequestBody(required=true) UpdateSettlementBatchCommand command ) {
		SettlementBatch entity = null;

		entity = service.updateSettlementBatch(command);
		LOGGER.info( "Successfully updated SettlementBatch with Id " + command.getSettlementBatchId()  );

		return entity;
	}
 
    /**
     * Handles deleting a SettlementBatch entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteSettlementBatchCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted SettlementBatch with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a SettlementBatch using a UUID
     * @param		UUID uuid 
     * @return		SettlementBatch
     */    
    @GetMapping("/get")
    public SettlementBatch get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	SettlementBatch entity = service.getSettlementBatch( new SettlementBatchFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded SettlementBatch with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all SettlementBatch business objects
     * @return		List<SettlementBatch>
     */
    @GetMapping("/")
    public List<SettlementBatch> getAll() {
    	List<SettlementBatch> settlementBatchList = null;

		settlementBatchList = service.getAllSettlementBatch();
		LOGGER.info( "successfully loaded all SettlementBatchs" );

        return settlementBatchList;
                            
    }

	/**
	 * Handles loading all Processor} business objects
	 * @return		List<SettlementBatch>

    @GetMapping("/Processor")
    public List<SettlementBatch> Processor(UUID parentId) {
		List<SettlementBatch> settlementBatchList = load(parentId).getProcessor;
		return settlementBatchList;
	}
	 */
    /**
     * save Processor on SettlementBatch
     * @param		command AssignProcessorToSettlementBatchCommand
     */     
	@PutMapping("/assignProcessor")
	public void assignProcessor( @RequestBody AssignProcessorToSettlementBatchCommand command ) {
		service.assignProcessor( command );
		LOGGER.info( "Successfully assigned Processor with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Processor on SettlementBatch
     * @param		 command UnAssignProcessorFromSettlementBatchCommand
     */     
	@PutMapping("/unassignProcessor")
	public void unAssignProcessor( @RequestBody(required=true)  UnAssignProcessorFromSettlementBatchCommand command ) {
		service.unAssignProcessor( command );
		LOGGER.info( "Successfully unassigned Processor with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Merchant} business objects
	 * @return		List<SettlementBatch>

    @GetMapping("/Merchant")
    public List<SettlementBatch> Merchant(UUID parentId) {
		List<SettlementBatch> settlementBatchList = load(parentId).getMerchant;
		return settlementBatchList;
	}
	 */
    /**
     * save Merchant on SettlementBatch
     * @param		command AssignMerchantToSettlementBatchCommand
     */     
	@PutMapping("/assignMerchant")
	public void assignMerchant( @RequestBody AssignMerchantToSettlementBatchCommand command ) {
		service.assignMerchant( command );
		LOGGER.info( "Successfully assigned Merchant with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Merchant on SettlementBatch
     * @param		 command UnAssignMerchantFromSettlementBatchCommand
     */     
	@PutMapping("/unassignMerchant")
	public void unAssignMerchant( @RequestBody(required=true)  UnAssignMerchantFromSettlementBatchCommand command ) {
		service.unAssignMerchant( command );
		LOGGER.info( "Successfully unassigned Merchant with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Payouts} business objects
	 * @return		List<SettlementBatch>

    @GetMapping("/Payouts")
    public List<SettlementBatch> Payouts(UUID parentId) {
		List<SettlementBatch> settlementBatchList = load(parentId).getPayouts;
		return settlementBatchList;
	}

    /**
     * save Payouts on SettlementBatch
     * @param		command AssignPayoutsToSettlementBatchCommand
     */     
	@PutMapping("/addToPayouts")
	public void addToPayouts( @RequestBody(required=true) AssignPayoutsToSettlementBatchCommand command ) {
		service.addToPayouts( command );
		LOGGER.info( "Successfully added Payouts with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Payouts on SettlementBatch
     * @param		command RemovePayoutsFromSettlementBatchCommand
     */     	
	@PutMapping("/removeFromPayouts")
	public void removeFromPayouts( 	@RequestBody(required=true) RemovePayoutsFromSettlementBatchCommand command )
	{		
		service.removeFromPayouts( command );
		LOGGER.info( "Successfully removed Payouts with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

	/**
	 * Handles loading all Transactions} business objects
	 * @return		List<SettlementBatch>

    @GetMapping("/Transactions")
    public List<SettlementBatch> Transactions(UUID parentId) {
		List<SettlementBatch> settlementBatchList = load(parentId).getTransactions;
		return settlementBatchList;
	}

    /**
     * save Transactions on SettlementBatch
     * @param		command AssignTransactionsToSettlementBatchCommand
     */     
	@PutMapping("/addToTransactions")
	public void addToTransactions( @RequestBody(required=true) AssignTransactionsToSettlementBatchCommand command ) {
		service.addToTransactions( command );
		LOGGER.info( "Successfully added Transactions with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Transactions on SettlementBatch
     * @param		command RemoveTransactionsFromSettlementBatchCommand
     */     	
	@PutMapping("/removeFromTransactions")
	public void removeFromTransactions( 	@RequestBody(required=true) RemoveTransactionsFromSettlementBatchCommand command )
	{		
		service.removeFromTransactions( command );
		LOGGER.info( "Successfully removed Transactions with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected SettlementBatch settlementBatch = null;
	protected SettlementBatchService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(SettlementBatchRestController.class.getName());
    
}
