
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * TradeOrderRestController as REST API
 *
 * <p>Exposes REST endpoints for the TradeOrder entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	TradeOrderService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateTradeOrderCommand</li>
 *      <li></li>UpdateTradeOrderCommand</li>
 *      <liDeleteTradeOrderCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/TradeOrder")
public class TradeOrderRestController extends BaseSpringRestController {

	public TradeOrderRestController( TradeOrderService service ) {
		this.service = service;
	}
    /**
     * Handles create a TradeOrder.  if not key provided, calls create, otherwise calls save
     * @param		TradeOrder	tradeOrder
     * @return		TradeOrder 
     */
	@PostMapping("/create")
    public TradeOrder create( @RequestBody(required=true) CreateTradeOrderCommand command ) {
    	TradeOrder entity = null;

		entity = service.createTradeOrder( command );
		LOGGER.info( "Successfully created TradeOrder with Id " + entity.getTradeOrderId()  );

		return entity;
    }

    /**
     * Handles updating a TradeOrder.  if no key provided, calls create, otherwise calls save
     * @param		TradeOrder tradeOrder
     * @return		TradeOrder
     */
	@PutMapping("/update")
    public TradeOrder update( @RequestBody(required=true) UpdateTradeOrderCommand command ) {
		TradeOrder entity = null;

		entity = service.updateTradeOrder(command);
		LOGGER.info( "Successfully updated TradeOrder with Id " + command.getTradeOrderId()  );

		return entity;
	}
 
    /**
     * Handles deleting a TradeOrder entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteTradeOrderCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted TradeOrder with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a TradeOrder using a UUID
     * @param		UUID uuid 
     * @return		TradeOrder
     */    
    @GetMapping("/get")
    public TradeOrder get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	TradeOrder entity = service.getTradeOrder( new TradeOrderFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded TradeOrder with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all TradeOrder business objects
     * @return		List<TradeOrder>
     */
    @GetMapping("/")
    public List<TradeOrder> getAll() {
    	List<TradeOrder> tradeOrderList = null;

		tradeOrderList = service.getAllTradeOrder();
		LOGGER.info( "successfully loaded all TradeOrders" );

        return tradeOrderList;
                            
    }

	/**
	 * Handles loading all Portfolio} business objects
	 * @return		List<TradeOrder>

    @GetMapping("/Portfolio")
    public List<TradeOrder> Portfolio(UUID parentId) {
		List<TradeOrder> tradeOrderList = load(parentId).getPortfolio;
		return tradeOrderList;
	}
	 */
    /**
     * save Portfolio on TradeOrder
     * @param		command AssignPortfolioToTradeOrderCommand
     */     
	@PutMapping("/assignPortfolio")
	public void assignPortfolio( @RequestBody AssignPortfolioToTradeOrderCommand command ) {
		service.assignPortfolio( command );
		LOGGER.info( "Successfully assigned Portfolio with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Portfolio on TradeOrder
     * @param		 command UnAssignPortfolioFromTradeOrderCommand
     */     
	@PutMapping("/unassignPortfolio")
	public void unAssignPortfolio( @RequestBody(required=true)  UnAssignPortfolioFromTradeOrderCommand command ) {
		service.unAssignPortfolio( command );
		LOGGER.info( "Successfully unassigned Portfolio with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	
	/**
	 * Handles loading all Security} business objects
	 * @return		List<TradeOrder>

    @GetMapping("/Security")
    public List<TradeOrder> Security(UUID parentId) {
		List<TradeOrder> tradeOrderList = load(parentId).getSecurity;
		return tradeOrderList;
	}
	 */
    /**
     * save Security on TradeOrder
     * @param		command AssignSecurityToTradeOrderCommand
     */     
	@PutMapping("/assignSecurity")
	public void assignSecurity( @RequestBody AssignSecurityToTradeOrderCommand command ) {
		service.assignSecurity( command );
		LOGGER.info( "Successfully assigned Security with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Security on TradeOrder
     * @param		 command UnAssignSecurityFromTradeOrderCommand
     */     
	@PutMapping("/unassignSecurity")
	public void unAssignSecurity( @RequestBody(required=true)  UnAssignSecurityFromTradeOrderCommand command ) {
		service.unAssignSecurity( command );
		LOGGER.info( "Successfully unassigned Security with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Trades} business objects
	 * @return		List<TradeOrder>

    @GetMapping("/Trades")
    public List<TradeOrder> Trades(UUID parentId) {
		List<TradeOrder> tradeOrderList = load(parentId).getTrades;
		return tradeOrderList;
	}

    /**
     * save Trades on TradeOrder
     * @param		command AssignTradesToTradeOrderCommand
     */     
	@PutMapping("/addToTrades")
	public void addToTrades( @RequestBody(required=true) AssignTradesToTradeOrderCommand command ) {
		service.addToTrades( command );
		LOGGER.info( "Successfully added Trades with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Trades on TradeOrder
     * @param		command RemoveTradesFromTradeOrderCommand
     */     	
	@PutMapping("/removeFromTrades")
	public void removeFromTrades( 	@RequestBody(required=true) RemoveTradesFromTradeOrderCommand command )
	{		
		service.removeFromTrades( command );
		LOGGER.info( "Successfully removed Trades with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected TradeOrder tradeOrder = null;
	protected TradeOrderService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(TradeOrderRestController.class.getName());
    
}
