
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * UsageLimitRestController as REST API
 *
 * <p>Exposes REST endpoints for the UsageLimit entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	UsageLimitService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateUsageLimitCommand</li>
 *      <li></li>UpdateUsageLimitCommand</li>
 *      <liDeleteUsageLimitCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/UsageLimit")
public class UsageLimitRestController extends BaseSpringRestController {

	public UsageLimitRestController( UsageLimitService service ) {
		this.service = service;
	}
    /**
     * Handles create a UsageLimit.  if not key provided, calls create, otherwise calls save
     * @param		UsageLimit	usageLimit
     * @return		UsageLimit 
     */
	@PostMapping("/create")
    public UsageLimit create( @RequestBody(required=true) CreateUsageLimitCommand command ) {
    	UsageLimit entity = null;

		entity = service.createUsageLimit( command );
		LOGGER.info( "Successfully created UsageLimit with Id " + entity.getUsageLimitId()  );

		return entity;
    }

    /**
     * Handles updating a UsageLimit.  if no key provided, calls create, otherwise calls save
     * @param		UsageLimit usageLimit
     * @return		UsageLimit
     */
	@PutMapping("/update")
    public UsageLimit update( @RequestBody(required=true) UpdateUsageLimitCommand command ) {
		UsageLimit entity = null;

		entity = service.updateUsageLimit(command);
		LOGGER.info( "Successfully updated UsageLimit with Id " + command.getUsageLimitId()  );

		return entity;
	}
 
    /**
     * Handles deleting a UsageLimit entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteUsageLimitCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted UsageLimit with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a UsageLimit using a UUID
     * @param		UUID uuid 
     * @return		UsageLimit
     */    
    @GetMapping("/get")
    public UsageLimit get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	UsageLimit entity = service.getUsageLimit( new UsageLimitFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded UsageLimit with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all UsageLimit business objects
     * @return		List<UsageLimit>
     */
    @GetMapping("/")
    public List<UsageLimit> getAll() {
    	List<UsageLimit> usageLimitList = null;

		usageLimitList = service.getAllUsageLimit();
		LOGGER.info( "successfully loaded all UsageLimits" );

        return usageLimitList;
                            
    }

	/**
	 * Handles loading all PricingPlan} business objects
	 * @return		List<UsageLimit>

    @GetMapping("/PricingPlan")
    public List<UsageLimit> PricingPlan(UUID parentId) {
		List<UsageLimit> usageLimitList = load(parentId).getPricingPlan;
		return usageLimitList;
	}
	 */
    /**
     * save PricingPlan on UsageLimit
     * @param		command AssignPricingPlanToUsageLimitCommand
     */     
	@PutMapping("/assignPricingPlan")
	public void assignPricingPlan( @RequestBody AssignPricingPlanToUsageLimitCommand command ) {
		service.assignPricingPlan( command );
		LOGGER.info( "Successfully assigned PricingPlan with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign PricingPlan on UsageLimit
     * @param		 command UnAssignPricingPlanFromUsageLimitCommand
     */     
	@PutMapping("/unassignPricingPlan")
	public void unAssignPricingPlan( @RequestBody(required=true)  UnAssignPricingPlanFromUsageLimitCommand command ) {
		service.unAssignPricingPlan( command );
		LOGGER.info( "Successfully unassigned PricingPlan with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected UsageLimit usageLimit = null;
	protected UsageLimitService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(UsageLimitRestController.class.getName());
    
}
