
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * WalletRestController as REST API
 *
 * <p>Exposes REST endpoints for the Wallet entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	WalletService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateWalletCommand</li>
 *      <li></li>UpdateWalletCommand</li>
 *      <liDeleteWalletCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Wallet")
public class WalletRestController extends BaseSpringRestController {

	public WalletRestController( WalletService service ) {
		this.service = service;
	}
    /**
     * Handles create a Wallet.  if not key provided, calls create, otherwise calls save
     * @param		Wallet	wallet
     * @return		Wallet 
     */
	@PostMapping("/create")
    public Wallet create( @RequestBody(required=true) CreateWalletCommand command ) {
    	Wallet entity = null;

		entity = service.createWallet( command );
		LOGGER.info( "Successfully created Wallet with Id " + entity.getWalletId()  );

		return entity;
    }

    /**
     * Handles updating a Wallet.  if no key provided, calls create, otherwise calls save
     * @param		Wallet wallet
     * @return		Wallet
     */
	@PutMapping("/update")
    public Wallet update( @RequestBody(required=true) UpdateWalletCommand command ) {
		Wallet entity = null;

		entity = service.updateWallet(command);
		LOGGER.info( "Successfully updated Wallet with Id " + command.getWalletId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Wallet entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteWalletCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Wallet with Id " + command.getId()  );
	}
	
    /**
     * Handles loading a Wallet using a UUID
     * @param		UUID uuid 
     * @return		Wallet
     */    
    @GetMapping("/get")
    public Wallet get( @RequestParam(required=true) IdentifierRequest identifier ) {
    	Wallet entity = service.getWallet( new WalletFetchOneSummary( identifier.getId() ) );

		LOGGER.info( "Successfully loaded Wallet with Id " + identifier.getId()   );

        return entity;
    }

    /**
     * Handles loading all Wallet business objects
     * @return		List<Wallet>
     */
    @GetMapping("/")
    public List<Wallet> getAll() {
    	List<Wallet> walletList = null;

		walletList = service.getAllWallet();
		LOGGER.info( "successfully loaded all Wallets" );

        return walletList;
                            
    }

	/**
	 * Handles loading all Customer} business objects
	 * @return		List<Wallet>

    @GetMapping("/Customer")
    public List<Wallet> Customer(UUID parentId) {
		List<Wallet> walletList = load(parentId).getCustomer;
		return walletList;
	}
	 */
    /**
     * save Customer on Wallet
     * @param		command AssignCustomerToWalletCommand
     */     
	@PutMapping("/assignCustomer")
	public void assignCustomer( @RequestBody AssignCustomerToWalletCommand command ) {
		service.assignCustomer( command );
		LOGGER.info( "Successfully assigned Customer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}

    /**
     * unassign Customer on Wallet
     * @param		 command UnAssignCustomerFromWalletCommand
     */     
	@PutMapping("/unassignCustomer")
	public void unAssignCustomer( @RequestBody(required=true)  UnAssignCustomerFromWalletCommand command ) {
		service.unAssignCustomer( command );
		LOGGER.info( "Successfully unassigned Customer with parentId:" + command.getParentId() + ", childId:" + command.getChildId() );
	}
	

	/**
	 * Handles loading all Transactions} business objects
	 * @return		List<Wallet>

    @GetMapping("/Transactions")
    public List<Wallet> Transactions(UUID parentId) {
		List<Wallet> walletList = load(parentId).getTransactions;
		return walletList;
	}

    /**
     * save Transactions on Wallet
     * @param		command AssignTransactionsToWalletCommand
     */     
	@PutMapping("/addToTransactions")
	public void addToTransactions( @RequestBody(required=true) AssignTransactionsToWalletCommand command ) {
		service.addToTransactions( command );
		LOGGER.info( "Successfully added Transactions with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}

    /**
     * remove Transactions on Wallet
     * @param		command RemoveTransactionsFromWalletCommand
     */     	
	@PutMapping("/removeFromTransactions")
	public void removeFromTransactions( 	@RequestBody(required=true) RemoveTransactionsFromWalletCommand command )
	{		
		service.removeFromTransactions( command );
		LOGGER.info( "Successfully removed Transactions with parentId:" + command.getParentId() + ", childIds:" + command.getChildIds()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Wallet wallet = null;
	protected WalletService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(WalletRestController.class.getName());
    
}
