/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 4.0
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */

package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Customer business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Customer related services in the case of a Customer business related service failing.</li>
 * <li>Exposes a simpler, uniform Customer interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Customer business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 4.0</td></tr>
 *          <tr><td>published</td><td>09/29/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class CustomerService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public CustomerService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new CustomerEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(CustomerRepository.class) );
		this.validator		= applicationContext.getBean(CustomerValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		Customer
	 */
		public Customer createCustomer( CreateCustomerCommand command ) {

		Customer entity = new Customer();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setCustomerId( command.getCustomerId() );
            entity.setFirstName( command.getFirstName() );
            entity.setLastName( command.getLastName() );
            entity.setDateOfBirth( command.getDateOfBirth() );
            entity.setEmail( command.getEmail() );
            entity.setPhone( command.getPhone() );
            entity.setAddress( command.getAddress() );
            entity.setTaxId( command.getTaxId() );
            entity.setRiskScore( command.getRiskScore() );
            entity.setCustomerType( command.getCustomerType() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of Customer {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateCustomerCommand
	 * @return		Customer
	 */
	public Customer updateCustomer( UpdateCustomerCommand command ) {

		Customer entity = new Customer();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setCustomerId( command.getCustomerId() );
            entity.setFirstName( command.getFirstName() );
            entity.setLastName( command.getLastName() );
            entity.setDateOfBirth( command.getDateOfBirth() );
            entity.setEmail( command.getEmail() );
            entity.setPhone( command.getPhone() );
            entity.setAddress( command.getAddress() );
            entity.setTaxId( command.getTaxId() );
            entity.setRiskScore( command.getRiskScore() );
            entity.setInstitution( command.getInstitution() );
            entity.setAccounts( command.getAccounts() );
            entity.setWallets( command.getWallets() );
            entity.setCards( command.getCards() );
            entity.setKycProfiles( command.getKycProfiles() );
            entity.setConsents( command.getConsents() );
            entity.setAgreements( command.getAgreements() );
            entity.setLoanApplications( command.getLoanApplications() );
            entity.setLoans( command.getLoans() );
            entity.setPortfolios( command.getPortfolios() );
            entity.setDisputes( command.getDisputes() );
            entity.setCustomerType( command.getCustomerType() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of Customer {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object.
	 * @param		command DeleteCustomerCommand
	 */
	public void delete( DeleteCustomerCommand command ) {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(command.getId());

		LOGGER.info( "done deleting of Customer id:{0} ", command.getId() );

	}

	/**
	 * Method to retrieve the Customer via CustomerFetchOneSummary.
	 * @param 	summary CustomerFetchOneSummary
	 * @return 	CustomerFetchOneResponse
	 */
	public Customer getCustomer( CustomerFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "CustomerFetchOneSummary arg cannot be null" );

		Customer entity = null;
		UUID id = summary.getId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a Customer using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all Customers
	 *
	 * @return 	List<Customer>
	 */
    public List<Customer> getAllCustomer() {
		List<Customer> list = projector.findAll( new FindAllCustomerQuery() );
		return list;
	}

	/**
	 * assign Institution on Customer
	 * @param		command AssignInstitutionToCustomerCommand
	 */
	public void assignInstitution( AssignInstitutionToCustomerCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignInstitution(command.getParentId(), command.getChildId());

	}

	/**
	 * unAssign Institution on Customer
	 * @param		command UnAssignInstitutionFromCustomerCommand
	 */
	public void unAssignInstitution( UnAssignInstitutionFromCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignInstitution(command.getParentId());
	}
	

	/**
	 * add Account to Accounts
	 * @param		command AssignAccountsToCustomerCommand
	 */
	public void addToAccounts( AssignAccountsToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToAccounts(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove Account from Accounts
	 * @param		command RemoveAccountsFromCustomerCommand
	 */
	public void removeFromAccounts( RemoveAccountsFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromAccounts(command.getParentId(), command.getChildIds());
	}

	/**
	 * add Wallet to Wallets
	 * @param		command AssignWalletsToCustomerCommand
	 */
	public void addToWallets( AssignWalletsToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToWallets(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove Wallet from Wallets
	 * @param		command RemoveWalletsFromCustomerCommand
	 */
	public void removeFromWallets( RemoveWalletsFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromWallets(command.getParentId(), command.getChildIds());
	}

	/**
	 * add PaymentCard to Cards
	 * @param		command AssignCardsToCustomerCommand
	 */
	public void addToCards( AssignCardsToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToCards(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove PaymentCard from Cards
	 * @param		command RemoveCardsFromCustomerCommand
	 */
	public void removeFromCards( RemoveCardsFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromCards(command.getParentId(), command.getChildIds());
	}

	/**
	 * add KYCProfile to KycProfiles
	 * @param		command AssignKycProfilesToCustomerCommand
	 */
	public void addToKycProfiles( AssignKycProfilesToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToKycProfiles(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove KYCProfile from KycProfiles
	 * @param		command RemoveKycProfilesFromCustomerCommand
	 */
	public void removeFromKycProfiles( RemoveKycProfilesFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromKycProfiles(command.getParentId(), command.getChildIds());
	}

	/**
	 * add Consent to Consents
	 * @param		command AssignConsentsToCustomerCommand
	 */
	public void addToConsents( AssignConsentsToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToConsents(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove Consent from Consents
	 * @param		command RemoveConsentsFromCustomerCommand
	 */
	public void removeFromConsents( RemoveConsentsFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromConsents(command.getParentId(), command.getChildIds());
	}

	/**
	 * add Agreement to Agreements
	 * @param		command AssignAgreementsToCustomerCommand
	 */
	public void addToAgreements( AssignAgreementsToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToAgreements(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove Agreement from Agreements
	 * @param		command RemoveAgreementsFromCustomerCommand
	 */
	public void removeFromAgreements( RemoveAgreementsFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromAgreements(command.getParentId(), command.getChildIds());
	}

	/**
	 * add LoanApplication to LoanApplications
	 * @param		command AssignLoanApplicationsToCustomerCommand
	 */
	public void addToLoanApplications( AssignLoanApplicationsToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToLoanApplications(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove LoanApplication from LoanApplications
	 * @param		command RemoveLoanApplicationsFromCustomerCommand
	 */
	public void removeFromLoanApplications( RemoveLoanApplicationsFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromLoanApplications(command.getParentId(), command.getChildIds());
	}

	/**
	 * add Loan to Loans
	 * @param		command AssignLoansToCustomerCommand
	 */
	public void addToLoans( AssignLoansToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToLoans(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove Loan from Loans
	 * @param		command RemoveLoansFromCustomerCommand
	 */
	public void removeFromLoans( RemoveLoansFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromLoans(command.getParentId(), command.getChildIds());
	}

	/**
	 * add InvestmentPortfolio to Portfolios
	 * @param		command AssignPortfoliosToCustomerCommand
	 */
	public void addToPortfolios( AssignPortfoliosToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToPortfolios(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove InvestmentPortfolio from Portfolios
	 * @param		command RemovePortfoliosFromCustomerCommand
	 */
	public void removeFromPortfolios( RemovePortfoliosFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromPortfolios(command.getParentId(), command.getChildIds());
	}

	/**
	 * add Dispute to Disputes
	 * @param		command AssignDisputesToCustomerCommand
	 */
	public void addToDisputes( AssignDisputesToCustomerCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToDisputes(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove Dispute from Disputes
	 * @param		command RemoveDisputesFromCustomerCommand
	 */
	public void removeFromDisputes( RemoveDisputesFromCustomerCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromDisputes(command.getParentId(), command.getChildIds());
	}




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final CustomerEntityProjector projector;
	private final CustomerValidator validator;
	private Customer customer 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(CustomerService.class);
}
